In [2]:
import pandas as pd

In [11]:
misplaced_priorities_data_input_path = "data/outputs/mandate_deviation/llm_alignment_results.csv"
use_columns = [
    'ergp_line_item',
    'mda_code',
    'agency',
    'amount',
    'alignment',
    'reason',
]
misplaced_priorities_df = pd.read_csv(misplaced_priorities_data_input_path, usecols=use_columns)

In [12]:
misplaced_priorities_df.head()

,ergp_line_item,mda_code,agency,amount,alignment,reason
0,PROVISION AND INSTALLATION OF SOLAR POWERED ST...,215001001,FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECUR...,1.400000e+09,NO,The budget item covers all 6 geo-political zon...
1,ESTABLISHMENT OF AGRICULTURAL MARKETING INCUBA...,215001001,FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECUR...,4.550000e+08,NO,The agency mandate is specifically for North-E...
2,FOOD SECURITY CROPS VALUE CHAINS DEVELOPMENT P...,215001001,FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECUR...,1.494891e+09,NO,The agency mandate describes the North East De...
3,FOOD SECURITY CROPS VALUE CHAINS DEVELOPMENT P...,215001001,FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECUR...,1.806315e+09,NO,The agency mandate describes the North East De...
4,PROVISION FOR ENHANCED STRATEGIC FOOD RESERVE ...,215001001,FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECUR...,1.862000e+09,NO,The agency mandate describes the North East De...

In [7]:
misplaced_priorities_df.columns.to_list()

['code',
 'ergp_line_item',
 'mda_code',
 'agency',
 'mother_ministry',
 'amount',
 'alignment',
 'confidence',
 'reason',
 'mandate_deviation_score']

In [ ]:
[
    # 'code',
    'ergp_line_item',
    #  'mda_code',
    'agency',
    # 'mother_ministry',
    'amount',
    'alignment',
    # 'confidence',
    'reason',
    # 'mandate_deviation_score'
]

In [ ]:
use_columns = [
    'ergp_line_item',
    'agency',
    'amount',
    'alignment',
    'reason',
]

In [13]:
misplaced_priorities_data_input_path = "data/outputs/mandate_deviation/llm_alignment_results.csv"
use_columns = [
    'ergp_line_item',
    'mda_code',
    'agency',
    'amount',
    'alignment',
    'reason',
]
df = pd.read_csv(misplaced_priorities_data_input_path, usecols=use_columns)


# Get unique agencies for dropdown
agencies = df[['agency']].drop_duplicates().sort_values('agency')

In [14]:
agencies.head()

                                                agency
0    FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECUR...
237  NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE...

In [18]:
# New column names using a dictionary
col_name_dict = {
    "CODE": "line_item_code",
    "LINE ITEM": "line_item_name",
    "AMOUNT": "amount",
    "mda": "mda"
}
input_path = "data/outputs/budget_split_into_capital_and_all_envelopes.xlsx"
sheet_name = "LineItem_Tables"

def ingest_excel(input_path, sheet_name, col_name_dict):

    df = pd.read_excel(input_path, sheet_name=sheet_name)
    df['CODE'] = df['CODE'].astype(str)
    df = df[df['CODE'].str.len() == 8].reset_index(drop=True)
    df = df.rename(columns={df.columns[4]: "mda"})
    df = df.drop(df.columns[3], axis=1)
    df = df.rename(columns=col_name_dict)

    return df

df = ingest_excel(input_path, sheet_name, col_name_dict)

In [16]:
df.head(20)

,line_item_code,line_item_name,amount,mda
0,21010101,SALARY,"1,929,869,076",111001001
1,21020111,REGULAR ALLOWANCES,"397,603,960",111001001
2,21020201,NHIS,"96,493,454",111001001
3,21020202,CONTRIBUTORY PENSION - EMPLOYER'S CONTRIBUTION,"192,986,908",111001001
4,21020212,EMPLOYEES' COMPENSATION SCHEME (ECS),"26,169,534",111001001
5,22020101,LOCAL TRAVEL & TRANSPORT: TRAINING,"275,735,543",111001001
6,22020102,LOCAL TRAVEL & TRANSPORT: OTHERS,"293,302,355",111001001
7,22020104,INTERNATIONAL TRAVEL & TRANSPORT: OTHERS,"2,864,757,769",111001001
8,22020201,ELECTRICITY CHARGES,"311,085,128",111001001
9,22020202,TELEPHONE CHARGES,"3,734,578",111001001
10,22020203,INTERNET ACCESS CHARGES,"22,525,158",111001001
11,22020205,WATER RATES,"15,920,683",111001001
12,22020206,SEWERAGE CHARGES,"12,008,947",111001001
13,22020301,OFFICE STATIONERIES / COMPUTER CONSUMABLES,"36,078,362",111001001
14,22020302,BOOKS,"2,528,168",111001001
15,22020303,NEWSPAPERS,"10,343,883",111001001
16,22020304,MAGAZINES & PERIODICALS,"2,116,069",111001001
17,22020305,PRINTING OF NON SECURITY DOCUMENTS,"17,426,915",111001001
18,22020306,PRINTING OF SECURITY DOCUMENTS,"8,397,827",111001001
19,22020307,DRUGS & MEDICAL SUPPLIES,"43,616,193",111001001

In [19]:
print(len(df))

46134

In [34]:
# Mandate data ingestion
input_path_csv = "data/inputs/combine_mandate_1_50.csv"

mandate_df_1_50 = pd.read_csv(input_path_csv)

In [36]:
mandate_df_1_50.head()

,mda_code,mda_name,mandate_description
0,521025001,"41. COMMUNITY HEALTH TUTOR PROGRAMME, UCH",The Community Health Tutor Programme at the Un...
1,517015001,42. COMPUTER PROFESSIONALS (REGISTRATION COUNC...,The Computer Professionals (Registration Counc...
2,119009118,"43. CONSULATE GENERAL OF NIGERIA, FRANKFURT, G...",The Consulate General of the Federal Republic ...
3,234005001,44. COUNCIL FOR THE REGULATION OF ENGINEERING ...,The Council for the Regulation of Engineering ...
4,229006001,45. COUNCIL FOR THE REGULATION OF FREIGHT FORW...,The Council for the Regulation of Freight Forw...

In [37]:
mandate_df_1_50.dtypes

mda_code                int64
mda_name               object
mandate_description    object
dtype: object

In [141]:
# Mandate data ingestion
input_path = "data/inputs/2026_budget_helper_tables.xlsx"
sheet_name = "mda_mandates"

mandate_df = pd.read_excel(input_path, sheet_name=sheet_name)

mandate_df.columns.values[2] = "mandate_description" # Rename columns

In [142]:
mandate_df.head()

,mda_code,mda_name,mandate_description
0,521002001,NATIONAL HEALTH INSURANCE SCHEME,Originally established by NHIS Act 1999 (...
1,521003001,NATIONAL PRIMARY HEALTH CARE DEVELOPMENT ...,"Established in 1992 by Decree 29 of 1992,..."
2,554001001,FEDERAL MINISTRY OF HUMANITARIAN AFFAIRS ...,Federal Ministry established to coordinat...
3,215001001,FEDERAL MINISTRY OF AGRICULTURE AND FOOD ...,Established by North East Development Com...
4,254006001,NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND M...,Established in 1975 by Research Institute...

In [143]:
mandate_df.dtypes

mda_code                int64
mda_name               object
mandate_description    object
dtype: object

In [18]:
# ERGP budget data ingestion
import os
input_path = "data/outputs/budget_split_into_capital_and_all_envelopes.xlsx"
sheet_name = "ERGP_Tables"

# Check if the file exists
if not os.path.exists(input_path):
    raise FileNotFoundError(f"The file at {input_path} does not exist. Check the path.")

budget_df = pd.read_excel(input_path, sheet_name=sheet_name)

budget_df_column_list = ['code', 'ergp_line_item', 'status', 'amount', 'mda_code']

# final
# budget_df_column_list = ['code', 'ergp_line_item', 'agency', 'mother_ministry', 'amount']

budget_df.columns = budget_df_column_list

In [19]:
budget_df.head()

,code,ergp_line_item,status,amount,mda_code
0,ERGP30102445,UPGRADE OF STATE HOUSE LIBRARY,ONGOING,"9,028,123",111001001
1,ERGP30114992,DIGITAL MEDICAL REFERENCES FOR THE STATE HOUSE...,ONGOING,"3,219,762",111001001
2,ERGP6101477,REHABILITATION OF ANIMAL ENCLOSURE/PROCUREMENT...,ONGOING,"21,850,216",111001001
3,ERGP6114996,CONVERSION/UPGRADE OF VILLA RANCH AND CONSTRUC...,ONGOING,"38,466,135",111001001
4,ERGP6114997,PURCHASE OF PLANT NURSERY EQUIPMENT FOR PRODUC...,ONGOING,"26,912,671",111001001

In [20]:
#  MDA lookup data
input_path = "data/inputs/2026_budget_helper_tables.xlsx"
sheet_name = "2026_mdas"

mda_lookup_table_df = pd.read_excel(input_path, sheet_name=sheet_name)
mda_lookup_table_df = mda_lookup_table_df.iloc[:, :-2]
mda_lookup_table_df = mda_lookup_table_df.dropna()
mda_lookup_table_df['mda_code'] = mda_lookup_table_df['mda_code'].astype(int)


# mda_lookup_table_df['mda_code'] = mda_lookup_table_df['mda_code'].dropna()
# mda_lookup_table_df = mda_lookup_table_df.loc[:, ~mda_lookup_table_df.iloc[0].isna()]

In [21]:
print(len(mda_lookup_table_df))

891

In [22]:
mda_lookup_table_df.tail()

      mda_code                                                mda
886  517004001   WEST AFRICAN EXAMINATION COUNCIL (INTERNATIONAL)
887  517006001           WEST AFRICAN EXAMINATION COUNCIL (LOCAL)
888  125004001         WEST AFRICAN MGT. DEVT. INSTITUTES NETWORK
889  517018019                         YABA COLLEGE OF TECHNOLOGY
890  517021064  YUSUF MAITAMA SULE FEDERAL UNIVERSITY OF EDUCA...

In [23]:
mda_lookup_table_df.dtypes

mda_code     int64
mda         object
dtype: object

In [24]:
budget_df.dtypes

code              object
ergp_line_item    object
status            object
amount            object
mda_code           int64
dtype: object

In [25]:
# Create a dictionary for mapping mda_code to agency from mda_lookup_table_df
mda_mapping = mda_lookup_table_df.set_index('mda_code')['mda'].to_dict()

# Add the "agency" column to budget_df using .map()
budget_df['agency'] = budget_df['mda_code'].map(mda_mapping)
budget_df['mother_ministry'] = ""

In [26]:
budget_df.head()

,code,ergp_line_item,status,amount,mda_code,agency,mother_ministry
0,ERGP30102445,UPGRADE OF STATE HOUSE LIBRARY,ONGOING,"9,028,123",111001001,STATE HOUSE - HQTRS,
1,ERGP30114992,DIGITAL MEDICAL REFERENCES FOR THE STATE HOUSE...,ONGOING,"3,219,762",111001001,STATE HOUSE - HQTRS,
2,ERGP6101477,REHABILITATION OF ANIMAL ENCLOSURE/PROCUREMENT...,ONGOING,"21,850,216",111001001,STATE HOUSE - HQTRS,
3,ERGP6114996,CONVERSION/UPGRADE OF VILLA RANCH AND CONSTRUC...,ONGOING,"38,466,135",111001001,STATE HOUSE - HQTRS,
4,ERGP6114997,PURCHASE OF PLANT NURSERY EQUIPMENT FOR PRODUC...,ONGOING,"26,912,671",111001001,STATE HOUSE - HQTRS,

In [ ]:
# budget_df_column_list = ['code', 'ergp_line_item', 'agency', 'mother_ministry', 'amount']

In [27]:
print(len(budget_df))

28805

In [28]:
# ergp_budget_with_mda_path = "data/outputs/ergp_budget_with_mda.csv"
# budget_df.to_csv(ergp_budget_with_mda_path, index=False)

In [160]:
test_mdas = [
    # 521002001,
    # 521003001,
    # 554001001,
    215001001,
    254006001,
    # 215029001,
    # 254011001
]

In [29]:
test_mdas = [
    521025001,
    517015001,
    119009118,
    234005001,
    229006001,
    326004001,
    257005001,
    535007001,
    252040001,
    517021051,
    515050001,
    517021023,
    252038001,
    228009001,
    161022001,
    238005001,
    111007001,
    111010001,
    161025001,
    256009001,
    238003001,
    535005001,
    252039001,
    555003001,
    124005001,
    215014001,
    344001001,
    158001001,
    116008001,
    521010001,
    521026016,
    517021015,
    517021055,
    125003001,
    116004003,
    123011001,
    215003001,
    215054001,
    521026003,
    517021004,
    116005003,
    116005002,
    233011001,
    517018008,
    517021032,
    517021056,
    521026013,
    252037001,
    517021027,
    140001001
]

In [161]:
test_ergp_budget_df = budget_df[budget_df['mda_code'].isin(test_mdas)]

In [ ]:
print(len(test_ergp_budget_df))

In [30]:
budget_df_1_to_50 = budget_df[budget_df['mda_code'].isin(test_mdas)]

In [39]:
budget_df_1_to_50.head()

,code,ergp_line_item,status,amount,mda_code,agency,mother_ministry
77,ERGP1102191,IT INFRASTRUCTURE AND ASSOCIATED EQUIPMENT\n,ONGOING,"98,175,000",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),
78,ERGP1102209,PURCHASE OF OFFICE FURNITURE AND FITTINGS FOR ...,ONGOING,"14,907,375",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),
79,ERGP1205869,PURCHASE OF LAP TOP AND DESKTOP COMPUTERS FOR ...,ONGOING,"110,726,000",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),
80,ERGP1205905,REMODELING OF SECURITY HOUSE AND BPE MAIN ENTR...,ONGOING,"14,000,000",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),
81,ERGP16234836,"""ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT H...",ONGOING,"14,000,000,000",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),

In [40]:
print(len(budget_df_1_to_50))

2355

In [163]:
test_ergp_budget_df.dtypes

code               object
ergp_line_item     object
status             object
amount             object
mda_code            int64
agency             object
mother_ministry    object
dtype: object

In [164]:
test_ergp_budget_df['amount'] = test_ergp_budget_df['amount'].astype('float64')

ValueError: could not convert string to float: '1,400,000,000'

In [165]:
# Remove commas and convert to float
test_ergp_budget_df['amount'] = test_ergp_budget_df['amount'].str.replace(',', '').astype('float64')

/var/folders/jj/66ym3p5j62s0g7zqbfvfg40c0000gn/T/ipykernel_45606/707382608.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_ergp_budget_df['amount'] = test_ergp_budget_df['amount'].str.replace(',', '').astype('float64')

In [166]:
test_ergp_budget_df.dtypes

code                object
ergp_line_item      object
status              object
amount             float64
mda_code             int64
agency              object
mother_ministry     object
dtype: object

In [167]:
budget_df = test_ergp_budget_df.copy()

In [120]:
"""
Budget-Mandate Semantic Similarity Analysis
============================================
Analyzes alignment between ERGP budget line items and agency mandates
using semantic similarity. Outputs mandate_deviation_score to flag
items potentially outside an agency's mandate.

Author: Abel Akeni
Demo: Ministry of Agriculture - 20 Agencies
"""

import pandas as pd
from sentence_transformers import SentenceTransformer, util


# =============================================================================
# CONFIGURATION
# =============================================================================

MODEL_NAME = "all-MiniLM-L6-v2"
# MODEL_NAME = "all-mpnet-base-v2"

In [116]:

# # =============================================================================
# # SIMILARITY ANALYSIS - before chunking
# # =============================================================================

# def load_model(model_name: str = MODEL_NAME) -> SentenceTransformer:
#     """Load the sentence transformer model."""
#     print(f"Loading model: {model_name}...")
#     model = SentenceTransformer(model_name)
#     print("Model loaded.")
#     return model


# def compute_similarity(model: SentenceTransformer, text1: str, text2: str) -> float:
#     """Compute cosine similarity between two texts."""
#     emb1 = model.encode(text1, convert_to_tensor=True)
#     emb2 = model.encode(text2, convert_to_tensor=True)
#     similarity = util.cos_sim(emb1, emb2)[0][0].item()
#     return similarity


# def compute_mandate_deviation_score(similarity_score: float) -> float:
#     """
#     Compute mandate deviation score as inverse of similarity.
    
#     - similarity = 1.0 (perfect match) → deviation = 0% (not deviant)
#     - similarity = 0.0 (no match) → deviation = 100% (fully deviant)
    
#     Higher deviation score = more likely outside agency mandate = higher audit priority.
#     """
#     deviation = (1 - similarity_score) * 100
#     return round(deviation, 2)


# def analyze_budget_mandate_alignment(
#     budget_df: pd.DataFrame,
#     mandate_df: pd.DataFrame,
#     model: SentenceTransformer
# ) -> pd.DataFrame:
#     """
#     Analyze alignment between budget items and agency mandates.
    
#     Returns DataFrame with added columns:
#     - similarity_score: Cosine similarity (0-1)
#     - mandate_deviation_score: Inverse of similarity (0-100%)
#     """
#     # Create mandate lookup
#     mandate_lookup = dict(zip(mandate_df["mda_code"], mandate_df["mandate_description"]))
    
#     results = []
    
#     print(f"Analyzing {len(budget_df)} budget items...")
    
#     for _, row in budget_df.iterrows():
#         agency = row["mda_code"]
#         budget_item = row["ergp_line_item"]
#         mandate = mandate_lookup.get(agency, "")
        
#         if mandate:
#             similarity = compute_similarity(model, budget_item, mandate)
#         else:
#             similarity = 0.0
        
#         deviation = compute_mandate_deviation_score(similarity)
        
#         results.append({
#             "code": row["code"],
#             "ergp_line_item": row["ergp_line_item"],
#             "mda": row["agency"],
#             "mother_ministry": row["mother_ministry"],
#             "amount": row["amount"],
#             "similarity_score": round(similarity, 4),
#             "mandate_deviation_score": deviation
#         })
    
#     print("Analysis complete.")
#     return pd.DataFrame(results)

In [126]:
# =============================================================================
# CHUNKING FUNCTIONS
# =============================================================================

def chunk_mandate(mandate_text: str) -> list[str]:
    """
    Split mandate into meaningful chunks.
    
    Strategy:
    1. If mandate has numbered points (1), (2), etc → split by numbers, skip intro
    2. If no numbered points → split by sentences
    3. Clean up: remove short chunks
    """
    import re
    
    MIN_CHUNK_WORDS = 10
    
    # Check if mandate has numbered points like (1), (2), etc.
    has_numbers = bool(re.search(r'\(\d+\)', mandate_text))
    
    if has_numbers:
        # Split by numbered points, skip intro (text before first number)
        parts = re.split(r'\(\d+\)\s*', mandate_text)
        chunks = parts[1:] if len(parts) > 1 else parts
    else:
        # Split by sentences
        chunks = re.split(r'(?<=[.!?])\s+', mandate_text)
    
    # Clean up: strip whitespace, remove short chunks
    cleaned = []
    for chunk in chunks:
        chunk = chunk.strip().rstrip(';,.')
        if chunk and len(chunk.split()) >= MIN_CHUNK_WORDS:
            cleaned.append(chunk)
    
    return cleaned if cleaned else [mandate_text]  # Fallback to full text


# =============================================================================
# SIMILARITY ANALYSIS
# =============================================================================

def load_model(model_name: str = MODEL_NAME) -> SentenceTransformer:
    """Load the sentence transformer model."""
    print(f"Loading model: {model_name}...")
    model = SentenceTransformer(model_name)
    print("Model loaded.")
    return model


def compute_mandate_deviation_score(similarity_score: float) -> float:
    """
    Compute mandate deviation score as inverse of similarity.
    
    - similarity = 1.0 (perfect match) → deviation = 0% (not deviant)
    - similarity = 0.0 (no match) → deviation = 100% (fully deviant)

    Higher deviation score = more likely outside agency mandate = higher audit priority.
    """
    deviation = (1 - similarity_score) * 100
    return round(deviation, 2)


def analyze_budget_mandate_alignment(
    budget_df: pd.DataFrame,
    mandate_df: pd.DataFrame,
    model: SentenceTransformer
) -> pd.DataFrame:
    """
    Analyze alignment between budget items and agency mandates.
    
    Returns DataFrame with added columns:
    - similarity_score: Cosine similarity (0-1)
    - mandate_deviation_score: Inverse of similarity (0-100%)
    """
    # === PRE-ENCODE MANDATE CHUNKS ===
    print("Pre-computing mandate chunk embeddings...")
    mandate_embeddings = {}
    for _, row in mandate_df.iterrows():
        mda_code = row["mda_code"]
        chunks = chunk_mandate(row["mandate_description"])
        mandate_embeddings[mda_code] = model.encode(chunks, convert_to_tensor=True)
    print(f"Chunked and embedded {len(mandate_embeddings)} agency mandates.")
    
    # === PRE-ENCODE ALL LINE ITEMS (NEW) ===
    print(f"Pre-computing embeddings for {len(budget_df)} line items...")
    all_line_items = budget_df["ergp_line_item"].tolist()
    all_item_embeddings = model.encode(all_line_items, convert_to_tensor=True)
    print("Line item embeddings complete.")
    
    # === COMPUTE SIMILARITIES ===
    print("Computing similarities...")
    results = []
    
    for i, (_, row) in enumerate(budget_df.iterrows()):
        mda_code = row["mda_code"]
        item_embedding = all_item_embeddings[i]
        chunk_embeddings = mandate_embeddings.get(mda_code)
        
        if chunk_embeddings is not None:
            similarities = util.cos_sim(item_embedding, chunk_embeddings)[0]
            similarity = similarities.max().item()
        else:
            similarity = 0.0
        
        deviation = compute_mandate_deviation_score(similarity)
        
        results.append({
            "code": row["code"],
            "ergp_line_item": row["ergp_line_item"],
            "agency": row["agency"],
            "mother_ministry": row["mother_ministry"],
            "amount": row["amount"],
            "similarity_score": round(similarity, 4),
            "mandate_deviation_score": deviation
        })
    
    print("Analysis complete.")
    return pd.DataFrame(results)

In [127]:
# =============================================================================
# OUTPUT & REPORTING
# =============================================================================

def print_results_table(result_df: pd.DataFrame) -> None:
    """Print the full results table."""
    print("\n" + "=" * 100)
    print("RESULTS: Budget-Mandate Semantic Similarity Analysis")
    print("=" * 100)
    
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)
    pd.set_option('display.max_colwidth', 45)
    
    print(result_df.to_string(index=False))


def print_summary(result_df: pd.DataFrame) -> None:
    """Print summary statistics."""
    print("\n" + "=" * 100)
    print("SUMMARY")
    print("=" * 100)
    
    total_items = len(result_df)
    total_amount = result_df["amount"].sum()
    avg_similarity = result_df["similarity_score"].mean()
    avg_deviation = result_df["mandate_deviation_score"].mean()
    
    # Flag items with high deviation (>60%)
    high_deviation = result_df[result_df["mandate_deviation_score"] > 60]
    flagged_count = len(high_deviation)
    flagged_amount = high_deviation["amount"].sum()
    
    print(f"Total Budget Items: {total_items}")
    print(f"Total Budget Amount: ₦{total_amount:,.0f}")
    print(f"Average Similarity Score: {avg_similarity:.4f}")
    print(f"Average Mandate Deviation Score: {avg_deviation:.2f}%")
    print(f"\nItems with Deviation > 60%: {flagged_count}")
    print(f"Flagged Amount: ₦{flagged_amount:,.0f} ({(flagged_amount/total_amount)*100:.1f}% of total)")


def print_flagged_items(result_df: pd.DataFrame, threshold: float = 60.0) -> None:
    """Print items flagged for audit review."""
    flagged = result_df[result_df["mandate_deviation_score"] > threshold].sort_values(
        "mandate_deviation_score", ascending=False
    )
    
    print("\n" + "=" * 100)
    print(f"FLAGGED FOR AUDIT REVIEW (Deviation > {threshold}%)")
    print("=" * 100)
    
    for _, row in flagged.iterrows():
        print(f"\n🚨 {row['code']}: {row['ergp_line_item'][:55]}...")
        print(f"   Agency: {row['agency']}")
        print(f"   Amount: ₦{row['amount']:,.0f}")
        print(f"   Similarity: {row['similarity_score']:.4f} | Deviation: {row['mandate_deviation_score']:.1f}%")


def export_to_csv(result_df: pd.DataFrame, filepath: str) -> None:
    """Export results to CSV."""
    result_df.to_csv(filepath, index=False)
    print(f"\n✅ Results exported to: {filepath}")

In [128]:

# =============================================================================
# MAIN EXECUTION
# =============================================================================


"""Main execution pipeline."""
print("\n" + "=" * 100)
print("BUDGET-MANDATE SEMANTIC SIMILARITY ANALYSIS")
print("Ministry of Agriculture - 20 Agencies Demo")
print("=" * 100)

# 1. Generate data
budget_df = test_ergp_budget_df.copy()
# mandate_df = mandate_df.copy()
print(f"\nLoaded {len(budget_df)} budget items, {len(mandate_df)} agency mandates")

# 2. Load model
model = load_model()
print("\n model loaded")


# 3. Run analysis
result_df = analyze_budget_mandate_alignment(budget_df, mandate_df, model)
print("\n Analysis run")

# 4. Output results
print_results_table(result_df)
print_summary(result_df)
print_flagged_items(result_df, threshold=60.0)

# 5. Export
export_to_csv(result_df, "similarity_results_with_chunking.csv")
    
# return result_df



# results = main()

====================================================================================================
BUDGET-MANDATE SEMANTIC SIMILARITY ANALYSIS
Ministry of Agriculture - 20 Agencies Demo
====================================================================================================

Loaded 1070 budget items, 7 agency mandates
Loading model: all-MiniLM-L6-v2...
Model loaded.

 model loaded
Pre-computing mandate chunk embeddings...
Chunked and embedded 7 agency mandates.
Pre-computing embeddings for 1070 line items...
Line item embeddings complete.
Computing similarities...
Analysis complete.

 Analysis run

====================================================================================================
RESULTS: Budget-Mandate Semantic Similarity Analysis
====================================================================================================
        code                                                                                                                                        ergp_line_item                                                           agency mother_ministry       amount  similarity_score  mandate_deviation_score
ERGP10175045                                             PROVISION AND INSTALLATION OF SOLAR POWERED STREETLIGHT IN RURAL COMMUNITIES IN THE 6 GEO-POLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.400000e+09            0.2394                    76.06
 ERGP1208767                                     ESTABLISHMENT OF AGRICULTURAL MARKETING INCUBATION CENTRES FOR YOUTH AND WOMEN ACROSS THE SIX GEO-POLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 4.550000e+08            0.3025                    69.75
 ERGP1208771                                                                                                 FOOD SECURITY CROPS VALUE CHAINS DEVELOPMENT PROGRAMS        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.494891e+09            0.2843                    71.57
 ERGP1208772                                                                                   FOOD SECURITY CROPS VALUE CHAINS DEVELOPMENT PROGRAMS ON CASH CROPS        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.806315e+09            0.2238                    77.62
 ERGP1208802                                                              PROVISION FOR ENHANCED STRATEGIC FOOD RESERVE FOR FOOD SECURITY AND MARKET STABILIZATION        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.862000e+09            0.1962                    80.38
ERGP12175035                                                                        CONSTRUCTION OF FEEDER ROADS IN RURAL COMMUNITIES IN THE 6 GEO-POLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 2.514894e+09            0.4092                    59.08
ERGP16193867                                                                IMPLEMENTATION OF MANPOWER DEVELOPMENT STRATEGIES TO IMPROVE AGRICULTURAL PRODUCTIVITY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 2.107000e+08            0.3458                    65.42
ERGP16231491                                                                                            IMPLEMENTATION OF FCSSIP POLICY TO ENHANCE FOOD SECURITY\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.724000e+08            0.2374                    76.26
ERGP18208797                      REHABILITATION AND CALIBRATION OF FGN RETAINED SILO COMPLEXES IN READINESS FOR STRATEGIC FOOD RESERVE STOCKING FOR FOOD SECURITY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.040000e+08            0.2269                    77.31
ERGP27105258                                                                                                   INFRASTRUCTURES AND PROJECTS SUPPORT COORDINATION\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 6.722100e+08            0.3943                    60.57
ERGP27174747                                                                          UPGRADE OF FACILITIES IN THE HEADQUARTERS BUILDING (OLD) AND STATE OFFICES\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.250000e+08            0.3051                    69.49
ERGP27174760                                                                                                   CONSTRUCTION OF FMARD HEADQUARTERS OFFICE COMPLEX\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.670000e+09            0.2371                    76.29
ERGP27231566                                              CONSTRUCTION OF PUBLIC TOILETS, RURAL MARKETS AND HOUSING INFRASTRUCTURES IN THE SIX GEO-POLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.648936e+08            0.4352                    56.48
ERGP28175039                                                                         PROVISION OF PORTABLE WATER IN RURAL COMMUNITIES IN THE 6 GEO-POLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.050000e+09            0.3862                    61.38
ERGP30105248                                                                                                         CONTRIBUTION TO INTERNATIONAL ORGANIZATIONS\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.177888e+08            0.3340                    66.60
ERGP30126578                                                                                                RESEARCH ON HUMAN CAPITAL DEVELOPMENT IN AGRICULTURE\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.850000e+08            0.3324                    66.76
ERGP30159116                                                                                    COUNTERPART FUNDING OF AGRICULTURAL PROJECTS WITH DONOR AGENCIES\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.116495e+08            0.3736                    62.64
ERGP30174655                                                                                   SURVEYING AND MAPPING OF ACQUIRED MINISTRY'S LANDS AND FACILITIES\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.057591e+07            0.3248                    67.52
ERGP30174685                                                                                               IMPLEMENTATION OF AGRICULTURAL FOOD SECURITY PROGRAMS\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.500000e+08            0.2299                    77.01
ERGP30174912                                                                                               NATIONAL COUNCIL ON AGRICULTURE AND RURAL DEVELOPMENT\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.298000e+08            0.3706                    62.94
ERGP30175085                                                                                                                MAINSTREAMING GENDER IN AGRIBUSINESS\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 6.075178e+08            0.2491                    75.09
ERGP30175109                                                           NATIONAL PROGRAMME FOR THE CONTROL OF TRANSBOUNDARY PESTS AND INTEGRATED PESTS SURVEILLANCE        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.500000e+08            0.2259                    77.41
ERGP30193870                                                                         INFRASTRUCUTURES DEVELOPMENT IN THE 37 FIELD AND 6 ZONAL COORDINATING OFFICES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.000000e+08            0.3384                    66.16
ERGP30208758                                                                              AGRICULTURE AND FOOD SECURITY STAKEHOLDERS' ANALYSIS AND MAPPING STUDY\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.520924e+07            0.3018                    69.82
ERGP30208761       REVIEW OF EXISTING AGRICULTURAL LAWS AND DRAFTING OF NEW ONES TO SUPPORT AGRIBUSINESS AND INVESTMENTS FOR AGRICULTURAL DEVELOPMENT AND FOOD AND        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.400000e+08            0.2692                    73.08
ERGP30208768                                               INSTITUTIONALIZING THE NIGERIAN FOOD SYSTEM DASHBOARD ON THE STATE OF FOOD AND NUTRITION IN THE COUNTRY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.750000e+09            0.3859                    61.41
ERGP30208769                                                     DEVELOPMENT OF DIGITAL MOBILE-BASED EXTENSION AND ADVISORY SYSTEM TO SUPPORT FARMERS PRODUCTIVITY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.756998e+08            0.2766                    72.34
ERGP30208770                                               DEVELOPMENT AND IMPLEMENTATION OF THE NATIONAL FARMERS SOIL HEALTH CARD SCHEME TO INCREASE PRODUCTIVITY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 8.400000e+08            0.2121                    78.79
ERGP30208774                                                                               FOOD SECURITY CROPS VALUE CHAINS DEVELOPMENT PROGRAMS ON EXPORT CROPS\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.063646e+09            0.2256                    77.44
ERGP30208781                   EDUCATION PROMOTION OF HOME GARDEN, HOME ECONOMICS AND NUTRITION KNOWLEDGE TRANSFER AND PRACTICE AT THE STATE AND LOCAL GOVERNMENTS        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 4.767424e+08            0.3325                    66.75
ERGP30208782                                                               DEVELOPMENT AND ESTABLISHMENT OF NATIONAL AGRICULTURAL DATABASE CENTRE FOR PRODUCTIVITY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 2.227364e+08            0.3293                    67.07
ERGP30208785                                            DEVELOPMENT OF FRAMEWORK AND CONDUCT OF TECHNOLOGY / ICT ENABLED FARMS AND FARMERS ENUMERATION AND MAPPING        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 8.400000e+08            0.3212                    67.88
ERGP30208786           CAPACITY BUILDING ON PROJECTS MONITORING EVALUATION, ACCOUNTABILITY AND LEARNING FOR EFFICIENCY AND HIGH PERFORMANCE FOR FOOD AND NUTRITION        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 2.829364e+08            0.4591                    54.09
ERGP30208793                           DEVELOPMENT OF A NATIONAL AGRICULTURAL MECHANISATION ENTERPRISE DEVELOPMENT SCHEME FOR YOUTH AGRIPRENEURS TOWARDS INCREASED        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.500000e+08            0.2896                    71.04
ERGP30208795                                            DEVELOPMENT OF ICT TOOLS FOR AGRICULTURE PRODUCTIVITY THROUGH YOUTH HACKATHON FOR CLIMATE SMART TECHNOLOGY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.039752e+07            0.3015                    69.85
ERGP30208799             DEVELOPMENT AND IMPLEMENTATION OF STRATEGIC COMMUNICATION TO PROMOTE AGRICULTURE AND FOOD SECURITY VALUE CHAINS DEVELOPMENT AND KNOWLEDGE        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.057591e+08            0.2969                    70.31
ERGP30208807       PROVISION OF INFRASTRUCTURE FOR INTERNATIONAL PUBLIC SECTOR ACCOUNTING STANDARD (IPSAS) & CAPACITY BUILDING FOR ACCOUNTS AND BUDGET OFFICERS ON        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.147954e+08            0.3202                    67.98
ERGP30208810                                             FIELD AND PROTECTIVEGEARS FOR VISIT AND OPERATIONAL SUPERVISION OF AGRICULTURE AND FOOD SECURITY PROJECTS        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 4.200000e+08            0.3653                    63.47
ERGP30231444                                                                                     EXTENSION SERVICES SUPPORT TO ALL THE AGRICULTURAL VALUE CHAINS\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 9.416051e+08            0.2239                    77.61
ERGP30231450                                                                            PROMOTION OF CLIMATE SMART FOOD PRODUCTION PROGRAMME FOR YOUTH EMPOWERMENT        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 2.035883e+08            0.2896                    71.04
ERGP30231454                                                                                         IMPLEMENTATION OF ECOWAS AGRO-ECOLOGY PROGRAMMES IN NIGERIA\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.500000e+08            0.4237                    57.63
ERGP30231485                          ESTABLISHMENT OF AGRICULTURE INNOVATION HUB IN THE MINISTRY AND STAKEHOLDERS ENGAGEMENT IN LINE WITH PRESIDENTIAL PRIORITIES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.400000e+08            0.3809                    61.91
ERGP30231488                   PROMOTION AND DEVELOPMENT OF AGRICULTURAL VALUE CHAIN COOPERATIVES TO SCALE UP FOOD PRODUCTION AND ENSURE FOOD SECURITY FOR NIGERIA        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.658000e+08            0.3642                    63.58
ERGP30231504             ESTABLISHMENT OF COTTAGE AND SMALL SCALE AGRO PROCESSING INDUSTRIES IN SELECTED STATES FOR VALUE ADDITION, EMPLOYMENT GENERATION AND FOOD        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 2.310000e+08            0.2424                    75.76
ERGP30231508                                         DEVELOPMENT OF A COMPENDIUM OF AGRO-BASE EQUIPMENT MANUFACTURERS, FABRICATORS, AND AGRO PROCESSORS IN NIGERIA        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.750000e+08            0.4461                    55.39
ERGP30231510                                                                             ESTABLISHMENT OF THE AGRO-PRODUCE CONDITIONING CENTRES IN FARM CLUSTERS\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.400000e+08            0.2055                    79.45
ERGP30231512                                        PROMOTION OF LOCAL FABRICATION OF AGRO PROCESSING TOOLS, EQUIPMENT AND MACHINERY FOR PROMOTION OF AGRIBUSINESS        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.000000e+07            0.2024                    79.76
ERGP30231514                                                             SUPPORT FOR AGRO PROCESSORS IN THE ACQUISITION OF EQUIPMENT FOR AGRICULTURAL VALUE CHAINS        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 2.310000e+08            0.2048                    79.52
ERGP30231515                                                   AGRIBUSINESS TRAINING FOR MSMES WOMEN AND YOUTHS TO BE CARRIED OUT ACROSS THE 3 GEO-POLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.260000e+08            0.3515                    64.85
ERGP30231516                                                                                         UPGRADE OF MARKETS IN LOCAL COMMUNITIES IN SELECTED STATES.\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 3.500000e+08            0.2390                    76.10
ERGP30231518                                       DEVELOPMENT OF COLD CHAIN FACILITIES TO SUPPORT FARMERS IN SOME SELECTED STATES ACROSS THE 3 GEOPOLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.820000e+08            0.3896                    61.04
ERGP30231519                                        DEVELOPMENT AND CAPACITY BUILDING ON AGRICULTURAL PRODUCT IMPROVEMENT FOR VALUE ADDITION AND INCOME GENERATION        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.050000e+08            0.3073                    69.27
ERGP30231520                                      COLLABORATION WITH DEVELOPMENT PARTNERS IN CAPACITY BUILDING FOR STANDARD OF EXPORTABLE CROP FOR ZERO REJECTION.        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.360639e+07            0.2652                    73.48
ERGP30231562                                                                                          DEVELOPMENT AND IMPROVEMENT OF FMAFS CAREER IN AGRICULTURE\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 6.930000e+07            0.3160                    68.40
ERGP30231563                                                                                    PROFESSIONALIZATION OF THE HUMAN RESOURCES MANAGEMENT DEPARTMENT\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 4.760000e+07            0.2374                    76.26
ERGP30231565                                                                      ELECTRIFICATION OF AGRO AND RURAL INDUSTRIAL COMMUNITIES IN 2 GEOPOLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.000000e+08            0.4587                    54.13
ERGP30231570                                   RURAL NON-FARM EMPOWERMENT SUPPORT (PROMOTION OF MICRO SMALL MEDIUM ENTERPRISE -MSMEs) IN THE 6 GEO-POLITICAL ZONES        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.083477e+08            0.3692                    63.08
ERGP30231571                            STRENTHENING MOBILIZATION & AWARENESS CREATION , NEEDS ASSESMENT IN RURAL COMMUNITIES FOR IMPROVED AGRICULTURAL PRODUCTION        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 9.180124e+07            0.3217                    67.83
ERGP30237810                                                      CONSTRUCTION OF MALE AND FEMALE HOSTELS IN NABANJE FEDERAL COLLEGE OF AGRICULTURE AND TECHNOLOGY        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 1.400000e+09            0.2896                    71.04
ERGP30237813                                                                                                                    CONSTRUCTION OF COMPUTER CENTRES\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 7.000000e+08            0.2376                    76.24
ERGP30237818                                                                                                  CONSTRUCTION OF RESIDENT FOR RECTOR WITH FINISHING\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.600000e+08            0.3095                    69.05
ERGP30237821                                                                                CONSTRUCTION OF HOUSES FOR BURSER AND CHEIF LABRERIAN WITH FINISHING\n        FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS                 5.950000e+08            0.1967                    80.33

In [112]:
show_these = ['code', 'ergp_line_item', 'mda', 'amount', 'similarity_score', 'mandate_deviation_score']
result_df[show_these].head()

,code,ergp_line_item,mda,amount,similarity_score,mandate_deviation_score
0,ERGP10175045,PROVISION AND INSTALLATION OF SOLAR POWER...,FEDERAL MINISTRY OF AGRICULTURE AND FOOD ...,1.400000e+09,0.1947,80.53
1,ERGP1208767,ESTABLISHMENT OF AGRICULTURAL MARKETING I...,FEDERAL MINISTRY OF AGRICULTURE AND FOOD ...,4.550000e+08,0.2792,72.08
2,ERGP1208771,FOOD SECURITY CROPS VALUE CHAINS DEVELOPM...,FEDERAL MINISTRY OF AGRICULTURE AND FOOD ...,1.494891e+09,0.2154,78.46
3,ERGP1208772,FOOD SECURITY CROPS VALUE CHAINS DEVELOPM...,FEDERAL MINISTRY OF AGRICULTURE AND FOOD ...,1.806315e+09,0.1729,82.71
4,ERGP1208802,PROVISION FOR ENHANCED STRATEGIC FOOD RES...,FEDERAL MINISTRY OF AGRICULTURE AND FOOD ...,1.862000e+09,0.1785,82.15

In [ ]:
# 5. Export
export_to_csv(result_df, "similarity_results2.csv")

✅ Results exported to: similarity_results2.csv

In [ ]:
# code	ergp_line_item	mda	amount	similarity_score	mandate_deviation_score

### LLM-AS-JUDGE:

In [42]:
# =============================================================================
# LLM-AS-JUDGE: CLAUDE API IMPLEMENTATION
# =============================================================================

import anthropic
import pandas as pd
import time
from typing import Optional
import os
from dotenv import load_dotenv


# =============================================================================
# CONFIGURATION
# =============================================================================


ANTHROPIC_API_KEY = os.getenv("CLAUDE_API_KEY")

MODEL_NAME = "claude-sonnet-4-20250514"  # Good balance of speed/cost/quality
MAX_RETRIES = 3
RETRY_DELAY = 2  # seconds

In [43]:
# =============================================================================
# CORE FUNCTIONS
# =============================================================================

def create_client(api_key: str = ANTHROPIC_API_KEY) -> anthropic.Anthropic:
    """Create Anthropic client."""
    return anthropic.Anthropic(api_key=api_key)


def judge_alignment(
    client: anthropic.Anthropic,
    line_item: str,
    agency: str,
    mandate: str
) -> dict:
    """
    Use Claude to judge if budget item aligns with agency mandate.
    
    Returns:
        dict with keys: alignment, confidence, reason
    """
    prompt = f"""You are an auditor checking if Nigerian government budget items align with agency mandates.

    AGENCY: {agency}

    AGENCY MANDATE: {mandate}

    BUDGET LINE ITEM: {line_item}

    Does this budget item fall within the agency's mandate?

    Respond in EXACTLY this format (no other text):
    ALIGNMENT: YES or PARTIAL or NO
    CONFIDENCE: HIGH or MEDIUM or LOW
    REASON: (one sentence explanation)"""

    for attempt in range(MAX_RETRIES):
        try:
            response = client.messages.create(
                model=MODEL_NAME,
                max_tokens=150,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            
            result_text = response.content[0].text
            return parse_llm_response(result_text)
            
        except Exception as e:
            if attempt < MAX_RETRIES - 1:
                print(f"   Retry {attempt + 1}/{MAX_RETRIES} after error: {e}")
                time.sleep(RETRY_DELAY)
            else:
                print(f"   Failed after {MAX_RETRIES} attempts: {e}")
                return {
                    "alignment": "ERROR",
                    "confidence": "UNKNOWN",
                    "reason": str(e)
                }


def parse_llm_response(response: str) -> dict:
    """Parse the structured LLM response."""
    result = {
        "alignment": "UNKNOWN",
        "confidence": "UNKNOWN",
        "reason": ""
    }
    
    lines = response.strip().split("\n")
    
    for line in lines:
        line = line.strip()
        if line.upper().startswith("ALIGNMENT:"):
            value = line.split(":", 1)[1].strip().upper()
            if value in ["YES", "PARTIAL", "NO"]:
                result["alignment"] = value
        elif line.upper().startswith("CONFIDENCE:"):
            value = line.split(":", 1)[1].strip().upper()
            if value in ["HIGH", "MEDIUM", "LOW"]:
                result["confidence"] = value
        elif line.upper().startswith("REASON:"):
            result["reason"] = line.split(":", 1)[1].strip()
    
    return result


def compute_deviation_score(alignment: str, confidence: str) -> float:
    """
    Convert alignment + confidence to a deviation score (0-100).
    
    Higher score = more likely outside mandate = higher audit priority.
    """
    alignment_scores = {
        "YES": 0,
        "PARTIAL": 50,
        "NO": 100,
        "UNKNOWN": 50,
        "ERROR": 50
    }
    
    confidence_adjustments = {
        "HIGH": 0,
        "MEDIUM": 5,
        "LOW": 10,
        "UNKNOWN": 10
    }
    
    base_score = alignment_scores.get(alignment, 50)
    adjustment = confidence_adjustments.get(confidence, 10)
    
    # For YES: add adjustment (less confident YES = slightly higher deviation)
    # For NO: subtract adjustment (less confident NO = slightly lower deviation)
    if alignment == "YES":
        return min(base_score + adjustment, 100)
    elif alignment == "NO":
        return max(base_score - adjustment, 0)
    else:
        return base_score


# =============================================================================
# MAIN ANALYSIS FUNCTION
# =============================================================================

def analyze_budget_mandate_alignment_llm(
    budget_df: pd.DataFrame,
    mandate_df: pd.DataFrame,
    api_key: str = ANTHROPIC_API_KEY,
    progress_interval: int = 10
) -> pd.DataFrame:
    """
    Analyze alignment between budget items and agency mandates using Claude.
    
    Args:
        budget_df: DataFrame with columns [code, ergp_line_item, mda_code, agency, mother_ministry, amount]
        mandate_df: DataFrame with columns [mda_code, mda_name, mandate_description]
        api_key: Anthropic API key
        progress_interval: Print progress every N items
        
    Returns:
        DataFrame with alignment results
    """
    # Create client
    client = create_client(api_key)
    
    # Create mandate lookup by mda_code
    mandate_lookup = dict(zip(mandate_df["mda_code"], mandate_df["mandate_description"]))
    
    results = []
    total_items = len(budget_df)
    
    print(f"Analyzing {total_items} budget items with Claude...")
    print(f"Estimated time: {total_items * 1.5 / 60:.1f} - {total_items * 2.5 / 60:.1f} minutes")
    print("=" * 60)
    
    start_time = time.time()
    
    for i, (_, row) in enumerate(budget_df.iterrows()):
        mda_code = row["mda_code"]
        line_item = row["ergp_line_item"]
        agency = row["agency"]
        mandate = mandate_lookup.get(mda_code, "")
        
        if mandate:
            judgement = judge_alignment(client, line_item, agency, mandate)
        else:
            judgement = {
                "alignment": "UNKNOWN",
                "confidence": "UNKNOWN",
                "reason": "No mandate found for this agency"
            }
        
        deviation = compute_deviation_score(
            judgement["alignment"], 
            judgement["confidence"]
        )
        
        results.append({
            "code": row["code"],
            "ergp_line_item": row["ergp_line_item"],
            "mda_code": row["mda_code"],
            "agency": row["agency"],
            "mother_ministry": row["mother_ministry"],
            "amount": row["amount"],
            "alignment": judgement["alignment"],
            "confidence": judgement["confidence"],
            "reason": judgement["reason"],
            "mandate_deviation_score": deviation
        })
        
        # Progress update
        if (i + 1) % progress_interval == 0 or (i + 1) == total_items:
            elapsed = time.time() - start_time
            rate = (i + 1) / elapsed
            remaining = (total_items - i - 1) / rate if rate > 0 else 0
            print(f"   Processed {i + 1}/{total_items} ({(i+1)/total_items*100:.1f}%) | "
                  f"Elapsed: {elapsed/60:.1f}min | Remaining: {remaining/60:.1f}min")
    
    print("=" * 60)
    print("Analysis complete.")
    
    return pd.DataFrame(results)

In [44]:
# =============================================================================
# OUTPUT & REPORTING
# =============================================================================

def print_summary_llm(result_df: pd.DataFrame) -> None:
    """Print summary statistics for LLM analysis."""
    print("\n" + "=" * 80)
    print("SUMMARY: LLM-AS-JUDGE ANALYSIS")
    print("=" * 80)
    
    total_items = len(result_df)
    total_amount = result_df["amount"].sum()
    
    # Alignment distribution
    alignment_counts = result_df["alignment"].value_counts()
    
    print(f"\nTotal Budget Items: {total_items}")
    print(f"Total Budget Amount: ₦{total_amount:,.0f}")
    
    print(f"\nAlignment Distribution:")
    for alignment, count in alignment_counts.items():
        pct = count / total_items * 100
        amount = result_df[result_df["alignment"] == alignment]["amount"].sum()
        print(f"   {alignment}: {count} items ({pct:.1f}%) | ₦{amount:,.0f}")
    
    # Flagged items (NO alignment)
    flagged = result_df[result_df["alignment"] == "NO"]
    print(f"\n🚨 Items flagged as NOT aligned: {len(flagged)}")
    print(f"   Flagged amount: ₦{flagged['amount'].sum():,.0f}")


def print_flagged_items_llm(result_df: pd.DataFrame, top_n: int = 20) -> None:
    """Print items flagged as not aligned."""
    flagged = result_df[result_df["alignment"] == "NO"].sort_values(
        "amount", ascending=False
    ).head(top_n)
    
    if len(flagged) == 0:
        print("\n✅ No items flagged as misaligned!")
        return
    
    print("\n" + "=" * 100)
    print(f"TOP {top_n} FLAGGED ITEMS (NOT ALIGNED)")
    print("=" * 100)
    
    for _, row in flagged.iterrows():
        print(f"\n🚨 {row['code']}: {row['ergp_line_item'][:60]}...")
        print(f"   Agency: {row['agency']}")
        print(f"   Amount: ₦{row['amount']:,.0f}")
        print(f"   Confidence: {row['confidence']}")
        print(f"   Reason: {row['reason']}")

In [171]:
# =============================================================================
# EXAMPLE USAGE
# =============================================================================


# Example usage (replace with your actual data)

# 1. Set your API key
api_key = ANTHROPIC_API_KEY

# 2. Run analysis
result_df = analyze_budget_mandate_alignment_llm(
    budget_df=budget_df,
    mandate_df=mandate_df,
    api_key=api_key,
    progress_interval=10
)

# 3. View results
print_summary_llm(result_df)
print_flagged_items_llm(result_df)

# 4. Export
result_df.to_csv("llm_alignment_results.csv", index=False)

pass

Analyzing 451 budget items with Claude...
Estimated time: 11.3 - 18.8 minutes
============================================================
   Processed 10/451 (2.2%) | Elapsed: 0.6min | Remaining: 25.5min
   Processed 20/451 (4.4%) | Elapsed: 1.1min | Remaining: 24.3min
   Processed 30/451 (6.7%) | Elapsed: 1.7min | Remaining: 23.6min
   Processed 40/451 (8.9%) | Elapsed: 2.2min | Remaining: 22.9min
   Processed 50/451 (11.1%) | Elapsed: 2.9min | Remaining: 22.9min
   Processed 60/451 (13.3%) | Elapsed: 3.4min | Remaining: 22.3min
   Processed 70/451 (15.5%) | Elapsed: 4.0min | Remaining: 21.8min
   Processed 80/451 (17.7%) | Elapsed: 4.6min | Remaining: 21.2min
   Processed 90/451 (20.0%) | Elapsed: 5.1min | Remaining: 20.6min
   Processed 100/451 (22.2%) | Elapsed: 5.7min | Remaining: 20.0min
   Processed 110/451 (24.4%) | Elapsed: 6.3min | Remaining: 19.4min
   Processed 120/451 (26.6%) | Elapsed: 6.8min | Remaining: 18.9min
   Processed 130/451 (28.8%) | Elapsed: 7.4min | Remaining: 18.2min
   Processed 140/451 (31.0%) | Elapsed: 7.9min | Remaining: 17.6min
   Processed 150/451 (33.3%) | Elapsed: 8.5min | Remaining: 17.1min
   Processed 160/451 (35.5%) | Elapsed: 9.1min | Remaining: 16.5min
   Processed 170/451 (37.7%) | Elapsed: 10.5min | Remaining: 17.4min
   Processed 180/451 (39.9%) | Elapsed: 11.1min | Remaining: 16.7min
   Processed 190/451 (42.1%) | Elapsed: 11.6min | Remaining: 16.0min
   Processed 200/451 (44.3%) | Elapsed: 12.2min | Remaining: 15.4min
   Processed 210/451 (46.6%) | Elapsed: 12.8min | Remaining: 14.7min
   Processed 220/451 (48.8%) | Elapsed: 13.4min | Remaining: 14.0min
   Processed 230/451 (51.0%) | Elapsed: 13.9min | Remaining: 13.4min
   Processed 240/451 (53.2%) | Elapsed: 17.1min | Remaining: 15.0min
   Processed 250/451 (55.4%) | Elapsed: 17.7min | Remaining: 14.2min
   Processed 260/451 (57.6%) | Elapsed: 18.1min | Remaining: 13.3min
   Processed 270/451 (59.9%) | Elapsed: 18.7min | Remaining: 12.5min
   Processed 280/451 (62.1%) | Elapsed: 19.2min | Remaining: 11.7min
   Processed 290/451 (64.3%) | Elapsed: 19.7min | Remaining: 11.0min
   Processed 300/451 (66.5%) | Elapsed: 20.3min | Remaining: 10.2min
   Processed 310/451 (68.7%) | Elapsed: 20.8min | Remaining: 9.5min
   Processed 320/451 (71.0%) | Elapsed: 21.3min | Remaining: 8.7min
   Processed 330/451 (73.2%) | Elapsed: 21.9min | Remaining: 8.0min
   Processed 340/451 (75.4%) | Elapsed: 22.4min | Remaining: 7.3min
   Processed 350/451 (77.6%) | Elapsed: 23.0min | Remaining: 6.6min
   Processed 360/451 (79.8%) | Elapsed: 23.5min | Remaining: 5.9min
   Processed 370/451 (82.0%) | Elapsed: 24.1min | Remaining: 5.3min
   Processed 380/451 (84.3%) | Elapsed: 24.6min | Remaining: 4.6min
   Processed 390/451 (86.5%) | Elapsed: 25.1min | Remaining: 3.9min
   Processed 400/451 (88.7%) | Elapsed: 25.6min | Remaining: 3.3min
   Processed 410/451 (90.9%) | Elapsed: 26.2min | Remaining: 2.6min
   Processed 420/451 (93.1%) | Elapsed: 26.7min | Remaining: 2.0min
   Processed 430/451 (95.3%) | Elapsed: 27.3min | Remaining: 1.3min
   Processed 440/451 (97.6%) | Elapsed: 27.8min | Remaining: 0.7min
   Processed 450/451 (99.8%) | Elapsed: 28.3min | Remaining: 0.1min
   Processed 451/451 (100.0%) | Elapsed: 28.4min | Remaining: 0.0min
============================================================
Analysis complete.

================================================================================
SUMMARY: LLM-AS-JUDGE ANALYSIS
================================================================================

Total Budget Items: 451
Total Budget Amount: ₦329,078,544,931

Alignment Distribution:
   NO: 401 items (88.9%) | ₦324,119,345,945
   YES: 29 items (6.4%) | ₦2,246,244,010
   PARTIAL: 21 items (4.7%) | ₦2,712,954,976

🚨 Items flagged as NOT aligned: 401
   Flagged amount: ₦324,119,345,945

====================================================================================================
TOP 20 FLAGGED ITEMS (NOT ALIGNED)
====================================================================================================

🚨 ERGP5234138: MULTILATERAL/BILATERAL TIED LOAN - SPECIAL AGRO INDUSTRIAL P...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦126,019,673,910
   Confidence: HIGH
   Reason: The budget item for agricultural processing zones does not align with the North East Development Commission's specific mandate focused on post-insurgency rehabilitation and reconstruction in six northeastern states.

🚨 ERGP5234139: MULTILATERAL/BILATERAL TIED LOAN - VALUE CHAIN DEVELOPMENT P...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦37,500,000,000
   Confidence: HIGH
   Reason: The agency mandate describes the North East Development Commission focused on insurgency recovery and reconstruction in six northeastern states, but the agency name is Federal Ministry of Agriculture and Food Security, creating a complete mismatch between the agricultural value chain development project and the stated insurgency-focused mandate.

🚨 ERGP1239720: BAKALORI DAM REHABILITATION ZAMFARA
...
   Agency: NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE RESEARCH
   Amount: ₦7,000,000,000
   Confidence: HIGH
   Reason: Bakalori Dam rehabilitation in Zamfara is an inland freshwater infrastructure project that falls completely outside NIOMR's mandate which focuses exclusively on marine and oceanographic research in territorial waters and high seas.

🚨 ERGP27174760: CONSTRUCTION OF FMARD HEADQUARTERS OFFICE COMPLEX
...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦5,670,000,000
   Confidence: HIGH
   Reason: The construction of FMARD headquarters office complex is unrelated to the North East Development Commission's mandate which specifically focuses on post-insurgency reconstruction and development in six northeastern states.

🚨 ERGP5234137: MULTILATERAL/BILATERAL TIED LOAN - RURAL ACCESS AND AGRICULT...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦4,607,142,855
   Confidence: HIGH
   Reason: The agency mandate describes the North East Development Commission focused on insurgency rehabilitation in six northeastern states, but the budget item is assigned to the Federal Ministry of Agriculture and Food Security, creating a complete mismatch between the agency name and its stated mandate.

🚨 ERGP10239756: SOLAR LIGHT PROVISION R.E.A
...
   Agency: NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE RESEARCH
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Solar light provision through the Rural Electrification Agency (R.E.A) is completely outside NIOMR's mandate which focuses exclusively on marine research, oceanography, fisheries, and blue economy development.

🚨 ERGP30237855: RENEWED HOPE INITIATIVE
...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The mandate provided is for the North East Development Commission (focused on insurgency rehabilitation in six specific states) but is incorrectly attributed to the Federal Ministry of Agriculture and Food Security, and the generic "Renewed Hope Initiative" budget item does not align with the specific North-East reconstruction and rehabilitation mandate described.

🚨 ERGP28239734: NITU LAKE REHABLIBATION
...
   Agency: NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE RESEARCH
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Lake rehabilitation falls outside NIOMR's mandate which specifically focuses on marine and oceanographic research in territorial waters and high seas, not freshwater lake ecosystems.

🚨 ERGP30237915: SUPPLIES OF GRAINS TO SELECTED STATES IN THE FEDERATION
...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦3,150,000,000
   Confidence: HIGH
   Reason: The mandate described is for the North East Development Commission focused on insurgency recovery in six specific states, but the agency name is Federal Ministry of Agriculture and Food Security, creating a complete mismatch between the stated agency and its described mandate.

🚨 ERGP30239703: PROVISION FOR MINI TRACTORS AND IMPLEMENTS BAKALORI DAM ZAMF...
   Agency: NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE RESEARCH
   Amount: ₦2,800,000,000
   Confidence: HIGH
   Reason: The provision of mini tractors and implements for Bakalori Dam in Zamfara relates to terrestrial agricultural activities, which falls completely outside NIOMR's mandate focused exclusively on marine and oceanographic research.

🚨 ERGP30239703: PROVISION FOR MINI TRACTORS AND IMPLEMENTS BAKALORI DAM ZAMF...
   Agency: NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE RESEARCH
   Amount: ₦2,800,000,000
   Confidence: HIGH
   Reason: The provision of mini tractors and implements for Bakalori Dam in Zamfara relates to terrestrial agricultural activities, which falls completely outside NIOMR's mandate focused exclusively on marine and oceanographic research.

🚨 ERGP12175035: CONSTRUCTION OF FEEDER ROADS IN RURAL COMMUNITIES IN THE 6 G...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦2,514,893,597
   Confidence: HIGH
   Reason: The budget item covers all 6 geo-political zones while the agency's mandate is specifically limited to the North-East zone comprising only 6 states (Adamawa, Bauchi, Borno, Gombe, Taraba, and Yobe).

🚨 ERGP1208802: PROVISION FOR ENHANCED STRATEGIC FOOD RESERVE FOR FOOD SECUR...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦1,862,000,000
   Confidence: HIGH
   Reason: The agency mandate describes the North East Development Commission focused on post-insurgency reconstruction and rehabilitation, while the agency name indicates the Federal Ministry of Agriculture, creating a complete mismatch with a food security budget item that would align with agricultural ministry functions but not commission mandates.

🚨 ERGP1208772: FOOD SECURITY CROPS VALUE CHAINS DEVELOPMENT PROGRAMS ON CAS...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦1,806,314,570
   Confidence: HIGH
   Reason: The agency mandate describes the North East Development Commission focused on insurgency victim rehabilitation and reconstruction, but the agency name is Federal Ministry of Agriculture and Food Security, creating a clear mismatch where the budget item aligns with the agency name but not the stated mandate.

🚨 ERGP30208768: INSTITUTIONALIZING THE NIGERIAN FOOD SYSTEM DASHBOARD ON THE...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦1,750,000,000
   Confidence: HIGH
   Reason: The budget item relates to establishing a national food system dashboard which falls under agricultural and food security functions, but the agency mandate described is specifically for the North East Development Commission focused on insurgency victim rehabilitation and reconstruction in six northeastern states.

🚨 ERGP1208771: FOOD SECURITY CROPS VALUE CHAINS DEVELOPMENT PROGRAMS...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦1,494,891,133
   Confidence: HIGH
   Reason: The agency mandate describes the North East Development Commission focused on post-insurgency reconstruction and rehabilitation, but the agency name indicates the Federal Ministry of Agriculture and Food Security, creating a clear mismatch where food security programs would align with the ministry name but not the stated NEDC mandate.

🚨 ERGP30237921: SUPPLY AND DISTRIBUTION OF 70 HORSE POWER TRACTORS LIGHT DUT...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦1,470,000,000
   Confidence: HIGH
   Reason: The agency mandate described is for the North East Development Commission focused on insurgency recovery and reconstruction, but the agency name is Federal Ministry of Agriculture and Food Security, creating a clear mismatch between the agricultural budget item and the stated insurgency-focused mandate.

🚨 ERGP30237824: CONSTRUCTION OF FENCING
...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: The agency mandate provided is for the North East Development Commission (focused on insurgency recovery in six northeastern states), which does not match the Federal Ministry of Agriculture and Food Security, and construction of fencing does not align with either agency's core functions.

🚨 ERGP30239710: PROCUREMENT OF FERTILIZERS FOR BAKALORI FARMERS ZAMFARA
...
   Agency: NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE RESEARCH
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Procurement of fertilizers for terrestrial farming in Zamfara falls completely outside NIOMR's marine and oceanographic research mandate, which focuses exclusively on territorial waters, marine resources, and aquaculture rather than land-based agriculture.

🚨 ERGP30237827: CONSTRUCTION OF LABROTERIES
...
   Agency: FEDERAL MINISTRY OF AGRICULTURE AND FOOD SECURITY - HQTRS
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: The agency mandate provided is for the North East Development Commission (focused on insurgency victims and regional reconstruction), but the agency name is Federal Ministry of Agriculture and Food Security, creating a clear mismatch where laboratory construction doesn't align with the insurgency-focused mandate listed.

In [172]:
mandate_df.head()

,mda_code,mda_name,mandate_description
0,521002001,NATIONAL HEALTH INSURANCE SCHEME,Originally established by NHIS Act 1999 (...
1,521003001,NATIONAL PRIMARY HEALTH CARE DEVELOPMENT ...,"Established in 1992 by Decree 29 of 1992,..."
2,554001001,FEDERAL MINISTRY OF HUMANITARIAN AFFAIRS ...,Federal Ministry established to coordinat...
3,215001001,FEDERAL MINISTRY OF AGRICULTURE AND FOOD ...,Established by North East Development Com...
4,254006001,NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND M...,Established in 1975 by Research Institute...

In [ ]:
# =============================================================================
#  USAGE 1 - 50
# =============================================================================
# budget_df_1_to_50
# mandate_df_1_50

# Example usage (replace with your actual data)

# 1. Set your API key
api_key = ANTHROPIC_API_KEY

# 2. Run analysis
result_df = analyze_budget_mandate_alignment_llm(
    budget_df=budget_df_1_to_50,
    mandate_df=mandate_df_1_50,
    api_key=api_key,
    progress_interval=10
)

Analyzing 2355 budget items with Claude...
Estimated time: 58.9 - 98.1 minutes
============================================================
   Processed 10/2355 (0.4%) | Elapsed: 0.5min | Remaining: 126.7min
   Processed 20/2355 (0.8%) | Elapsed: 1.1min | Remaining: 122.7min
   Processed 30/2355 (1.3%) | Elapsed: 1.6min | Remaining: 121.5min
   Processed 40/2355 (1.7%) | Elapsed: 2.1min | Remaining: 123.0min
   Processed 50/2355 (2.1%) | Elapsed: 3.4min | Remaining: 156.8min
   Processed 60/2355 (2.5%) | Elapsed: 3.9min | Remaining: 150.2min
   Processed 70/2355 (3.0%) | Elapsed: 4.5min | Remaining: 145.7min
   Processed 80/2355 (3.4%) | Elapsed: 4.9min | Remaining: 140.7min
   Processed 90/2355 (3.8%) | Elapsed: 5.4min | Remaining: 137.0min
   Processed 100/2355 (4.2%) | Elapsed: 6.0min | Remaining: 134.6min
   Processed 110/2355 (4.7%) | Elapsed: 6.5min | Remaining: 132.7min
   Processed 120/2355 (5.1%) | Elapsed: 7.0min | Remaining: 130.8min
   Processed 130/2355 (5.5%) | Elapsed: 7.5min | Remaining: 129.0min
   Processed 140/2355 (5.9%) | Elapsed: 8.2min | Remaining: 129.0min
   Processed 150/2355 (6.4%) | Elapsed: 8.7min | Remaining: 127.5min
   Processed 160/2355 (6.8%) | Elapsed: 9.2min | Remaining: 126.3min
   Processed 170/2355 (7.2%) | Elapsed: 9.8min | Remaining: 125.5min
   Processed 180/2355 (7.6%) | Elapsed: 10.3min | Remaining: 124.2min
   Processed 190/2355 (8.1%) | Elapsed: 10.8min | Remaining: 122.7min
   Processed 200/2355 (8.5%) | Elapsed: 11.3min | Remaining: 121.6min
   Processed 210/2355 (8.9%) | Elapsed: 11.8min | Remaining: 120.4min
   Processed 220/2355 (9.3%) | Elapsed: 12.3min | Remaining: 119.3min
   Processed 230/2355 (9.8%) | Elapsed: 12.8min | Remaining: 118.4min
   Processed 240/2355 (10.2%) | Elapsed: 13.4min | Remaining: 117.9min
   Processed 250/2355 (10.6%) | Elapsed: 13.9min | Remaining: 117.1min
   Processed 260/2355 (11.0%) | Elapsed: 14.4min | Remaining: 116.3min
   Processed 270/2355 (11.5%) | Elapsed: 15.0min | Remaining: 115.8min
   Processed 280/2355 (11.9%) | Elapsed: 15.6min | Remaining: 115.3min
   Processed 290/2355 (12.3%) | Elapsed: 16.1min | Remaining: 114.7min
   Processed 300/2355 (12.7%) | Elapsed: 16.6min | Remaining: 114.0min
   Processed 310/2355 (13.2%) | Elapsed: 17.2min | Remaining: 113.2min
   Processed 320/2355 (13.6%) | Elapsed: 17.7min | Remaining: 112.3min
   Processed 330/2355 (14.0%) | Elapsed: 18.2min | Remaining: 111.6min
   Processed 340/2355 (14.4%) | Elapsed: 18.7min | Remaining: 110.8min
   Processed 350/2355 (14.9%) | Elapsed: 19.2min | Remaining: 110.1min
   Processed 360/2355 (15.3%) | Elapsed: 19.7min | Remaining: 109.4min
   Processed 370/2355 (15.7%) | Elapsed: 20.3min | Remaining: 108.8min
   Processed 380/2355 (16.1%) | Elapsed: 20.8min | Remaining: 108.0min
   Processed 390/2355 (16.6%) | Elapsed: 21.3min | Remaining: 107.2min
   Processed 400/2355 (17.0%) | Elapsed: 21.9min | Remaining: 107.1min
   Processed 410/2355 (17.4%) | Elapsed: 22.5min | Remaining: 106.5min
   Processed 420/2355 (17.8%) | Elapsed: 23.0min | Remaining: 106.1min
   Processed 430/2355 (18.3%) | Elapsed: 23.6min | Remaining: 105.6min
   Processed 440/2355 (18.7%) | Elapsed: 24.1min | Remaining: 104.9min
   Processed 450/2355 (19.1%) | Elapsed: 24.6min | Remaining: 104.3min
   Processed 460/2355 (19.5%) | Elapsed: 25.2min | Remaining: 103.6min
   Processed 470/2355 (20.0%) | Elapsed: 25.7min | Remaining: 103.0min
   Processed 480/2355 (20.4%) | Elapsed: 26.2min | Remaining: 102.4min
   Processed 490/2355 (20.8%) | Elapsed: 26.8min | Remaining: 101.9min
   Processed 500/2355 (21.2%) | Elapsed: 27.3min | Remaining: 101.3min
   Processed 510/2355 (21.7%) | Elapsed: 27.9min | Remaining: 100.8min
   Processed 520/2355 (22.1%) | Elapsed: 28.4min | Remaining: 100.2min
   Processed 530/2355 (22.5%) | Elapsed: 28.9min | Remaining: 99.6min
   Processed 540/2355 (22.9%) | Elapsed: 29.5min | Remaining: 99.0min
   Processed 550/2355 (23.4%) | Elapsed: 30.0min | Remaining: 98.6min
   Processed 560/2355 (23.8%) | Elapsed: 30.6min | Remaining: 98.0min
   Processed 570/2355 (24.2%) | Elapsed: 31.1min | Remaining: 97.2min
   Processed 580/2355 (24.6%) | Elapsed: 31.6min | Remaining: 96.6min
   Processed 590/2355 (25.1%) | Elapsed: 32.1min | Remaining: 95.9min
   Processed 600/2355 (25.5%) | Elapsed: 32.6min | Remaining: 95.3min
   Processed 610/2355 (25.9%) | Elapsed: 33.1min | Remaining: 94.6min
   Processed 620/2355 (26.3%) | Elapsed: 33.6min | Remaining: 94.0min
   Processed 630/2355 (26.8%) | Elapsed: 34.1min | Remaining: 93.3min
   Processed 640/2355 (27.2%) | Elapsed: 34.6min | Remaining: 92.6min
   Processed 650/2355 (27.6%) | Elapsed: 35.1min | Remaining: 92.0min
   Processed 660/2355 (28.0%) | Elapsed: 35.6min | Remaining: 91.5min
   Processed 670/2355 (28.5%) | Elapsed: 36.1min | Remaining: 90.8min
   Processed 680/2355 (28.9%) | Elapsed: 36.6min | Remaining: 90.3min
   Processed 690/2355 (29.3%) | Elapsed: 37.1min | Remaining: 89.6min
   Processed 700/2355 (29.7%) | Elapsed: 37.7min | Remaining: 89.0min
   Processed 710/2355 (30.1%) | Elapsed: 38.2min | Remaining: 88.5min
   Processed 720/2355 (30.6%) | Elapsed: 38.7min | Remaining: 87.8min
   Processed 730/2355 (31.0%) | Elapsed: 39.2min | Remaining: 87.2min
   Processed 740/2355 (31.4%) | Elapsed: 39.7min | Remaining: 86.6min
   Processed 750/2355 (31.8%) | Elapsed: 40.2min | Remaining: 86.0min
   Processed 760/2355 (32.3%) | Elapsed: 40.7min | Remaining: 85.4min
   Processed 770/2355 (32.7%) | Elapsed: 41.2min | Remaining: 84.9min
   Processed 780/2355 (33.1%) | Elapsed: 41.8min | Remaining: 84.3min
   Processed 790/2355 (33.5%) | Elapsed: 42.3min | Remaining: 83.8min
   Processed 800/2355 (34.0%) | Elapsed: 42.8min | Remaining: 83.2min
   Processed 810/2355 (34.4%) | Elapsed: 43.4min | Remaining: 82.7min
   Processed 820/2355 (34.8%) | Elapsed: 43.9min | Remaining: 82.1min
   Processed 830/2355 (35.2%) | Elapsed: 44.4min | Remaining: 81.7min
   Processed 840/2355 (35.7%) | Elapsed: 45.0min | Remaining: 81.2min
   Processed 850/2355 (36.1%) | Elapsed: 45.6min | Remaining: 80.7min
   Processed 860/2355 (36.5%) | Elapsed: 46.1min | Remaining: 80.2min
   Processed 870/2355 (36.9%) | Elapsed: 46.7min | Remaining: 79.6min
   Processed 880/2355 (37.4%) | Elapsed: 47.2min | Remaining: 79.1min
   Processed 890/2355 (37.8%) | Elapsed: 47.7min | Remaining: 78.5min
   Processed 900/2355 (38.2%) | Elapsed: 48.2min | Remaining: 77.9min
   Processed 910/2355 (38.6%) | Elapsed: 48.8min | Remaining: 77.4min
   Processed 920/2355 (39.1%) | Elapsed: 49.3min | Remaining: 76.8min
   Processed 930/2355 (39.5%) | Elapsed: 49.8min | Remaining: 76.3min
   Processed 940/2355 (39.9%) | Elapsed: 50.3min | Remaining: 75.7min
   Processed 950/2355 (40.3%) | Elapsed: 50.8min | Remaining: 75.2min
   Processed 960/2355 (40.8%) | Elapsed: 51.3min | Remaining: 74.6min
   Processed 970/2355 (41.2%) | Elapsed: 51.8min | Remaining: 74.0min
   Processed 980/2355 (41.6%) | Elapsed: 52.3min | Remaining: 73.4min
   Processed 990/2355 (42.0%) | Elapsed: 52.8min | Remaining: 72.9min
   Processed 1000/2355 (42.5%) | Elapsed: 53.4min | Remaining: 72.3min
   Processed 1010/2355 (42.9%) | Elapsed: 53.9min | Remaining: 71.8min
   Processed 1020/2355 (43.3%) | Elapsed: 54.4min | Remaining: 71.2min
   Processed 1030/2355 (43.7%) | Elapsed: 54.9min | Remaining: 70.6min
   Processed 1040/2355 (44.2%) | Elapsed: 55.4min | Remaining: 70.1min
   Processed 1050/2355 (44.6%) | Elapsed: 55.9min | Remaining: 69.5min
   Processed 1060/2355 (45.0%) | Elapsed: 56.4min | Remaining: 68.9min
   Processed 1070/2355 (45.4%) | Elapsed: 56.9min | Remaining: 68.3min
   Processed 1080/2355 (45.9%) | Elapsed: 57.4min | Remaining: 67.8min
   Processed 1090/2355 (46.3%) | Elapsed: 57.9min | Remaining: 67.2min
   Processed 1100/2355 (46.7%) | Elapsed: 58.4min | Remaining: 66.7min
   Processed 1110/2355 (47.1%) | Elapsed: 59.0min | Remaining: 66.2min
   Processed 1120/2355 (47.6%) | Elapsed: 59.5min | Remaining: 65.6min
   Processed 1130/2355 (48.0%) | Elapsed: 60.0min | Remaining: 65.1min
   Processed 1140/2355 (48.4%) | Elapsed: 60.5min | Remaining: 64.5min
   Processed 1150/2355 (48.8%) | Elapsed: 61.0min | Remaining: 64.0min
   Processed 1160/2355 (49.3%) | Elapsed: 61.6min | Remaining: 63.4min
   Processed 1170/2355 (49.7%) | Elapsed: 62.1min | Remaining: 62.9min
   Processed 1180/2355 (50.1%) | Elapsed: 62.7min | Remaining: 62.4min
   Processed 1190/2355 (50.5%) | Elapsed: 63.2min | Remaining: 61.9min
   Processed 1200/2355 (51.0%) | Elapsed: 63.8min | Remaining: 61.4min
   Processed 1210/2355 (51.4%) | Elapsed: 64.3min | Remaining: 60.9min
   Processed 1220/2355 (51.8%) | Elapsed: 64.9min | Remaining: 60.3min
   Processed 1230/2355 (52.2%) | Elapsed: 65.4min | Remaining: 59.8min
   Processed 1240/2355 (52.7%) | Elapsed: 65.9min | Remaining: 59.3min
   Processed 1250/2355 (53.1%) | Elapsed: 66.4min | Remaining: 58.7min
   Processed 1260/2355 (53.5%) | Elapsed: 67.0min | Remaining: 58.2min
   Processed 1270/2355 (53.9%) | Elapsed: 67.5min | Remaining: 57.7min
   Processed 1280/2355 (54.4%) | Elapsed: 68.0min | Remaining: 57.1min
   Processed 1290/2355 (54.8%) | Elapsed: 68.5min | Remaining: 56.6min
   Processed 1300/2355 (55.2%) | Elapsed: 69.1min | Remaining: 56.1min
   Processed 1310/2355 (55.6%) | Elapsed: 69.6min | Remaining: 55.5min
   Processed 1320/2355 (56.1%) | Elapsed: 70.1min | Remaining: 55.0min
   Processed 1330/2355 (56.5%) | Elapsed: 70.7min | Remaining: 54.5min
   Processed 1340/2355 (56.9%) | Elapsed: 71.2min | Remaining: 54.0min
   Processed 1350/2355 (57.3%) | Elapsed: 71.8min | Remaining: 53.4min
   Processed 1360/2355 (57.7%) | Elapsed: 72.3min | Remaining: 52.9min
   Processed 1370/2355 (58.2%) | Elapsed: 72.8min | Remaining: 52.4min
   Processed 1380/2355 (58.6%) | Elapsed: 73.3min | Remaining: 51.8min
   Processed 1390/2355 (59.0%) | Elapsed: 73.9min | Remaining: 51.3min
   Processed 1400/2355 (59.4%) | Elapsed: 74.4min | Remaining: 50.7min
   Processed 1410/2355 (59.9%) | Elapsed: 74.9min | Remaining: 50.2min
   Processed 1420/2355 (60.3%) | Elapsed: 75.5min | Remaining: 49.7min
   Processed 1430/2355 (60.7%) | Elapsed: 76.0min | Remaining: 49.2min
   Processed 1440/2355 (61.1%) | Elapsed: 76.6min | Remaining: 48.7min
   Processed 1450/2355 (61.6%) | Elapsed: 77.2min | Remaining: 48.2min
   Processed 1460/2355 (62.0%) | Elapsed: 77.8min | Remaining: 47.7min
   Processed 1470/2355 (62.4%) | Elapsed: 78.3min | Remaining: 47.1min
   Processed 1480/2355 (62.8%) | Elapsed: 78.9min | Remaining: 46.6min
   Processed 1490/2355 (63.3%) | Elapsed: 79.4min | Remaining: 46.1min
   Processed 1500/2355 (63.7%) | Elapsed: 79.9min | Remaining: 45.6min
   Processed 1510/2355 (64.1%) | Elapsed: 80.5min | Remaining: 45.0min
   Processed 1520/2355 (64.5%) | Elapsed: 81.0min | Remaining: 44.5min
   Processed 1530/2355 (65.0%) | Elapsed: 81.5min | Remaining: 43.9min
   Processed 1540/2355 (65.4%) | Elapsed: 82.0min | Remaining: 43.4min
   Processed 1550/2355 (65.8%) | Elapsed: 82.4min | Remaining: 42.8min
   Processed 1560/2355 (66.2%) | Elapsed: 83.0min | Remaining: 42.3min
   Processed 1570/2355 (66.7%) | Elapsed: 83.6min | Remaining: 41.8min
   Processed 1580/2355 (67.1%) | Elapsed: 84.1min | Remaining: 41.2min
   Processed 1590/2355 (67.5%) | Elapsed: 84.6min | Remaining: 40.7min
   Processed 1600/2355 (67.9%) | Elapsed: 85.1min | Remaining: 40.2min
   Processed 1610/2355 (68.4%) | Elapsed: 85.7min | Remaining: 39.6min
   Processed 1620/2355 (68.8%) | Elapsed: 86.2min | Remaining: 39.1min
   Processed 1630/2355 (69.2%) | Elapsed: 86.7min | Remaining: 38.5min
   Processed 1640/2355 (69.6%) | Elapsed: 87.2min | Remaining: 38.0min
   Processed 1650/2355 (70.1%) | Elapsed: 87.7min | Remaining: 37.5min
   Processed 1660/2355 (70.5%) | Elapsed: 88.2min | Remaining: 36.9min
   Processed 1670/2355 (70.9%) | Elapsed: 88.8min | Remaining: 36.4min
   Processed 1680/2355 (71.3%) | Elapsed: 89.3min | Remaining: 35.9min
   Processed 1690/2355 (71.8%) | Elapsed: 89.8min | Remaining: 35.4min
   Processed 1700/2355 (72.2%) | Elapsed: 90.4min | Remaining: 34.8min
   Processed 1710/2355 (72.6%) | Elapsed: 90.9min | Remaining: 34.3min
   Processed 1720/2355 (73.0%) | Elapsed: 91.5min | Remaining: 33.8min
   Processed 1730/2355 (73.5%) | Elapsed: 92.0min | Remaining: 33.2min
   Processed 1740/2355 (73.9%) | Elapsed: 92.6min | Remaining: 32.7min
   Processed 1750/2355 (74.3%) | Elapsed: 93.1min | Remaining: 32.2min
   Processed 1760/2355 (74.7%) | Elapsed: 93.8min | Remaining: 31.7min
   Processed 1770/2355 (75.2%) | Elapsed: 94.3min | Remaining: 31.2min
   Processed 1780/2355 (75.6%) | Elapsed: 94.9min | Remaining: 30.6min
   Processed 1790/2355 (76.0%) | Elapsed: 95.4min | Remaining: 30.1min
   Processed 1800/2355 (76.4%) | Elapsed: 95.9min | Remaining: 29.6min
   Processed 1810/2355 (76.9%) | Elapsed: 96.5min | Remaining: 29.1min
   Processed 1820/2355 (77.3%) | Elapsed: 97.1min | Remaining: 28.5min
   Processed 1830/2355 (77.7%) | Elapsed: 97.6min | Remaining: 28.0min
   Processed 1840/2355 (78.1%) | Elapsed: 98.1min | Remaining: 27.5min
   Processed 1850/2355 (78.6%) | Elapsed: 98.7min | Remaining: 26.9min
   Processed 1860/2355 (79.0%) | Elapsed: 99.3min | Remaining: 26.4min
   Processed 1870/2355 (79.4%) | Elapsed: 99.8min | Remaining: 25.9min
   Processed 1880/2355 (79.8%) | Elapsed: 100.3min | Remaining: 25.3min
   Processed 1890/2355 (80.3%) | Elapsed: 100.8min | Remaining: 24.8min
   Processed 1900/2355 (80.7%) | Elapsed: 101.3min | Remaining: 24.3min
   Processed 1910/2355 (81.1%) | Elapsed: 101.9min | Remaining: 23.7min
   Processed 1920/2355 (81.5%) | Elapsed: 102.5min | Remaining: 23.2min
   Processed 1930/2355 (82.0%) | Elapsed: 103.0min | Remaining: 22.7min
   Processed 1940/2355 (82.4%) | Elapsed: 103.6min | Remaining: 22.2min
   Processed 1950/2355 (82.8%) | Elapsed: 104.1min | Remaining: 21.6min
   Processed 1960/2355 (83.2%) | Elapsed: 104.6min | Remaining: 21.1min
   Processed 1970/2355 (83.7%) | Elapsed: 105.2min | Remaining: 20.6min
   Processed 1980/2355 (84.1%) | Elapsed: 105.8min | Remaining: 20.0min
   Processed 1990/2355 (84.5%) | Elapsed: 106.3min | Remaining: 19.5min
   Processed 2000/2355 (84.9%) | Elapsed: 106.9min | Remaining: 19.0min
   Processed 2010/2355 (85.4%) | Elapsed: 107.4min | Remaining: 18.4min
   Processed 2020/2355 (85.8%) | Elapsed: 108.0min | Remaining: 17.9min
   Processed 2030/2355 (86.2%) | Elapsed: 108.6min | Remaining: 17.4min
   Processed 2040/2355 (86.6%) | Elapsed: 109.1min | Remaining: 16.8min
   Processed 2050/2355 (87.0%) | Elapsed: 109.7min | Remaining: 16.3min
   Processed 2060/2355 (87.5%) | Elapsed: 110.2min | Remaining: 15.8min
   Processed 2070/2355 (87.9%) | Elapsed: 110.7min | Remaining: 15.2min
   Processed 2080/2355 (88.3%) | Elapsed: 111.3min | Remaining: 14.7min
   Processed 2090/2355 (88.7%) | Elapsed: 111.8min | Remaining: 14.2min
   Processed 2100/2355 (89.2%) | Elapsed: 112.3min | Remaining: 13.6min
   Processed 2110/2355 (89.6%) | Elapsed: 112.8min | Remaining: 13.1min
   Processed 2120/2355 (90.0%) | Elapsed: 113.4min | Remaining: 12.6min
   Processed 2130/2355 (90.4%) | Elapsed: 113.9min | Remaining: 12.0min
   Processed 2140/2355 (90.9%) | Elapsed: 114.4min | Remaining: 11.5min
   Processed 2150/2355 (91.3%) | Elapsed: 115.0min | Remaining: 11.0min
   Processed 2160/2355 (91.7%) | Elapsed: 115.5min | Remaining: 10.4min
   Processed 2170/2355 (92.1%) | Elapsed: 116.1min | Remaining: 9.9min
   Processed 2180/2355 (92.6%) | Elapsed: 116.6min | Remaining: 9.4min
   Processed 2190/2355 (93.0%) | Elapsed: 117.1min | Remaining: 8.8min
   Processed 2200/2355 (93.4%) | Elapsed: 117.6min | Remaining: 8.3min
   Processed 2210/2355 (93.8%) | Elapsed: 118.1min | Remaining: 7.8min
   Processed 2220/2355 (94.3%) | Elapsed: 118.7min | Remaining: 7.2min
   Processed 2230/2355 (94.7%) | Elapsed: 119.2min | Remaining: 6.7min
   Processed 2240/2355 (95.1%) | Elapsed: 119.8min | Remaining: 6.1min
   Processed 2250/2355 (95.5%) | Elapsed: 120.3min | Remaining: 5.6min
   Processed 2260/2355 (96.0%) | Elapsed: 120.8min | Remaining: 5.1min
   Processed 2270/2355 (96.4%) | Elapsed: 121.2min | Remaining: 4.5min
   Processed 2280/2355 (96.8%) | Elapsed: 121.8min | Remaining: 4.0min
   Processed 2290/2355 (97.2%) | Elapsed: 122.3min | Remaining: 3.5min
   Processed 2300/2355 (97.7%) | Elapsed: 122.8min | Remaining: 2.9min
   Processed 2310/2355 (98.1%) | Elapsed: 123.3min | Remaining: 2.4min
   Processed 2320/2355 (98.5%) | Elapsed: 123.9min | Remaining: 1.9min
   Processed 2330/2355 (98.9%) | Elapsed: 124.4min | Remaining: 1.3min
   Processed 2340/2355 (99.4%) | Elapsed: 124.9min | Remaining: 0.8min
   Processed 2350/2355 (99.8%) | Elapsed: 125.4min | Remaining: 0.3min
   Processed 2355/2355 (100.0%) | Elapsed: 125.7min | Remaining: 0.0min
============================================================
Analysis complete.

================================================================================
SUMMARY: LLM-AS-JUDGE ANALYSIS
================================================================================

Total Budget Items: 2355

ValueError: Unknown format code 'f' for object of type 'str'

In [46]:
result_df.columns.to_list()

['code',
 'ergp_line_item',
 'mda_code',
 'agency',
 'mother_ministry',
 'amount',
 'alignment',
 'confidence',
 'reason',
 'mandate_deviation_score']

In [47]:
result_df.dtypes

code                       object
ergp_line_item             object
mda_code                    int64
agency                     object
mother_ministry            object
amount                     object
alignment                  object
confidence                 object
reason                     object
mandate_deviation_score     int64
dtype: object

In [48]:
# Remove commas and convert to float
result_df['amount'] = result_df['amount'].str.replace(',', '').astype('float64')

In [49]:
result_df.dtypes

code                        object
ergp_line_item              object
mda_code                     int64
agency                      object
mother_ministry             object
amount                     float64
alignment                   object
confidence                  object
reason                      object
mandate_deviation_score      int64
dtype: object

In [50]:
# 3. View results
print_summary_llm(result_df)
print_flagged_items_llm(result_df)

# 4. Export
result_df.to_csv("llm_alignment_results_1_to_50.csv", index=False)

pass

================================================================================
SUMMARY: LLM-AS-JUDGE ANALYSIS
================================================================================

Total Budget Items: 2355
Total Budget Amount: ₦780,536,740,991

Alignment Distribution:
   YES: 1261 items (53.5%) | ₦208,782,504,556
   NO: 812 items (34.5%) | ₦144,628,302,649
   PARTIAL: 282 items (12.0%) | ₦427,125,933,786

🚨 Items flagged as NOT aligned: 812
   Flagged amount: ₦144,628,302,649

====================================================================================================
TOP 20 FLAGGED ITEMS (NOT ALIGNED)
====================================================================================================

🚨 ERGP16234836: "ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT HEADQUARTER OFF...
   Agency: BUREAU OF PUBLIC ENTERPRISES (BPE)
   Amount: ₦14,000,000,000
   Confidence: HIGH
   Reason: The budget item refers to acquiring headquarters for the Bureau of Public Procurement, which is a completely different agency from the Bureau of Public Enterprises and falls outside BPE's mandate of privatisation and commercialisation.

🚨 ERGP22242227: COMPLETION AND EQUIPPING OF GENERAL HOSPITALS (MULTIPLE LOTS...
   Agency: AMINU KANO UNIVERSITY TEACHING HOSPITAL
   Amount: ₦4,200,000,000
   Confidence: HIGH
   Reason: The budget item involves completion and equipping of general hospitals in Bagwai LGA, which falls outside AKTH's mandate as a teaching hospital focused on tertiary care, medical education, and research rather than establishing or equipping general hospitals in local government areas.

🚨 ERGP1246874: PROVISION OF FARM IMPLEMENTS AND FERTILIZER TO VULNERABLE CO...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: ARCN's mandate is focused on research, training, and extension coordination rather than direct provision of farm implements and fertilizers to communities, which would be an implementation/operational activity outside their supervisory and coordinating role.

🚨 ERGP25242209: EQUIPPING OF MUHAMMAD ABDULLAHI WASE SPECIALIST HOSPITAL (MU...
   Agency: AMINU KANO UNIVERSITY TEACHING HOSPITAL
   Amount: ₦2,100,000,000
   Confidence: HIGH
   Reason: This budget item is for equipping a different hospital (Muhammad Abdullahi Wase Specialist Hospital) rather than Aminu Kano University Teaching Hospital itself, which falls outside AKTH's institutional mandate.

🚨 ERGP1246853: CONSTRUCTION OF SELECTED INNER RURAL ROADS AND SOLAR STREET ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,554,700,000
   Confidence: HIGH
   Reason: Construction of rural roads and solar street lights is infrastructure development work that falls outside ARCN's mandate which is specifically focused on agricultural research, training, extension activities, and coordination of agricultural science institutions.

🚨 ERGP1247024: CONSTRUCTION OF SCHOOL IN DIFFERENT COMMUNITIES IN OGUN STAT...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Construction of general schools to discourage out-of-school children falls under basic education mandate, not agricultural research, training, and extension activities which are ARCN's core functions.

🚨 ERGP1247025: CONSTRUCTION OF RURAL FARM ROADS IN SELECTED COMMUNITIES OF ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: ARCN's mandate focuses on agricultural research, training, extension coordination, and supervision of research institutes, but does not include infrastructure construction like farm roads, which falls outside their core functions of research coordination and policy advisory roles.

🚨 ERGP1246980: EMPOWERMENT OF YOUTH AND WOMEN IN FOOTWEAR AND LEATHER GOODS...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: This budget item focuses on footwear and leather goods manufacturing empowerment, which falls outside ARCN's mandate that is specifically limited to agricultural research, training, and extension activities.

🚨 ERGP1246907: GADING AND ASPHALTING OF SELECTED RURAL FARMING ROAD IN LAGO...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road grading and asphalting is infrastructure construction work that falls outside ARCN's mandate which focuses specifically on agricultural research, training, extension activities, and coordination of research institutes rather than physical infrastructure development.

🚨 ERGP1246905: RECONSTRUCTION OF SELECTED DILAPIDATED FARMERS ACCESS ROADS ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road reconstruction falls outside ARCN's mandate which focuses specifically on agricultural research, training, extension coordination, and supervision of research institutes rather than infrastructure development or road construction projects.

🚨 ERGP1246907: GADING AND ASPHALTING OF SELECTED RURAL FARMING ROAD IN LAGO...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road grading and asphalting is infrastructure construction work that falls outside ARCN's mandate which focuses specifically on agricultural research, training, extension activities, and coordination of research institutes rather than physical infrastructure development.

🚨 ERGP1246905: RECONSTRUCTION OF SELECTED DILAPIDATED FARMERS ACCESS ROADS ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road reconstruction is infrastructure development that falls outside ARCN's mandate which specifically focuses on agricultural research, training, extension activities, and coordination of research institutes rather than physical infrastructure projects.

🚨 ERGP1247023: CONSTRUCTION OF MARKET STALLS IN RURAL FARMING COMMUNITIES A...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Construction of market stalls is infrastructure development outside ARCN's mandate, which focuses specifically on coordinating agricultural research, training, and extension activities rather than building commercial infrastructure.

🚨 ERGP23236312: ACQUISITION AND LAND CLEARING FOR UNIVERSITY OF SCIENCE AND ...
   Agency: BENIN/ OWENA RBDA
   Amount: ₦1,190,000,000
   Confidence: HIGH
   Reason: Acquiring and clearing land for a university in Lagos State falls completely outside BORBDA's mandate, which is specifically focused on water resources development and management within the Benin-Owena River Basin covering Edo, Ondo, Ekiti states and one senatorial district in Delta State.

🚨 ERGP1247022: GRADING/ASPHALTING OF FARM SETTLEMENT ROAD WITH DRAINAGE CON...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Road construction and infrastructure development falls outside ARCN's mandate which focuses on coordinating agricultural research, training, and extension activities rather than physical infrastructure projects.

🚨 ERGP1246906: INSTALLATION OF MOTORIZED BOREHOLE WITH OVERHEAD TANK IN SEL...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Installing motorized boreholes with overhead tanks in communities is a water infrastructure development activity that falls outside ARCN's mandate, which is specifically focused on agricultural research, training, and extension activities rather than community water supply projects.

🚨 ERGP1246906: INSTALLATION OF MOTORIZED BOREHOLE WITH OVERHEAD TANK IN SEL...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Installing motorized boreholes with overhead tanks in communities is a water infrastructure project that falls outside ARCN's mandate, which specifically focuses on agricultural research, training, and extension activities rather than community water supply infrastructure.

🚨 ERGP1246909: CONSTRUCTION AND TARRING (WITH ASPHALT) OF DADINKOWA - MAGAN...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Road construction and tarring falls outside ARCN's mandate which is specifically focused on agricultural research, training, extension activities, and coordination of agricultural research institutes rather than infrastructure development.

🚨 ERGP1246909: CONSTRUCTION AND TARRING (WITH ASPHALT) OF DADINKOWA - MAGAN...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Road construction and tarring falls under infrastructure development which is outside ARCN's mandate that specifically focuses on agricultural research, training, extension activities, and coordination of agricultural institutes.

🚨 ERGP25247721: SUPPLY OF FURNITURE AND EQUIPMENT FOR SCHOOL OF BIOMEDICAL E...
   Agency: ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOSPITAL BAUCHI
   Amount: ₦1,000,000,000
   Confidence: HIGH
   Reason: The budget item is for a School of Biomedical Engineering, but ATBUTH is a teaching hospital affiliated with a College of Medical Sciences that focuses on clinical training, healthcare delivery, and medical research, not biomedical engineering education.

In [51]:
result_df.columns.to_list()

['code',
 'ergp_line_item',
 'mda_code',
 'agency',
 'mother_ministry',
 'amount',
 'alignment',
 'confidence',
 'reason',
 'mandate_deviation_score']

In [55]:
# Calculate total
total = result_df['amount'].sum()
total_formatted = f"Total: ₦{total:,.2f}"

# A: Sum amount where alignment is NO
flagged = result_df[result_df["alignment"] == "NO"]
flagged_amount = flagged['amount'].sum()
flagged_amount_naira = f"₦{flagged_amount:.2%}"
# B: Sum amount for full filtered dataframe
total_mda_project_value = f"₦{total:.2%}"
# C: A/B
flagged_percentage = flagged_amount/total
# Format the output as a percentage with 2 decimal places
format_flagged_as_percent = f"{flagged_percentage:.2%}"

In [54]:
total_mda_project_value

'₦78053674099100.00%'