In [2]:
import pandas as pd
import os
from dotenv import load_dotenv

In [3]:
# Mandate data ingestion
input_path_csv = "data/inputs/combine_mandate_581_891.csv"

mandate_df_581_891 = pd.read_csv(input_path_csv)

In [4]:
print(len(mandate_df_581_891))

296

In [3]:
mandate_df_581_891.head()

,mda_code,mda_name,mandate_description
0,521014001,# NIGERIAN FEDERAL AGENCY MANDATES: AGENCIES 5...,**MDA Code:** 521014001\n\nNational Agency for...
1,535021001,582. NATIONAL AGENCY FOR GREAT GREEN WALL (NAGGW),National Agency for Great Green Wall is federa...
2,111057001,583. NATIONAL AGENCY FOR SCIENCE AND ENGINEERI...,National Agency for Science and Engineering In...
3,161012001,584. NATIONAL AGENCY FOR THE CONTROL OF AIDS (...,National Agency for the Control of AIDS (NACA)...
4,215018001,585. NATIONAL AGRICULTURAL EXTENSION AND RESEA...,National Agricultural Extension and Research L...

In [4]:
mandate_df_581_891.dtypes

mda_code                int64
mda_name               object
mandate_description    object
dtype: object

In [15]:
ergp_budget_with_mda_path = "data/outputs/ergp_budget_with_mda_no_duplicates.csv"
budget_df = pd.read_csv(ergp_budget_with_mda_path)

In [16]:
# Drop the first column by index 
# (remove Unnamed: 0)

budget_df = budget_df.drop('Unnamed: 0', axis=1)

In [96]:
print(len(budget_df))

27538

In [18]:
budget_df.head()

,code,ergp_line_item,status,amount,mda_code,agency,mother_ministry
0,ERGP30102445,UPGRADE OF STATE HOUSE LIBRARY,ONGOING,9028123.0,111001001,STATE HOUSE - HQTRS,NaN
1,ERGP30114992,DIGITAL MEDICAL REFERENCES FOR THE STATE HOUSE...,ONGOING,3219762.0,111001001,STATE HOUSE - HQTRS,NaN
2,ERGP6101477,REHABILITATION OF ANIMAL ENCLOSURE/PROCUREMENT...,ONGOING,21850216.0,111001001,STATE HOUSE - HQTRS,NaN
3,ERGP6114996,CONVERSION/UPGRADE OF VILLA RANCH AND CONSTRUC...,ONGOING,38466135.0,111001001,STATE HOUSE - HQTRS,NaN
4,ERGP6114997,PURCHASE OF PLANT NURSERY EQUIPMENT FOR PRODUC...,ONGOING,26912671.0,111001001,STATE HOUSE - HQTRS,NaN

In [19]:
budget_df.dtypes

code                object
ergp_line_item      object
status              object
amount             float64
mda_code             int64
agency              object
mother_ministry    float64
dtype: object

In [ ]:
# Remove commas and convert to float
budget_df['amount'] = budget_df['amount'].str.replace(',', '').astype('float64')

In [20]:
budget_df.dtypes

code                object
ergp_line_item      object
status              object
amount             float64
mda_code             int64
agency              object
mother_ministry    float64
dtype: object

In [21]:


mda_list_581_891 = [
    521014001,
    535021001,
    111057001,
    161012001,
    215018001,
    215061001,
    215035001,
    111056001,
    215051001,
    265003001,
    521005001,
    222004001,
    535022001,
    228008001,
    521047001,
    517030001,
    517029001,
    161021001,
    123008001,
    238004001,
    517013001,
    252048001,
    517021024,
    521026012,
    265008001,
    123006001,
    517018017,
    517004001,
    517006001,
    125004001,
    517018019,
    517021064,
    517007001,
    254012001,
    255003001,
    215008001,
    157002002,
    157003001,
    157003002,
    233008001,
    318001001,
    517008001,
    164004001,
    164003001,
    517021025,
    164002001,
    233005001,
    521048002,
    521048003,
    521048001,
    228043001,
    535015001,
    517024001,
    123031017,
    521027063,
    521027014,
    521027015,
    535002001,
    161013001,
    161024001,
    521022001,
    231010001,
    521003001,
    227004001,
    228044001,
    215007001,
    231003001,
    521029001,
    521029014,
    521029005,
    521029008,
    521029011,
    521029009,
    521029003,
    521029006,
    521029007,
    521029010,
    521029004,
    521029013,
    521029016,
    521029002,
    155004001,
    160001001,
    161008001,
    157004001,
    111062001,
    161009001,
    123005001,
    451002001,
    252044001,
    215053001,
    230004001,
    111048001,
    521027047,
    161015001,
    156003001,
    124002001,
    231011001,
    111011001,
    513021002,
    252002001,
    124003001,
    228051001,
    513021003,
    326005001,
    228050001,
    242001001,
    157001001,
    554009001,
    517032001,
    554003001,
    228005001,
    513001001,
    233013001,
    233004001,
    521027016,
    517017001,
    256007001,
    256008001,
    517020001,
    517021057,
    265002001,
    256010001,
    252049001,
    555002001,
    554006001,
    228079001,
    116006001,
    231005001,
    222008001,
    222006001,
    256002001,
    256003001,
    111009002,
    238002001,
    254006001,
    228045001,
    265007001,
    119008001,
    521032001,
    257006001,
    215037001,
    229002001,
    222030001,
    326002001,
    230002001,
    451003001,
    451007001,
    222002001,
    111001001,
    111001007,
    111001006,
    111001002,
    111001003,
    157002003,
    517026102,
    234006001,
    222014001,
    517014001,
    119002001,
    116022001,
    231020001,
    517028001,
    517003001,
    521026001,
    517021010,
    554002001,
    535016001,
    517009001,
    521027039,
    521048004,
    256006001,
    161014001,
    521002001,
    215011001,
    521049001,
    326007001,
    116004002,
    161005001,
    254004001,
    521051001,
    521031001,
    517021028,
    517018024,
    123031011,
    215004001,
    157005001,
    228033001,
    514002001,
    215005001,
    554007001,
    517033001,
    517016001,
    256004001,
    517011001,
    554005001,
    256005001,
    111058001,
    157006001,
    157007001,
    116007001,
    227005001,
    326009001,
    521027040,
    517012001,
    116004001,
    229003001,
    230006001,
    123003001,
    255002001,
    119001002,
    156006001,
    111006001,
    521026014,
    517021022,
    521036001,
    451008001,
    554004001,
    451005001,
    521011001,
    517021005,
    521026015,
    517021006,
    521026005,
    517021008,
    521026010,
    517021001,
    517021009,
    521026007,
    517021007,
    517021002,
    517021021,
    521026011,
    521026004,
    517021003,
    517021014,
    521026009,
    517021016,
    517021020,
    521027002,
    252047001,
    252050001,
    517021042,
    228004001,
    232009001,
    222031001,
    155002001,
    123009001,
    124004001,
    215050001,
    116005001,
    116009001,
    116003001,
    517021044,
    228041001,
    220023001,
    230003001,
    326010001,
    521026006,
    220007001,
    111001004,
    111001005,
    125001001,
    215055001,
    554008001,
    253016001,
    252045001,
    222013001,
    535009001,
    521009001,
    535004001,
    220015001,
    119009122,
    232003001,
    521012001,
    521029012,
    161019001,
    228042001,
    145001001,
    125006001,
    517026101,
    521006001,
    521026023,
    228078001,
    326008001,
    234007001,
    246001001,
    215016001,
    161001001,
    238005002,
    161018001,
    228003001,
    222027001,
    252046001,
    257004001,
    451006001,
   
]

In [25]:
budget_df_mda_581_891= budget_df[budget_df['mda_code'].isin(mda_list_581_891)]

In [26]:
print(len(budget_df_mda_581_891))

10747

In [27]:
budget_df_mda_581_891.dtypes

code                object
ergp_line_item      object
status              object
amount             float64
mda_code             int64
agency              object
mother_ministry    float64
dtype: object

In [ ]:
# code	ergp_line_item	mda	amount	similarity_score	mandate_deviation_score

### LLM-AS-JUDGE:

In [14]:
# =============================================================================
# LLM-AS-JUDGE: CLAUDE API IMPLEMENTATION
# =============================================================================

import anthropic
import pandas as pd
import time
from typing import Optional


# =============================================================================
# CONFIGURATION
# =============================================================================
ANTHROPIC_API_KEY = os.getenv("CLAUDE_API_KEY")
MODEL_NAME = "claude-sonnet-4-20250514"  # Good balance of speed/cost/quality
MAX_RETRIES = 3
RETRY_DELAY = 2  # seconds

In [15]:
# =============================================================================
# CORE FUNCTIONS
# =============================================================================

def create_client(api_key: str = ANTHROPIC_API_KEY) -> anthropic.Anthropic:
    """Create Anthropic client."""
    return anthropic.Anthropic(api_key=api_key)


def judge_alignment(
    client: anthropic.Anthropic,
    line_item: str,
    agency: str,
    mandate: str
) -> dict:
    """
    Use Claude to judge if budget item aligns with agency mandate.
    
    Returns:
        dict with keys: alignment, confidence, reason
    """
    prompt = f"""You are an auditor checking if Nigerian government budget items align with agency mandates.

    AGENCY: {agency}

    AGENCY MANDATE: {mandate}

    BUDGET LINE ITEM: {line_item}

    Does this budget item fall within the agency's mandate?

    Respond in EXACTLY this format (no other text):
    ALIGNMENT: YES or PARTIAL or NO
    CONFIDENCE: HIGH or MEDIUM or LOW
    REASON: (one sentence explanation)"""

    for attempt in range(MAX_RETRIES):
        try:
            response = client.messages.create(
                model=MODEL_NAME,
                max_tokens=150,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            
            result_text = response.content[0].text
            return parse_llm_response(result_text)
            
        except Exception as e:
            if attempt < MAX_RETRIES - 1:
                print(f"   Retry {attempt + 1}/{MAX_RETRIES} after error: {e}")
                time.sleep(RETRY_DELAY)
            else:
                print(f"   Failed after {MAX_RETRIES} attempts: {e}")
                return {
                    "alignment": "ERROR",
                    "confidence": "UNKNOWN",
                    "reason": str(e)
                }


def parse_llm_response(response: str) -> dict:
    """Parse the structured LLM response."""
    result = {
        "alignment": "UNKNOWN",
        "confidence": "UNKNOWN",
        "reason": ""
    }
    
    lines = response.strip().split("\n")
    
    for line in lines:
        line = line.strip()
        if line.upper().startswith("ALIGNMENT:"):
            value = line.split(":", 1)[1].strip().upper()
            if value in ["YES", "PARTIAL", "NO"]:
                result["alignment"] = value
        elif line.upper().startswith("CONFIDENCE:"):
            value = line.split(":", 1)[1].strip().upper()
            if value in ["HIGH", "MEDIUM", "LOW"]:
                result["confidence"] = value
        elif line.upper().startswith("REASON:"):
            result["reason"] = line.split(":", 1)[1].strip()
    
    return result


def compute_deviation_score(alignment: str, confidence: str) -> float:
    """
    Convert alignment + confidence to a deviation score (0-100).
    
    Higher score = more likely outside mandate = higher audit priority.
    """
    alignment_scores = {
        "YES": 0,
        "PARTIAL": 50,
        "NO": 100,
        "UNKNOWN": 50,
        "ERROR": 50
    }
    
    confidence_adjustments = {
        "HIGH": 0,
        "MEDIUM": 5,
        "LOW": 10,
        "UNKNOWN": 10
    }
    
    base_score = alignment_scores.get(alignment, 50)
    adjustment = confidence_adjustments.get(confidence, 10)
    
    # For YES: add adjustment (less confident YES = slightly higher deviation)
    # For NO: subtract adjustment (less confident NO = slightly lower deviation)
    if alignment == "YES":
        return min(base_score + adjustment, 100)
    elif alignment == "NO":
        return max(base_score - adjustment, 0)
    else:
        return base_score


# =============================================================================
# MAIN ANALYSIS FUNCTION
# =============================================================================

def analyze_budget_mandate_alignment_llm(
    budget_df: pd.DataFrame,
    mandate_df: pd.DataFrame,
    api_key: str = ANTHROPIC_API_KEY,
    progress_interval: int = 10
) -> pd.DataFrame:
    """
    Analyze alignment between budget items and agency mandates using Claude.
    
    Args:
        budget_df: DataFrame with columns [code, ergp_line_item, mda_code, agency, mother_ministry, amount]
        mandate_df: DataFrame with columns [mda_code, mda_name, mandate_description]
        api_key: Anthropic API key
        progress_interval: Print progress every N items
        
    Returns:
        DataFrame with alignment results
    """
    # Create client
    client = create_client(api_key)
    
    # Create mandate lookup by mda_code
    mandate_lookup = dict(zip(mandate_df["mda_code"], mandate_df["mandate_description"]))
    
    results = []
    total_items = len(budget_df)
    
    print(f"Analyzing {total_items} budget items with Claude...")
    print(f"Estimated time: {total_items * 1.5 / 60:.1f} - {total_items * 2.5 / 60:.1f} minutes")
    print("=" * 60)
    
    start_time = time.time()
    
    for i, (_, row) in enumerate(budget_df.iterrows()):
        mda_code = row["mda_code"]
        line_item = row["ergp_line_item"]
        agency = row["agency"]
        mandate = mandate_lookup.get(mda_code, "")
        
        if mandate:
            judgement = judge_alignment(client, line_item, agency, mandate)
        else:
            judgement = {
                "alignment": "UNKNOWN",
                "confidence": "UNKNOWN",
                "reason": "No mandate found for this agency"
            }
        
        deviation = compute_deviation_score(
            judgement["alignment"], 
            judgement["confidence"]
        )
        
        results.append({
            "code": row["code"],
            "ergp_line_item": row["ergp_line_item"],
            "mda_code": row["mda_code"],
            "agency": row["agency"],
            "mother_ministry": row["mother_ministry"],
            "amount": row["amount"],
            "alignment": judgement["alignment"],
            "confidence": judgement["confidence"],
            "reason": judgement["reason"],
            "mandate_deviation_score": deviation
        })
        
        # Progress update
        if (i + 1) % progress_interval == 0 or (i + 1) == total_items:
            elapsed = time.time() - start_time
            rate = (i + 1) / elapsed
            remaining = (total_items - i - 1) / rate if rate > 0 else 0
            print(f"   Processed {i + 1}/{total_items} ({(i+1)/total_items*100:.1f}%) | "
                  f"Elapsed: {elapsed/60:.1f}min | Remaining: {remaining/60:.1f}min")
    
    print("=" * 60)
    print("Analysis complete.")
    
    return pd.DataFrame(results)

In [17]:
# =============================================================================
# OUTPUT & REPORTING
# =============================================================================

def print_summary_llm(result_df: pd.DataFrame) -> None:
    """Print summary statistics for LLM analysis."""
    print("\n" + "=" * 80)
    print("SUMMARY: LLM-AS-JUDGE ANALYSIS")
    print("=" * 80)
    
    total_items = len(result_df)
    total_amount = result_df["amount"].sum()
    
    # Alignment distribution
    alignment_counts = result_df["alignment"].value_counts()
    
    print(f"\nTotal Budget Items: {total_items}")
    print(f"Total Budget Amount: ₦{total_amount:,.0f}")
    
    print(f"\nAlignment Distribution:")
    for alignment, count in alignment_counts.items():
        pct = count / total_items * 100
        amount = result_df[result_df["alignment"] == alignment]["amount"].sum()
        print(f"   {alignment}: {count} items ({pct:.1f}%) | ₦{amount:,.0f}")
    
    # Flagged items (NO alignment)
    flagged = result_df[result_df["alignment"] == "NO"]
    print(f"\n🚨 Items flagged as NOT aligned: {len(flagged)}")
    print(f"   Flagged amount: ₦{flagged['amount'].sum():,.0f}")


def print_flagged_items_llm(result_df: pd.DataFrame, top_n: int = 20) -> None:
    """Print items flagged as not aligned."""
    flagged = result_df[result_df["alignment"] == "NO"].sort_values(
        "amount", ascending=False
    ).head(top_n)
    
    if len(flagged) == 0:
        print("\n✅ No items flagged as misaligned!")
        return
    
    print("\n" + "=" * 100)
    print(f"TOP {top_n} FLAGGED ITEMS (NOT ALIGNED)")
    print("=" * 100)
    
    for _, row in flagged.iterrows():
        print(f"\n🚨 {row['code']}: {row['ergp_line_item'][:60]}...")
        print(f"   Agency: {row['agency']}")
        print(f"   Amount: ₦{row['amount']:,.0f}")
        print(f"   Confidence: {row['confidence']}")
        print(f"   Reason: {row['reason']}")

In [31]:
# =============================================================================
#  USAGE 
# =============================================================================


# Example usage (replace with your actual data)

# 1. Set your API key
api_key = ANTHROPIC_API_KEY

# 2. Run analysis
result_df = analyze_budget_mandate_alignment_llm(
    budget_df=budget_df_mda_581_891,
    mandate_df=mandate_df_581_891,
    api_key=api_key,
    progress_interval=10
)

Analyzing 10747 budget items with Claude...
Estimated time: 268.7 - 447.8 minutes
============================================================
   Processed 10/10747 (0.1%) | Elapsed: 0.5min | Remaining: 588.3min
   Processed 20/10747 (0.2%) | Elapsed: 1.0min | Remaining: 553.4min
   Processed 30/10747 (0.3%) | Elapsed: 1.6min | Remaining: 557.0min
   Processed 40/10747 (0.4%) | Elapsed: 2.0min | Remaining: 547.2min
   Processed 50/10747 (0.5%) | Elapsed: 5.5min | Remaining: 1183.4min
   Processed 60/10747 (0.6%) | Elapsed: 6.0min | Remaining: 1069.1min
   Processed 70/10747 (0.7%) | Elapsed: 6.5min | Remaining: 992.6min
   Processed 80/10747 (0.7%) | Elapsed: 7.0min | Remaining: 932.9min
   Processed 90/10747 (0.8%) | Elapsed: 7.5min | Remaining: 888.7min
   Processed 100/10747 (0.9%) | Elapsed: 8.0min | Remaining: 852.2min
   Processed 110/10747 (1.0%) | Elapsed: 8.5min | Remaining: 820.3min
   Processed 120/10747 (1.1%) | Elapsed: 9.0min | Remaining: 798.4min
   Processed 130/10747 (1.2%) | Elapsed: 9.5min | Remaining: 777.0min
   Processed 140/10747 (1.3%) | Elapsed: 10.1min | Remaining: 762.8min
   Processed 150/10747 (1.4%) | Elapsed: 10.6min | Remaining: 751.3min
   Processed 160/10747 (1.5%) | Elapsed: 11.1min | Remaining: 737.2min
   Processed 170/10747 (1.6%) | Elapsed: 11.7min | Remaining: 725.7min
   Processed 180/10747 (1.7%) | Elapsed: 12.2min | Remaining: 715.3min
   Processed 190/10747 (1.8%) | Elapsed: 12.8min | Remaining: 709.8min
   Processed 200/10747 (1.9%) | Elapsed: 13.8min | Remaining: 729.0min
   Processed 210/10747 (2.0%) | Elapsed: 14.3min | Remaining: 719.0min
   Processed 220/10747 (2.0%) | Elapsed: 14.8min | Remaining: 708.2min
   Processed 230/10747 (2.1%) | Elapsed: 15.3min | Remaining: 700.2min
   Processed 240/10747 (2.2%) | Elapsed: 15.9min | Remaining: 695.0min
   Processed 250/10747 (2.3%) | Elapsed: 16.4min | Remaining: 687.4min
   Processed 260/10747 (2.4%) | Elapsed: 16.9min | Remaining: 681.9min
   Processed 270/10747 (2.5%) | Elapsed: 17.4min | Remaining: 676.7min
   Processed 280/10747 (2.6%) | Elapsed: 18.0min | Remaining: 671.1min
   Processed 290/10747 (2.7%) | Elapsed: 18.5min | Remaining: 666.3min
   Processed 300/10747 (2.8%) | Elapsed: 19.0min | Remaining: 662.8min
   Processed 310/10747 (2.9%) | Elapsed: 19.6min | Remaining: 658.9min
   Processed 320/10747 (3.0%) | Elapsed: 20.1min | Remaining: 654.5min
   Processed 330/10747 (3.1%) | Elapsed: 20.6min | Remaining: 650.7min
   Processed 340/10747 (3.2%) | Elapsed: 21.1min | Remaining: 646.9min
   Processed 350/10747 (3.3%) | Elapsed: 21.6min | Remaining: 642.9min
   Processed 360/10747 (3.3%) | Elapsed: 22.2min | Remaining: 639.4min
   Processed 370/10747 (3.4%) | Elapsed: 22.7min | Remaining: 635.9min
   Processed 380/10747 (3.5%) | Elapsed: 23.2min | Remaining: 633.8min
   Processed 390/10747 (3.6%) | Elapsed: 23.8min | Remaining: 631.1min
   Processed 400/10747 (3.7%) | Elapsed: 24.3min | Remaining: 628.1min
   Processed 410/10747 (3.8%) | Elapsed: 24.8min | Remaining: 624.5min
   Processed 420/10747 (3.9%) | Elapsed: 25.3min | Remaining: 622.4min
   Processed 430/10747 (4.0%) | Elapsed: 25.8min | Remaining: 619.6min
   Processed 440/10747 (4.1%) | Elapsed: 26.3min | Remaining: 616.0min
   Processed 450/10747 (4.2%) | Elapsed: 26.8min | Remaining: 613.9min
   Processed 460/10747 (4.3%) | Elapsed: 27.3min | Remaining: 611.2min
   Processed 470/10747 (4.4%) | Elapsed: 27.8min | Remaining: 608.3min
   Processed 480/10747 (4.5%) | Elapsed: 28.3min | Remaining: 606.1min
   Processed 490/10747 (4.6%) | Elapsed: 28.9min | Remaining: 604.3min
   Processed 500/10747 (4.7%) | Elapsed: 29.4min | Remaining: 601.9min
   Processed 510/10747 (4.7%) | Elapsed: 29.8min | Remaining: 599.1min
   Processed 520/10747 (4.8%) | Elapsed: 30.3min | Remaining: 596.5min
   Processed 530/10747 (4.9%) | Elapsed: 30.8min | Remaining: 594.3min
   Processed 540/10747 (5.0%) | Elapsed: 31.3min | Remaining: 591.8min
   Processed 550/10747 (5.1%) | Elapsed: 31.8min | Remaining: 589.3min
   Processed 560/10747 (5.2%) | Elapsed: 32.3min | Remaining: 587.6min
   Processed 570/10747 (5.3%) | Elapsed: 32.8min | Remaining: 586.4min
   Processed 580/10747 (5.4%) | Elapsed: 33.4min | Remaining: 585.4min
   Processed 590/10747 (5.5%) | Elapsed: 33.9min | Remaining: 584.4min
   Processed 600/10747 (5.6%) | Elapsed: 34.5min | Remaining: 583.0min
   Processed 610/10747 (5.7%) | Elapsed: 35.0min | Remaining: 581.9min
   Processed 620/10747 (5.8%) | Elapsed: 35.5min | Remaining: 580.6min
   Processed 630/10747 (5.9%) | Elapsed: 36.1min | Remaining: 579.1min
   Processed 640/10747 (6.0%) | Elapsed: 36.6min | Remaining: 577.7min
   Processed 650/10747 (6.0%) | Elapsed: 37.1min | Remaining: 576.5min
   Processed 660/10747 (6.1%) | Elapsed: 37.6min | Remaining: 575.3min
   Processed 670/10747 (6.2%) | Elapsed: 38.2min | Remaining: 573.8min
   Processed 680/10747 (6.3%) | Elapsed: 38.7min | Remaining: 572.4min
   Processed 690/10747 (6.4%) | Elapsed: 39.2min | Remaining: 571.2min
   Processed 700/10747 (6.5%) | Elapsed: 39.7min | Remaining: 569.7min
   Processed 710/10747 (6.6%) | Elapsed: 40.2min | Remaining: 568.6min
   Processed 720/10747 (6.7%) | Elapsed: 40.7min | Remaining: 567.4min
   Processed 730/10747 (6.8%) | Elapsed: 41.2min | Remaining: 566.0min
   Processed 740/10747 (6.9%) | Elapsed: 41.8min | Remaining: 565.3min
   Processed 750/10747 (7.0%) | Elapsed: 42.3min | Remaining: 564.4min
   Processed 760/10747 (7.1%) | Elapsed: 42.8min | Remaining: 562.9min
   Processed 770/10747 (7.2%) | Elapsed: 43.3min | Remaining: 561.6min
   Processed 780/10747 (7.3%) | Elapsed: 43.9min | Remaining: 560.4min
   Processed 790/10747 (7.4%) | Elapsed: 44.4min | Remaining: 560.1min
   Processed 800/10747 (7.4%) | Elapsed: 45.0min | Remaining: 559.2min
   Processed 810/10747 (7.5%) | Elapsed: 45.5min | Remaining: 558.6min
   Processed 820/10747 (7.6%) | Elapsed: 46.1min | Remaining: 558.1min
   Processed 830/10747 (7.7%) | Elapsed: 46.7min | Remaining: 557.5min
   Processed 840/10747 (7.8%) | Elapsed: 47.2min | Remaining: 556.5min
   Processed 850/10747 (7.9%) | Elapsed: 47.7min | Remaining: 555.6min
   Processed 860/10747 (8.0%) | Elapsed: 48.2min | Remaining: 554.6min
   Processed 870/10747 (8.1%) | Elapsed: 48.8min | Remaining: 553.7min
   Processed 880/10747 (8.2%) | Elapsed: 49.3min | Remaining: 552.8min
   Processed 890/10747 (8.3%) | Elapsed: 49.8min | Remaining: 551.5min
   Processed 900/10747 (8.4%) | Elapsed: 50.3min | Remaining: 550.9min
   Processed 910/10747 (8.5%) | Elapsed: 50.9min | Remaining: 550.6min
   Processed 920/10747 (8.6%) | Elapsed: 51.6min | Remaining: 551.1min
   Processed 930/10747 (8.7%) | Elapsed: 52.1min | Remaining: 550.2min
   Processed 940/10747 (8.7%) | Elapsed: 52.7min | Remaining: 549.7min
   Processed 950/10747 (8.8%) | Elapsed: 53.2min | Remaining: 548.7min
   Processed 960/10747 (8.9%) | Elapsed: 53.7min | Remaining: 547.5min
   Processed 970/10747 (9.0%) | Elapsed: 54.2min | Remaining: 546.6min
   Processed 980/10747 (9.1%) | Elapsed: 54.8min | Remaining: 545.8min
   Processed 990/10747 (9.2%) | Elapsed: 55.3min | Remaining: 544.6min
   Processed 1000/10747 (9.3%) | Elapsed: 55.8min | Remaining: 543.8min
   Processed 1010/10747 (9.4%) | Elapsed: 56.3min | Remaining: 542.7min
   Processed 1020/10747 (9.5%) | Elapsed: 56.9min | Remaining: 542.4min
   Processed 1030/10747 (9.6%) | Elapsed: 57.5min | Remaining: 542.0min
   Processed 1040/10747 (9.7%) | Elapsed: 58.1min | Remaining: 541.9min
   Processed 1050/10747 (9.8%) | Elapsed: 58.6min | Remaining: 541.6min
   Processed 1060/10747 (9.9%) | Elapsed: 59.2min | Remaining: 541.2min
   Processed 1070/10747 (10.0%) | Elapsed: 59.8min | Remaining: 540.8min
   Processed 1080/10747 (10.0%) | Elapsed: 60.3min | Remaining: 540.0min
   Processed 1090/10747 (10.1%) | Elapsed: 60.9min | Remaining: 539.1min
   Processed 1100/10747 (10.2%) | Elapsed: 61.4min | Remaining: 538.8min
   Processed 1110/10747 (10.3%) | Elapsed: 62.0min | Remaining: 538.3min
   Processed 1120/10747 (10.4%) | Elapsed: 62.5min | Remaining: 537.5min
   Processed 1130/10747 (10.5%) | Elapsed: 63.0min | Remaining: 536.5min
   Processed 1140/10747 (10.6%) | Elapsed: 63.6min | Remaining: 535.7min
   Processed 1150/10747 (10.7%) | Elapsed: 64.1min | Remaining: 534.5min
   Processed 1160/10747 (10.8%) | Elapsed: 64.6min | Remaining: 533.7min
   Processed 1170/10747 (10.9%) | Elapsed: 65.1min | Remaining: 533.2min
   Processed 1180/10747 (11.0%) | Elapsed: 65.7min | Remaining: 532.5min
   Processed 1190/10747 (11.1%) | Elapsed: 66.2min | Remaining: 531.5min
   Processed 1200/10747 (11.2%) | Elapsed: 66.7min | Remaining: 530.5min
   Processed 1210/10747 (11.3%) | Elapsed: 67.2min | Remaining: 529.4min
   Processed 1220/10747 (11.4%) | Elapsed: 67.7min | Remaining: 528.4min
   Processed 1230/10747 (11.4%) | Elapsed: 68.1min | Remaining: 527.2min
   Processed 1240/10747 (11.5%) | Elapsed: 68.6min | Remaining: 526.3min
   Processed 1250/10747 (11.6%) | Elapsed: 69.1min | Remaining: 525.3min
   Processed 1260/10747 (11.7%) | Elapsed: 69.7min | Remaining: 524.4min
   Processed 1270/10747 (11.8%) | Elapsed: 70.2min | Remaining: 524.0min
   Processed 1280/10747 (11.9%) | Elapsed: 70.7min | Remaining: 523.2min
   Processed 1290/10747 (12.0%) | Elapsed: 71.3min | Remaining: 523.0min
   Processed 1300/10747 (12.1%) | Elapsed: 71.9min | Remaining: 522.4min
   Processed 1310/10747 (12.2%) | Elapsed: 72.4min | Remaining: 521.8min
   Processed 1320/10747 (12.3%) | Elapsed: 73.0min | Remaining: 521.0min
   Processed 1330/10747 (12.4%) | Elapsed: 73.5min | Remaining: 520.1min
   Processed 1340/10747 (12.5%) | Elapsed: 74.0min | Remaining: 519.4min
   Processed 1350/10747 (12.6%) | Elapsed: 74.6min | Remaining: 519.1min
   Processed 1360/10747 (12.7%) | Elapsed: 75.1min | Remaining: 518.5min
   Processed 1370/10747 (12.7%) | Elapsed: 75.6min | Remaining: 517.5min
   Processed 1380/10747 (12.8%) | Elapsed: 76.1min | Remaining: 516.7min
   Processed 1390/10747 (12.9%) | Elapsed: 76.6min | Remaining: 515.7min
   Processed 1400/10747 (13.0%) | Elapsed: 77.1min | Remaining: 514.8min
   Processed 1410/10747 (13.1%) | Elapsed: 77.6min | Remaining: 514.0min
   Processed 1420/10747 (13.2%) | Elapsed: 78.2min | Remaining: 513.5min
   Processed 1430/10747 (13.3%) | Elapsed: 78.7min | Remaining: 512.7min
   Processed 1440/10747 (13.4%) | Elapsed: 79.2min | Remaining: 511.9min
   Processed 1450/10747 (13.5%) | Elapsed: 79.7min | Remaining: 511.2min
   Processed 1460/10747 (13.6%) | Elapsed: 80.3min | Remaining: 510.6min
   Processed 1470/10747 (13.7%) | Elapsed: 80.9min | Remaining: 510.3min
   Processed 1480/10747 (13.8%) | Elapsed: 81.4min | Remaining: 509.4min
   Processed 1490/10747 (13.9%) | Elapsed: 81.9min | Remaining: 508.6min
   Processed 1500/10747 (14.0%) | Elapsed: 82.4min | Remaining: 508.0min
   Processed 1510/10747 (14.1%) | Elapsed: 82.9min | Remaining: 507.3min
   Processed 1520/10747 (14.1%) | Elapsed: 83.5min | Remaining: 506.7min
   Processed 1530/10747 (14.2%) | Elapsed: 84.0min | Remaining: 506.3min
   Processed 1540/10747 (14.3%) | Elapsed: 84.6min | Remaining: 505.7min
   Processed 1550/10747 (14.4%) | Elapsed: 85.1min | Remaining: 504.8min
   Processed 1560/10747 (14.5%) | Elapsed: 85.6min | Remaining: 504.0min
   Processed 1570/10747 (14.6%) | Elapsed: 86.1min | Remaining: 503.5min
   Processed 1580/10747 (14.7%) | Elapsed: 86.7min | Remaining: 502.9min
   Processed 1590/10747 (14.8%) | Elapsed: 87.2min | Remaining: 502.5min
   Processed 1600/10747 (14.9%) | Elapsed: 87.8min | Remaining: 501.8min
   Processed 1610/10747 (15.0%) | Elapsed: 88.3min | Remaining: 501.2min
   Processed 1620/10747 (15.1%) | Elapsed: 88.9min | Remaining: 500.6min
   Processed 1630/10747 (15.2%) | Elapsed: 89.4min | Remaining: 500.1min
   Processed 1640/10747 (15.3%) | Elapsed: 90.0min | Remaining: 499.5min
   Processed 1650/10747 (15.4%) | Elapsed: 90.5min | Remaining: 499.1min
   Processed 1660/10747 (15.4%) | Elapsed: 91.1min | Remaining: 498.4min
   Processed 1670/10747 (15.5%) | Elapsed: 91.6min | Remaining: 497.9min
   Processed 1680/10747 (15.6%) | Elapsed: 92.2min | Remaining: 497.6min
   Processed 1690/10747 (15.7%) | Elapsed: 92.7min | Remaining: 496.8min
   Processed 1700/10747 (15.8%) | Elapsed: 93.2min | Remaining: 496.2min
   Processed 1710/10747 (15.9%) | Elapsed: 93.8min | Remaining: 495.6min
   Processed 1720/10747 (16.0%) | Elapsed: 94.3min | Remaining: 494.9min
   Processed 1730/10747 (16.1%) | Elapsed: 94.9min | Remaining: 494.4min
   Processed 1740/10747 (16.2%) | Elapsed: 95.4min | Remaining: 493.8min
   Processed 1750/10747 (16.3%) | Elapsed: 95.9min | Remaining: 493.1min
   Processed 1760/10747 (16.4%) | Elapsed: 96.4min | Remaining: 492.4min
   Processed 1770/10747 (16.5%) | Elapsed: 97.0min | Remaining: 491.8min
   Processed 1780/10747 (16.6%) | Elapsed: 97.5min | Remaining: 491.0min
   Processed 1790/10747 (16.7%) | Elapsed: 98.1min | Remaining: 490.7min
   Processed 1800/10747 (16.7%) | Elapsed: 98.6min | Remaining: 490.2min
   Processed 1810/10747 (16.8%) | Elapsed: 99.1min | Remaining: 489.5min
   Processed 1820/10747 (16.9%) | Elapsed: 99.7min | Remaining: 489.0min
   Processed 1830/10747 (17.0%) | Elapsed: 100.2min | Remaining: 488.4min
   Processed 1840/10747 (17.1%) | Elapsed: 100.7min | Remaining: 487.7min
   Processed 1850/10747 (17.2%) | Elapsed: 101.3min | Remaining: 487.3min
   Processed 1860/10747 (17.3%) | Elapsed: 101.9min | Remaining: 486.7min
   Processed 1870/10747 (17.4%) | Elapsed: 102.4min | Remaining: 486.0min
   Processed 1880/10747 (17.5%) | Elapsed: 102.9min | Remaining: 485.4min
   Processed 1890/10747 (17.6%) | Elapsed: 103.4min | Remaining: 484.8min
   Processed 1900/10747 (17.7%) | Elapsed: 104.0min | Remaining: 484.1min
   Processed 1910/10747 (17.8%) | Elapsed: 104.5min | Remaining: 483.6min
   Processed 1920/10747 (17.9%) | Elapsed: 105.1min | Remaining: 483.0min
   Processed 1930/10747 (18.0%) | Elapsed: 105.7min | Remaining: 482.7min
   Processed 1940/10747 (18.1%) | Elapsed: 106.2min | Remaining: 482.2min
   Processed 1950/10747 (18.1%) | Elapsed: 106.7min | Remaining: 481.5min
   Processed 1960/10747 (18.2%) | Elapsed: 107.3min | Remaining: 480.9min
   Processed 1970/10747 (18.3%) | Elapsed: 107.8min | Remaining: 480.3min
   Processed 1980/10747 (18.4%) | Elapsed: 110.5min | Remaining: 489.4min
   Processed 1990/10747 (18.5%) | Elapsed: 111.1min | Remaining: 488.8min
   Processed 2000/10747 (18.6%) | Elapsed: 111.6min | Remaining: 488.2min
   Processed 2010/10747 (18.7%) | Elapsed: 112.1min | Remaining: 487.5min
   Processed 2020/10747 (18.8%) | Elapsed: 112.7min | Remaining: 486.9min
   Processed 2030/10747 (18.9%) | Elapsed: 113.2min | Remaining: 486.2min
   Processed 2040/10747 (19.0%) | Elapsed: 113.7min | Remaining: 485.5min
   Processed 2050/10747 (19.1%) | Elapsed: 114.3min | Remaining: 484.7min
   Processed 2060/10747 (19.2%) | Elapsed: 114.8min | Remaining: 484.0min
   Processed 2070/10747 (19.3%) | Elapsed: 115.3min | Remaining: 483.4min
   Processed 2080/10747 (19.4%) | Elapsed: 115.8min | Remaining: 482.6min
   Processed 2090/10747 (19.4%) | Elapsed: 116.3min | Remaining: 481.8min
   Processed 2100/10747 (19.5%) | Elapsed: 116.8min | Remaining: 481.0min
   Processed 2110/10747 (19.6%) | Elapsed: 117.3min | Remaining: 480.1min
   Processed 2120/10747 (19.7%) | Elapsed: 117.8min | Remaining: 479.5min
   Processed 2130/10747 (19.8%) | Elapsed: 118.3min | Remaining: 478.7min
   Processed 2140/10747 (19.9%) | Elapsed: 118.8min | Remaining: 478.0min
   Processed 2150/10747 (20.0%) | Elapsed: 119.3min | Remaining: 477.2min
   Processed 2160/10747 (20.1%) | Elapsed: 119.9min | Remaining: 476.5min
   Processed 2170/10747 (20.2%) | Elapsed: 120.3min | Remaining: 475.7min
   Processed 2180/10747 (20.3%) | Elapsed: 120.8min | Remaining: 474.8min
   Processed 2190/10747 (20.4%) | Elapsed: 121.3min | Remaining: 473.9min
   Processed 2200/10747 (20.5%) | Elapsed: 121.8min | Remaining: 473.3min
   Processed 2210/10747 (20.6%) | Elapsed: 122.3min | Remaining: 472.6min
   Processed 2220/10747 (20.7%) | Elapsed: 122.9min | Remaining: 472.1min
   Processed 2230/10747 (20.7%) | Elapsed: 123.5min | Remaining: 471.5min
   Processed 2240/10747 (20.8%) | Elapsed: 124.0min | Remaining: 470.8min
   Processed 2250/10747 (20.9%) | Elapsed: 124.5min | Remaining: 470.1min
   Processed 2260/10747 (21.0%) | Elapsed: 129.4min | Remaining: 486.1min
   Processed 2270/10747 (21.1%) | Elapsed: 130.0min | Remaining: 485.3min
   Processed 2280/10747 (21.2%) | Elapsed: 130.5min | Remaining: 484.5min
   Processed 2290/10747 (21.3%) | Elapsed: 131.0min | Remaining: 483.8min
   Processed 2300/10747 (21.4%) | Elapsed: 131.5min | Remaining: 482.9min
   Processed 2310/10747 (21.5%) | Elapsed: 132.0min | Remaining: 482.0min
   Processed 2320/10747 (21.6%) | Elapsed: 132.5min | Remaining: 481.2min
   Processed 2330/10747 (21.7%) | Elapsed: 133.0min | Remaining: 480.5min
   Processed 2340/10747 (21.8%) | Elapsed: 133.5min | Remaining: 479.5min
   Processed 2350/10747 (21.9%) | Elapsed: 134.0min | Remaining: 478.7min
   Processed 2360/10747 (22.0%) | Elapsed: 134.5min | Remaining: 478.0min
   Processed 2370/10747 (22.1%) | Elapsed: 135.0min | Remaining: 477.1min
   Processed 2380/10747 (22.1%) | Elapsed: 135.5min | Remaining: 476.3min
   Processed 2390/10747 (22.2%) | Elapsed: 136.0min | Remaining: 475.5min
   Processed 2400/10747 (22.3%) | Elapsed: 136.5min | Remaining: 474.6min
   Processed 2410/10747 (22.4%) | Elapsed: 137.0min | Remaining: 473.9min
   Processed 2420/10747 (22.5%) | Elapsed: 137.5min | Remaining: 473.1min
   Processed 2430/10747 (22.6%) | Elapsed: 138.0min | Remaining: 472.3min
   Processed 2440/10747 (22.7%) | Elapsed: 138.5min | Remaining: 471.5min
   Processed 2450/10747 (22.8%) | Elapsed: 139.0min | Remaining: 470.9min
   Processed 2460/10747 (22.9%) | Elapsed: 139.6min | Remaining: 470.1min
   Processed 2470/10747 (23.0%) | Elapsed: 140.1min | Remaining: 469.3min
   Processed 2480/10747 (23.1%) | Elapsed: 140.5min | Remaining: 468.5min
   Processed 2490/10747 (23.2%) | Elapsed: 141.1min | Remaining: 467.8min
   Processed 2500/10747 (23.3%) | Elapsed: 141.6min | Remaining: 467.0min
   Processed 2510/10747 (23.4%) | Elapsed: 142.1min | Remaining: 466.3min
   Processed 2520/10747 (23.4%) | Elapsed: 142.6min | Remaining: 465.4min
   Processed 2530/10747 (23.5%) | Elapsed: 143.1min | Remaining: 464.6min
   Processed 2540/10747 (23.6%) | Elapsed: 143.6min | Remaining: 463.9min
   Processed 2550/10747 (23.7%) | Elapsed: 144.0min | Remaining: 463.0min
   Processed 2560/10747 (23.8%) | Elapsed: 144.5min | Remaining: 462.1min
   Processed 2570/10747 (23.9%) | Elapsed: 145.0min | Remaining: 461.4min
   Processed 2580/10747 (24.0%) | Elapsed: 145.5min | Remaining: 460.5min
   Processed 2590/10747 (24.1%) | Elapsed: 146.0min | Remaining: 459.7min
   Processed 2600/10747 (24.2%) | Elapsed: 146.4min | Remaining: 458.8min
   Processed 2610/10747 (24.3%) | Elapsed: 146.9min | Remaining: 458.0min
   Processed 2620/10747 (24.4%) | Elapsed: 147.4min | Remaining: 457.3min
   Processed 2630/10747 (24.5%) | Elapsed: 147.9min | Remaining: 456.5min
   Processed 2640/10747 (24.6%) | Elapsed: 148.4min | Remaining: 455.7min
   Processed 2650/10747 (24.7%) | Elapsed: 148.9min | Remaining: 454.9min
   Processed 2660/10747 (24.8%) | Elapsed: 149.4min | Remaining: 454.2min
   Processed 2670/10747 (24.8%) | Elapsed: 149.9min | Remaining: 453.5min
   Processed 2680/10747 (24.9%) | Elapsed: 150.4min | Remaining: 452.7min
   Processed 2690/10747 (25.0%) | Elapsed: 150.9min | Remaining: 451.9min
   Processed 2700/10747 (25.1%) | Elapsed: 151.4min | Remaining: 451.1min
   Processed 2710/10747 (25.2%) | Elapsed: 151.8min | Remaining: 450.3min
   Processed 2720/10747 (25.3%) | Elapsed: 152.3min | Remaining: 449.5min
   Processed 2730/10747 (25.4%) | Elapsed: 152.8min | Remaining: 448.8min

In [32]:
print(len(result_df))

10747

In [33]:
result_df.columns.to_list()

['code',
 'ergp_line_item',
 'mda_code',
 'agency',
 'mother_ministry',
 'amount',
 'alignment',
 'confidence',
 'reason',
 'mandate_deviation_score']

In [34]:
result_df.dtypes

code                        object
ergp_line_item              object
mda_code                     int64
agency                      object
mother_ministry            float64
amount                     float64
alignment                   object
confidence                  object
reason                      object
mandate_deviation_score      int64
dtype: object

In [35]:
# 3. View results
print_summary_llm(result_df)
print_flagged_items_llm(result_df)

# 4. Export
result_df.to_csv("llm_alignment_results_581_891.csv", index=False)

pass

================================================================================
SUMMARY: LLM-AS-JUDGE ANALYSIS
================================================================================

Total Budget Items: 10747
Total Budget Amount: ₦13,048,770,777,241

Alignment Distribution:
   YES: 5027 items (46.8%) | ₦7,806,341,776,821
   NO: 3904 items (36.3%) | ₦2,447,618,379,686
   PARTIAL: 1814 items (16.9%) | ₦2,794,775,620,734
   ERROR: 2 items (0.0%) | ₦35,000,000

🚨 Items flagged as NOT aligned: 3904
   Flagged amount: ₦2,447,618,379,686

====================================================================================================
TOP 20 FLAGGED ITEMS (NOT ALIGNED)
====================================================================================================

🚨 ERGP16210669: MILITARY PENSIONS - MILITARY PENSION...
   Agency: SERVICE WIDE VOTE
   Amount: ₦239,522,931,359
   Confidence: HIGH
   Reason: Military pensions are specific statutory obligations that should be funded through dedicated pension agencies or the military's own budget allocation, not through the Service Wide Vote which is meant for government-wide services, contingencies, and cross-cutting needs.

🚨 ERGP25234023: NIGERIA INTELLIGENCE AGENCY (NIA) HOSPITAL
...
   Agency: SERVICE WIDE VOTE
   Amount: ₦208,049,108,010
   Confidence: HIGH
   Reason: A specific hospital for the Nigeria Intelligence Agency (NIA) is a specialized sectoral facility that should be funded through NIA's own budget allocation rather than through the centralized Service Wide Vote meant for government-wide services and contingencies.

🚨 ERGP16210701: PARASTATALS' PENSION AND RAILWAY PENSIONS - PENSIONS...
   Agency: SERVICE WIDE VOTE
   Amount: ₦194,686,375,535
   Confidence: HIGH
   Reason: Parastatals' pension and railway pensions are specific ongoing pension obligations that should be funded through dedicated pension schemes or the respective agencies, not through Service Wide Vote which is meant for contingencies, emergencies, and cross-cutting government services.

🚨 ERGP16210670: MILITARY PENSIONS - EXPECTED RETIREES...
   Agency: SERVICE WIDE VOTE
   Amount: ₦130,381,048,588
   Confidence: HIGH
   Reason: Military pensions for expected retirees are specific statutory obligations that should be funded through the Ministry of Defence or dedicated pension agencies, not through the Service Wide Vote which is meant for contingencies, emergencies, and cross-cutting government services.

🚨 ERGP14247831: NAF OUTSTANDING OBLIGATIONS ON 6X T-129 ATAK HELICOPTER AND ...
   Agency: SERVICE WIDE VOTE
   Amount: ₦110,305,719,176
   Confidence: HIGH
   Reason: This budget item is for specific military helicopter procurement which should be funded through the Nigerian Air Force's own budget allocation, not through the Service Wide Vote which is meant for cross-cutting government services and contingencies.

🚨 ERGP16210667: MILITARY PENSIONS - DEATH BENEFITS...
   Agency: SERVICE WIDE VOTE
   Amount: ₦101,516,907,952
   Confidence: HIGH
   Reason: Military pensions and death benefits are specific statutory obligations that should be funded through the Ministry of Defence or dedicated pension agency budgets, not through the Service Wide Vote which is meant for cross-cutting services and contingencies.

🚨 ERGP1247840: NIGERIA DEVELOPMENT FINANCE CORPORATION...
   Agency: SERVICE WIDE VOTE
   Amount: ₦100,000,000,000
   Confidence: HIGH
   Reason: Nigeria Development Finance Corporation is a specific financial institution that should have its own dedicated budget allocation rather than being funded through Service Wide Vote, which is meant for government-wide services, contingencies, and cross-cutting needs.

🚨 ERGP1212130: CONSUMER CREDIT FUND...
   Agency: SERVICE WIDE VOTE
   Amount: ₦80,000,000,000
   Confidence: HIGH
   Reason: Consumer Credit Fund is a specific financial sector intervention that does not align with Service Wide Vote's mandate of providing centralized funding for government-wide services, emergencies, and cross-cutting administrative needs.

🚨 ERGP1212140: MORTGAGE DEVELOPMENT/PROMOTION FUND...
   Agency: SERVICE WIDE VOTE
   Amount: ₦65,000,000,000
   Confidence: HIGH
   Reason: Mortgage development and promotion is a specific sectoral function that should fall under housing or finance sector agencies, not the Service Wide Vote which is meant for cross-cutting government services, emergencies, and contingencies.

🚨 ERGP16210690: PAYMENT INTO REDEMPTION FUND...
   Agency: SERVICE WIDE VOTE
   Amount: ₦62,249,182,917
   Confidence: HIGH
   Reason: Payment into redemption fund is a debt service obligation that does not align with Service Wide Vote's mandate to provide centralized funding for government-wide services, emergencies, and cross-cutting operational needs.

🚨 ERGP16210668: CIVILIAN PENSIONS - PENSIONS...
   Agency: SERVICE WIDE VOTE
   Amount: ₦60,335,434,421
   Confidence: HIGH
   Reason: Civilian pensions are ongoing statutory obligations that should be managed by dedicated pension agencies, not through the Service Wide Vote which is designed for contingencies, emergencies, and cross-cutting government services.

🚨 ERGP23234159: MULTILATERAL/BILATERAL TIED LOAN - SUSTAINABLE PROCUREMENT, ...
   Agency: NATIONAL UNIVERSITIES COMMISSION SECRETARIAT
   Amount: ₦30,644,312,730
   Confidence: HIGH
   Reason: The SPESSE project focuses on procurement and environmental standards enhancement, which falls outside NUC's core mandate of regulating university education, accrediting academic programs, and overseeing university quality standards.

🚨 ERGP16210671: DEPARTMENT OF STATE SECURITY - PENSIONS (INCLUDING ARREARS)...
   Agency: SERVICE WIDE VOTE
   Amount: ₦28,611,520,421
   Confidence: HIGH
   Reason: Department of State Security pensions are specific operational obligations that should be funded directly through the DSS budget rather than through Service Wide Vote's mandate for cross-cutting government services and contingencies.

🚨 ERGP16210673: POLICE PENSIONS - PENSIONS...
   Agency: SERVICE WIDE VOTE
   Amount: ₦18,319,909,320
   Confidence: HIGH
   Reason: Police pensions are specific statutory obligations that should be funded through the Nigeria Police Force budget or dedicated pension agencies, not through the Service Wide Vote which is for centralized government-wide services and contingencies.

🚨 ERGP16210697: CUSTOMS, IMMIGRATION AND PRISONS PENSION OFFICE - PENSIONS...
   Agency: SERVICE WIDE VOTE
   Amount: ₦18,107,191,867
   Confidence: HIGH
   Reason: Pensions for specific agencies (Customs, Immigration and Prisons) are operational personnel costs that should be funded through their respective agency budgets, not through Service Wide Vote which is designated for government-wide services, contingencies, and cross-cutting initiatives.

🚨 ERGP16210691: NIGERIA INTELLIGENCE AGENCY - PENSIONS/DEPENDANTS BENEFITS...
   Agency: SERVICE WIDE VOTE
   Amount: ₦15,450,070,461
   Confidence: HIGH
   Reason: Pensions and dependants benefits for a specific intelligence agency should be funded directly through that agency's personnel budget rather than through the Service Wide Vote's mandate for government-wide services and contingencies.

🚨 ERGP16234123: BENEFITS OF RETIRED PROFESSORS
...
   Agency: SERVICE WIDE VOTE
   Amount: ₦14,283,196,861
   Confidence: HIGH
   Reason: Benefits for retired professors are specific personnel costs that should be funded by the Ministry of Education or relevant educational institutions, not through Service Wide Vote which is designated for government-wide services, emergencies, and cross-cutting needs.

🚨 ERGP12240135: CONSTRUCTION OF SURFACE AND RURAL FEEDER ROADS IN SELECTED C...
   Agency: NIGERIAN BUILDING AND ROAD RESEARCH INSTITUTE - LAGOS
   Amount: ₦14,000,000,000
   Confidence: HIGH
   Reason: The Nigerian Building and Road Research Institute is a research institution focused on studying construction materials and road technologies, not implementing actual road construction projects which falls outside their research mandate.

🚨 ERGP31194588: CONSTRUCTION AND EQUIPPING OF AIB ABUJA HEADQUARTERS
...
   Agency: NIGERIAN SAFETY INVESTIGATION BUREAU (NSIB)
   Amount: ₦13,757,969,600
   Confidence: HIGH
   Reason: The budget item refers to "AIB" (Accident Investigation Bureau) headquarters when the agency is NSIB (Nigerian Safety Investigation Bureau), indicating this budget line belongs to a different organization.

🚨 ERGP16210696: UNIVERSITIES' PENSIONS INCLUDING ARREARS - PENSIONS...
   Agency: SERVICE WIDE VOTE
   Amount: ₦13,120,357,752
   Confidence: HIGH
   Reason: Universities' pensions are specific personnel obligations that should be funded through the education sector or pension administration agencies, not through the Service Wide Vote which is designed for government-wide services, contingencies, and cross-cutting initiatives.

In [70]:
result_df.columns.to_list()

['code',
 'ergp_line_item',
 'mda_code',
 'agency',
 'mother_ministry',
 'amount',
 'alignment',
 'confidence',
 'reason',
 'mandate_deviation_score']

In [71]:
print(len(result_df))

5686

In [72]:
result_df.dtypes

code                        object
ergp_line_item              object
mda_code                     int64
agency                      object
mother_ministry            float64
amount                     float64
alignment                   object
confidence                  object
reason                      object
mandate_deviation_score      int64
dtype: object

In [36]:
# stack 1 - 380, 381 - 580 and 581 - 891.

mandate_deviation_output_path_1_380 = "data/outputs/mandate_deviation/combined_llm_alignment_results_1_to_380.csv"
result_df_1_380= pd.read_csv(mandate_deviation_output_path_1_380)

mandate_deviation_output_path_381_580 = "data/outputs/mandate_deviation/llm_alignment_results_381_580.csv"
result_df_381_580= pd.read_csv(mandate_deviation_output_path_381_580)

mandate_deviation_output_path_581_891 = "data/outputs/mandate_deviation/llm_alignment_results_581_891.csv"
result_df_581_891= pd.read_csv(mandate_deviation_output_path_581_891)

# Merge vertically (stack rows)
merged_mandate_deviation_for_mdas_1_580_df = pd.concat([result_df_1_380, result_df_381_580], ignore_index=True)
merged_mandate_deviation_for_mdas_1_891_df = pd.concat([merged_mandate_deviation_for_mdas_1_580_df, result_df_581_891], ignore_index=True)

In [37]:
merged_mandate_deviation_for_mdas_1_891_df.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
0,ERGP1102191,IT INFRASTRUCTURE AND ASSOCIATED EQUIPMENT\n,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,9.817500e+07,YES,HIGH,IT infrastructure and associated equipment dir...,0
1,ERGP1102209,PURCHASE OF OFFICE FURNITURE AND FITTINGS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.490738e+07,YES,HIGH,Office furniture and fittings are necessary ad...,0
2,ERGP1205869,PURCHASE OF LAP TOP AND DESKTOP COMPUTERS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.107260e+08,YES,HIGH,Purchasing computers for staff official use is...,0
3,ERGP1205905,REMODELING OF SECURITY HOUSE AND BPE MAIN ENTR...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+07,PARTIAL,MEDIUM,While the remodeling of BPE's main entrance do...,50
4,ERGP16234836,"""ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT H...",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+10,NO,HIGH,The budget item refers to acquiring headquarte...,100

In [38]:
print(len(merged_mandate_deviation_for_mdas_1_891_df))

20391

In [46]:

cols_mandate_deviation = [
    'code', 'ergp_line_item',
    # 'mda_code', 'agency', 'mother_ministry', 'amount',
    # 'alignment', 'confidence', 'reason','mandate_deviation_score'
]

mdas_1_891_no_duplicates = merged_mandate_deviation_for_mdas_1_891_df.drop_duplicates(subset=cols_mandate_deviation)
# mdas_1_891_no_duplicates.reset_index(drop=True, inplace=True)

In [47]:
mdas_1_891_no_duplicates.columns.to_list()

['code',
 'ergp_line_item',
 'mda_code',
 'agency',
 'mother_ministry',
 'amount',
 'alignment',
 'confidence',
 'reason',
 'mandate_deviation_score']

In [48]:
print(len(mdas_1_891_no_duplicates))

20391

In [49]:
# export combined csv
mdas_1_891_no_duplicates.to_csv("combined_llm_alignment_results_1_891.csv", index=False)

In [78]:
# Group by mda_code
budget_padding_summary_df = mdas_1_891_no_duplicates.groupby('mda_code').apply(
    lambda x: pd.Series({
        'flagged_amount': x[x['alignment'] == 'NO']['amount'].sum(),  # (1) sum where alignment is 'NO'
        'total_amount': x['amount'].sum(),  # (2) sum all amounts for the agency
        'agency': x['agency'].iloc[0]  # keep agency name
    })
).reset_index(drop=True)

# (3) Calculate ratio
budget_padding_summary_df['flagged_ratio'] = budget_padding_summary_df['flagged_amount'] / budget_padding_summary_df['total_amount']

/var/folders/jj/66ym3p5j62s0g7zqbfvfg40c0000gn/T/ipykernel_6372/1932823915.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  budget_padding_summary_df = mdas_1_891_no_duplicates.groupby('mda_code').apply(

In [79]:
budget_padding_summary_df.head()

,flagged_amount,total_amount,agency,flagged_ratio
0,26912511.0,3.052168e+10,STATE HOUSE - HQTRS,0.000882
1,134257312.0,7.713732e+08,STATE HOUSE OPERATIONS - PRESIDENT,0.174050
2,79833217.0,6.413852e+08,STATE HOUSE OPERATIONS - VICE PRESIDENT,0.124470
3,0.0,3.456059e+08,OFFICE OF THE CHIEF OF STAFF TO THE PRESIDENT,0.000000
4,0.0,3.458174e+08,STATE HOUSE MEDICAL CENTRE,0.000000

In [80]:
budget_padding_summary_df['flagged_amount'] = budget_padding_summary_df['flagged_amount'].astype('int64')
# budget_padding_summary_df['flagged_amount'] = budget_padding_summary_df['flagged_amount'].apply(lambda x: f"{x:,.2f}")


budget_padding_summary_df['total_amount'] = budget_padding_summary_df['total_amount'].astype('int64')
# budget_padding_summary_df['total_amount'] = budget_padding_summary_df['total_amount'].apply(lambda x: f"{x:,.2f}")


budget_padding_summary_df['flagged_percent'] = budget_padding_summary_df['flagged_ratio'].apply(lambda x: f"{x:.2%}")

In [83]:



budget_padding_summary_df = budget_padding_summary_df.sort_values('flagged_ratio', ascending=False)

In [85]:
budget_padding_summary_df.head(100)

,flagged_amount,total_amount,agency,flagged_ratio,flagged_percent
7,14000000000,14392470828,BUREAU OF PUBLIC ENTERPRISES (BPE),0.972731,97.27%
149,9640963623,9972994978,INDUSTRIAL ARBITRATION PANEL,0.966707,96.67%
294,31344312730,32665455192,NATIONAL UNIVERSITIES COMMISSION SECRETARIAT,0.959555,95.96%
219,53364452386,56064114604,NIGERIAN INSTITUTE FOR OCEANOGRAPHY AND MARINE...,0.951847,95.18%
241,31066490000,33373845874,FEDERAL COLLEGE OF VETERINARY AND MEDICAL LABO...,0.930863,93.09%
...,...,...,...,...,...
157,3630200000,10150117687,BOARD FOR TECHNOLOGY BUSINESS INCUBATOR CENTRE...,0.357651,35.77%
545,440086111,1241163447,CITIZENSHIP & LEADERSHIP TRAINING CENTRE,0.354575,35.46%
257,6600552566,19112986739,NATIONAL CENTRE FOR WOMEN DEVELOPMENT,0.345344,34.53%
185,270007678,814064101,NATIONAL STEEL RAW MATERIALS EXPLORATION AGENC...,0.331679,33.17%
528,210000000,635664834,FEDERAL COLLEGE OF WILDLIFE MANAGEMENT - NEW B...,0.330363,33.04%

In [73]:
# 3. View results
print_summary_llm(result_df)
print_flagged_items_llm(result_df)

# 4. Export
result_df.to_csv("llm_alignment_results_51_to_200.csv", index=False)

pass

================================================================================
SUMMARY: LLM-AS-JUDGE ANALYSIS
================================================================================

Total Budget Items: 5686
Total Budget Amount: ₦2,210,874,466,149

Alignment Distribution:
   NO: 2626 items (46.2%) | ₦628,172,564,174
   YES: 2451 items (43.1%) | ₦1,331,965,056,587
   PARTIAL: 609 items (10.7%) | ₦250,736,845,388

🚨 Items flagged as NOT aligned: 2626
   Flagged amount: ₦628,172,564,174

====================================================================================================
TOP 20 FLAGGED ITEMS (NOT ALIGNED)
====================================================================================================

🚨 ERGP12234386: ROADS REHABILITATION IN SELECTED LOCATIONS IN NORTH WEST, NI...
   Agency: FEDERAL ROAD MAINTENANCE AGENCY
   Amount: ₦7,000,000,000
   Confidence: HIGH
   Reason: FERMA's mandate is limited to routine and periodic maintenance of existing federal roads, while road rehabilitation involves major reconstruction work that falls under the Federal Ministry of Works' capital projects mandate.

🚨 ERGP1246025: CONSTRUCTION OF POLICE TRAINING INSTITUTE (SHORT SERVICE) , ...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- IBADAN
   Amount: ₦7,000,000,000
   Confidence: HIGH
   Reason: The construction of a police training institute is completely outside the mandate of a cooperative college focused on training middle-level manpower for the cooperative subsector and related business disciplines.

🚨 ERGP27246215: CONSTRUCTION OF SCHOOL OF VETERINARY AND MEDICAL LABORATORY ...
   Agency: FEDERAL COLLEGE OF VETERINARY AND MEDICAL LABORATORY TECHNOLOGY, VOM, PLATEAU STATE
   Amount: ₦7,000,000,000
   Confidence: HIGH
   Reason: The budget item is for construction in Kaduna State while the agency is specifically located in and operates from Plateau State, with no mandate indicating operations or facilities in Kaduna State.

🚨 ERGP27246215: CONSTRUCTION OF SCHOOL OF VETERINARY AND MEDICAL LABORATORY ...
   Agency: FEDERAL COLLEGE OF VETERINARY AND MEDICAL LABORATORY TECHNOLOGY, VOM, PLATEAU STATE
   Amount: ₦7,000,000,000
   Confidence: HIGH
   Reason: The budget item is for construction in Kaduna State while the agency is specifically located in and operates from Vom, Plateau State, with no mandate indicating multi-state operations or expansion authority.

🚨 ERGP30236268: PROVISION OF ACCESS ROADS AND EROSION CONTROL IN OKPORO, OHO...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER
   Amount: ₦6,500,000,000
   Confidence: HIGH
   Reason: The budget item involves infrastructure construction and erosion control across multiple states, which falls outside the college's mandate of providing cooperative education, training, and academic programs.

🚨 ERGP30234978: CONSTRUCTION OF LECTURE THEATERS, FACULTY BUILDINGS, HOSTELS...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER
   Amount: ₦6,500,000,000
   Confidence: HIGH
   Reason: The budget item specifies construction "in selected locations in Nigeria (multiple lots)" which extends beyond the Federal Co-operative College Oji River's specific institutional mandate and geographic scope as a single college facility.

🚨 ERGP30236268: PROVISION OF ACCESS ROADS AND EROSION CONTROL IN OKPORO, OHO...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER
   Amount: ₦6,500,000,000
   Confidence: HIGH
   Reason: The budget item involves infrastructure construction and erosion control across multiple states, which falls outside the educational mandate of a cooperative college that focuses on training and academic programs in cooperative studies and related fields.

🚨 ERGP12234394: REHABILITATION OF BUNI GARI-GULANI ROAD IN YOBE STATE.
...
   Agency: FEDERAL ROAD MAINTENANCE AGENCY
   Amount: ₦4,900,000,000
   Confidence: HIGH
   Reason: FERMA's mandate is limited to maintenance activities (routine, periodic, and emergency repairs) while rehabilitation involves major reconstruction work that falls under the Federal Ministry of Works' responsibility for road development and major rehabilitation projects.

🚨 ERGP1246072: CONSTRUCTION AND INSTALLATION OF ASTRAL ENERGY SYSTEMS FOR I...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- IBADAN
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The construction and installation of astral energy systems for illumination across the nation is a large-scale national infrastructure project that falls completely outside the mandate of an educational institution focused on cooperative training and related academic programs.

🚨 ERGP1246071: CONSTRUCTION AND DEVELOPMENT OF MODERN GENERAL HOSPITALS IN ...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- IBADAN
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The Federal Co-operative College Ibadan is an educational institution focused on training cooperative and business professionals, not a healthcare agency, and constructing hospitals falls entirely outside its educational mandate.

🚨 ERGP12234499: CONSTRUCTION OF GORGORAM - GURI ROAD IN YOBE STATE...
   Agency: FEDERAL ROAD MAINTENANCE AGENCY
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: FERMA's mandate is limited to maintenance of existing federal roads, while construction of new roads like the Gorgoram-Guri road falls under the Federal Ministry of Works' construction responsibilities.

🚨 ERGP1246657: CONSTRUCTION OF EDUCATIONAL BUILDINGS IN SELECTED PUBLIC SCH...
   Agency: FEDERAL COLLEGE OF LAND RESOURCES TECHNOLOGY - OWERRI
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The budget item involves constructing educational buildings in general public schools across the South West region, which falls outside FECOLART's specific mandate to train middle-level manpower in land resources technology, soil conservation, and environmental management through their own diploma programmes.

🚨 ERGP30236267: SUPPLY OF GRAINS, FERTILIZERS, CEREAL, HERBICIDES AND INSECT...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The Federal Co-operative College Oji River is an educational institution focused on training and curriculum delivery in cooperative studies and related disciplines, not direct agricultural input distribution to farmers.

🚨 ERGP1246472: SUPPLY OF GRAINS TO SELECTED VICTIMS OF INSURGENCIES, BANDIT...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- KADUNA
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Supplying grains to victims of insurgencies, banditry, and domestic violence is a humanitarian relief activity that falls completely outside the Federal Co-operative College's educational mandate of providing cooperative training, education, and skills development programs.

🚨 ERGP25243407: "ESTABLISHMENT OF NATIONAL TARUMA CENTRE "...
   Agency: FEDERAL MEDICAL CENTRE, AZARE BAUCHI
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The establishment of a National Taruma Centre falls outside the Federal Medical Centre Azare's mandate, which is focused on providing tertiary healthcare services, medical training, and research within the Bauchi State region rather than establishing national-level specialized centers.

🚨 ERGP1245688: SUPPLY OF PROCESSED AND SEMI-PROCESSED FOOD ITEMS TO VULNERA...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- IBADAN
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The agency's mandate focuses on training middle-level manpower for the cooperative sector and related academic programs, not on food supply or distribution to vulnerable communities.

🚨 ERGP1245615: CONSTRUCTION OF RURAL ROADS & RURAL MARKETS IN SELECTED LOCA...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- IBADAN
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Construction of rural roads and markets is infrastructure development work that falls outside the educational mandate of a cooperative college focused on training students and supporting cooperative societies through academic programs and capacity building.

🚨 ERGP30236267: SUPPLY OF GRAINS, FERTILIZERS, CEREAL, HERBICIDES AND INSECT...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The budget item involves direct supply of agricultural inputs to farmers, which falls outside the college's mandate as an educational institution focused on cooperative studies, business, and technical education rather than agricultural supply operations.

🚨 ERGP1245961: PROVISION OF TRICYCLES AND MOTOR CYCLES FOR POVERTY ALLEVIAT...
   Agency: FEDERAL CO-OPERATIVE COLLEGE- IBADAN
   Amount: ₦2,870,000,000
   Confidence: HIGH
   Reason: The Federal Co-operative College Ibadan's mandate is focused on education and training for the cooperative sector, not direct poverty alleviation through distribution of vehicles across geo-political zones.

🚨 ERGP12246349: CONSTRUCTION & REHABILITATION OF SOME SELECTED RURAL FARM RO...
   Agency: FEDERAL COLLEGE OF VETERINARY AND MEDICAL LABORATORY TECHNOLOGY, VOM, PLATEAU STATE
   Amount: ₦2,835,000,000
   Confidence: HIGH
   Reason: The construction and rehabilitation of rural farm roads is not within the mandate of this veterinary and medical laboratory technology college, which is specifically focused on training technicians and technologists in animal health, production, and veterinary laboratory services.

In [51]:
result_df.columns.to_list()

['code',
 'ergp_line_item',
 'mda_code',
 'agency',
 'mother_ministry',
 'amount',
 'alignment',
 'confidence',
 'reason',
 'mandate_deviation_score']

In [78]:
# Calculate total
total = result_df['amount'].sum()
total_formatted = f"Total: ₦{total:,.2f}"

# A: Sum amount where alignment is NO
flagged = result_df[result_df["alignment"] == "NO"]
flagged_amount = flagged['amount'].sum()
flagged_amount_naira = f"₦{flagged_amount:.2f}"
# B: Sum amount for full filtered dataframe
total_mda_project_value = f"₦{total:.2f}"
# C: A/B
flagged_percentage = flagged_amount/total
# Format the output as a percentage with 2 decimal places
format_flagged_as_percent = f"{flagged_percentage:.2%}"

In [79]:
total_mda_project_value

'₦2210874466149.00'

In [80]:
format_flagged_as_percent

'28.41%'

In [81]:
flagged_amount_naira

'₦628172564174.00'

In [86]:
mandate_deviation_output_path_1_50 = "data/outputs/mandate_deviation/llm_alignment_results_1_to_50.csv"
result_df_1_50 = pd.read_csv(mandate_deviation_output_path_1_50)

In [87]:
print(len(result_df_1_50))

2355

In [84]:
# Calculate total
total = result_df['amount'].sum()
total_formatted = f"Total: ₦{total:,.2f}"

# A: Sum amount where alignment is NO
flagged = result_df[result_df["alignment"] == "NO"]
flagged_amount = flagged['amount'].sum()
flagged_amount_naira = f"₦{flagged_amount:.2f}"
# B: Sum amount for full filtered dataframe
total_mda_project_value = f"₦{total:.2f}"
# C: A/B
flagged_percentage = flagged_amount/total
# Format the output as a percentage with 2 decimal places
format_flagged_as_percent = f"{flagged_percentage:.2%}"

In [ ]:
flagged_amount_naira

'₦144628302649.00'

In [88]:
# 3. View results
print_summary_llm(result_df_1_50)
print_flagged_items_llm(result_df_1_50)


pass

================================================================================
SUMMARY: LLM-AS-JUDGE ANALYSIS
================================================================================

Total Budget Items: 2355
Total Budget Amount: ₦780,536,740,991

Alignment Distribution:
   YES: 1261 items (53.5%) | ₦208,782,504,556
   NO: 812 items (34.5%) | ₦144,628,302,649
   PARTIAL: 282 items (12.0%) | ₦427,125,933,786

🚨 Items flagged as NOT aligned: 812
   Flagged amount: ₦144,628,302,649

====================================================================================================
TOP 20 FLAGGED ITEMS (NOT ALIGNED)
====================================================================================================

🚨 ERGP16234836: "ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT HEADQUARTER OFF...
   Agency: BUREAU OF PUBLIC ENTERPRISES (BPE)
   Amount: ₦14,000,000,000
   Confidence: HIGH
   Reason: The budget item refers to acquiring headquarters for the Bureau of Public Procurement, which is a completely different agency from the Bureau of Public Enterprises and falls outside BPE's mandate of privatisation and commercialisation.

🚨 ERGP22242227: COMPLETION AND EQUIPPING OF GENERAL HOSPITALS (MULTIPLE LOTS...
   Agency: AMINU KANO UNIVERSITY TEACHING HOSPITAL
   Amount: ₦4,200,000,000
   Confidence: HIGH
   Reason: The budget item involves completion and equipping of general hospitals in Bagwai LGA, which falls outside AKTH's mandate as a teaching hospital focused on tertiary care, medical education, and research rather than establishing or equipping general hospitals in local government areas.

🚨 ERGP1246874: PROVISION OF FARM IMPLEMENTS AND FERTILIZER TO VULNERABLE CO...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: ARCN's mandate is focused on research, training, and extension coordination rather than direct provision of farm implements and fertilizers to communities, which would be an implementation/operational activity outside their supervisory and coordinating role.

🚨 ERGP25242209: EQUIPPING OF MUHAMMAD ABDULLAHI WASE SPECIALIST HOSPITAL (MU...
   Agency: AMINU KANO UNIVERSITY TEACHING HOSPITAL
   Amount: ₦2,100,000,000
   Confidence: HIGH
   Reason: This budget item is for equipping a different hospital (Muhammad Abdullahi Wase Specialist Hospital) rather than Aminu Kano University Teaching Hospital itself, which falls outside AKTH's institutional mandate.

🚨 ERGP1246853: CONSTRUCTION OF SELECTED INNER RURAL ROADS AND SOLAR STREET ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,554,700,000
   Confidence: HIGH
   Reason: Construction of rural roads and solar street lights is infrastructure development work that falls outside ARCN's mandate which is specifically focused on agricultural research, training, extension activities, and coordination of agricultural science institutions.

🚨 ERGP1247024: CONSTRUCTION OF SCHOOL IN DIFFERENT COMMUNITIES IN OGUN STAT...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Construction of general schools to discourage out-of-school children falls under basic education mandate, not agricultural research, training, and extension activities which are ARCN's core functions.

🚨 ERGP1247025: CONSTRUCTION OF RURAL FARM ROADS IN SELECTED COMMUNITIES OF ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: ARCN's mandate focuses on agricultural research, training, extension coordination, and supervision of research institutes, but does not include infrastructure construction like farm roads, which falls outside their core functions of research coordination and policy advisory roles.

🚨 ERGP1246980: EMPOWERMENT OF YOUTH AND WOMEN IN FOOTWEAR AND LEATHER GOODS...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: This budget item focuses on footwear and leather goods manufacturing empowerment, which falls outside ARCN's mandate that is specifically limited to agricultural research, training, and extension activities.

🚨 ERGP1246907: GADING AND ASPHALTING OF SELECTED RURAL FARMING ROAD IN LAGO...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road grading and asphalting is infrastructure construction work that falls outside ARCN's mandate which focuses specifically on agricultural research, training, extension activities, and coordination of research institutes rather than physical infrastructure development.

🚨 ERGP1246905: RECONSTRUCTION OF SELECTED DILAPIDATED FARMERS ACCESS ROADS ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road reconstruction falls outside ARCN's mandate which focuses specifically on agricultural research, training, extension coordination, and supervision of research institutes rather than infrastructure development or road construction projects.

🚨 ERGP1246907: GADING AND ASPHALTING OF SELECTED RURAL FARMING ROAD IN LAGO...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road grading and asphalting is infrastructure construction work that falls outside ARCN's mandate which focuses specifically on agricultural research, training, extension activities, and coordination of research institutes rather than physical infrastructure development.

🚨 ERGP1246905: RECONSTRUCTION OF SELECTED DILAPIDATED FARMERS ACCESS ROADS ...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Road reconstruction is infrastructure development that falls outside ARCN's mandate which specifically focuses on agricultural research, training, extension activities, and coordination of research institutes rather than physical infrastructure projects.

🚨 ERGP1247023: CONSTRUCTION OF MARKET STALLS IN RURAL FARMING COMMUNITIES A...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,400,000,000
   Confidence: HIGH
   Reason: Construction of market stalls is infrastructure development outside ARCN's mandate, which focuses specifically on coordinating agricultural research, training, and extension activities rather than building commercial infrastructure.

🚨 ERGP23236312: ACQUISITION AND LAND CLEARING FOR UNIVERSITY OF SCIENCE AND ...
   Agency: BENIN/ OWENA RBDA
   Amount: ₦1,190,000,000
   Confidence: HIGH
   Reason: Acquiring and clearing land for a university in Lagos State falls completely outside BORBDA's mandate, which is specifically focused on water resources development and management within the Benin-Owena River Basin covering Edo, Ondo, Ekiti states and one senatorial district in Delta State.

🚨 ERGP1247022: GRADING/ASPHALTING OF FARM SETTLEMENT ROAD WITH DRAINAGE CON...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Road construction and infrastructure development falls outside ARCN's mandate which focuses on coordinating agricultural research, training, and extension activities rather than physical infrastructure projects.

🚨 ERGP1246906: INSTALLATION OF MOTORIZED BOREHOLE WITH OVERHEAD TANK IN SEL...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Installing motorized boreholes with overhead tanks in communities is a water infrastructure development activity that falls outside ARCN's mandate, which is specifically focused on agricultural research, training, and extension activities rather than community water supply projects.

🚨 ERGP1246906: INSTALLATION OF MOTORIZED BOREHOLE WITH OVERHEAD TANK IN SEL...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Installing motorized boreholes with overhead tanks in communities is a water infrastructure project that falls outside ARCN's mandate, which specifically focuses on agricultural research, training, and extension activities rather than community water supply infrastructure.

🚨 ERGP1246909: CONSTRUCTION AND TARRING (WITH ASPHALT) OF DADINKOWA - MAGAN...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Road construction and tarring falls outside ARCN's mandate which is specifically focused on agricultural research, training, extension activities, and coordination of agricultural research institutes rather than infrastructure development.

🚨 ERGP1246909: CONSTRUCTION AND TARRING (WITH ASPHALT) OF DADINKOWA - MAGAN...
   Agency: AGRICULTURAL RESEARCH COUNCIL OF NIGERIA
   Amount: ₦1,050,000,000
   Confidence: HIGH
   Reason: Road construction and tarring falls under infrastructure development which is outside ARCN's mandate that specifically focuses on agricultural research, training, extension activities, and coordination of agricultural institutes.

🚨 ERGP25247721: SUPPLY OF FURNITURE AND EQUIPMENT FOR SCHOOL OF BIOMEDICAL E...
   Agency: ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOSPITAL BAUCHI
   Amount: ₦1,000,000,000
   Confidence: HIGH
   Reason: The budget item is for a School of Biomedical Engineering, but ATBUTH is a teaching hospital affiliated with a College of Medical Sciences that focuses on clinical training, healthcare delivery, and medical research, not biomedical engineering education.

In [90]:
print(len(result_df_1_50))

2355

In [89]:
mandate_deviation_output_path_51_200 = "data/outputs/mandate_deviation/llm_alignment_results_51_to_200.csv"
result_df_51_200 = pd.read_csv(mandate_deviation_output_path_51_200)

In [91]:
print(len(result_df_51_200))

5686

In [92]:
# Merge vertically (stack rows)
merged_mandate_deviation_for_mdas_1_200_df = pd.concat([result_df_1_50, result_df_51_200], ignore_index=True)

In [93]:
print(len(merged_mandate_deviation_for_mdas_1_200_df))

8041

In [108]:
cols = ['code', 'ergp_line_item', 'mda_code', 'amount']

In [109]:
duplicates = merged_mandate_deviation_for_mdas_1_200_df[merged_mandate_deviation_for_mdas_1_200_df.duplicated(subset=cols)]

In [110]:
duplicates.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
800,ERGP30242140,CONSTRUCTION OF AL-QUAREEB COMMUNITY MOSQUE AN...,215014001,COCOA RESEARCH INSTITUTE- IBADAN,NaN,280000000.0,NO,HIGH,"Construction of a mosque, palace, and provisio...",100
801,ERGP30242141,RENOVATION OF SCHOOLS IN IBARAPA EAST/IDO FEDE...,215014001,COCOA RESEARCH INSTITUTE- IBADAN,NaN,140000000.0,NO,HIGH,The renovation of schools falls under educatio...,100
802,ERGP30242143,CONSTRUCTION OF WELL EQUIPPED I.C.T CENTER IN ...,215014001,COCOA RESEARCH INSTITUTE- IBADAN,NaN,175000000.0,NO,HIGH,The construction of an ICT center in a specifi...,100
803,ERGP30242145,PROVISION OF MOTORISED BOREHOLE ACROSS OGO-OLU...,215014001,COCOA RESEARCH INSTITUTE- IBADAN,NaN,140000000.0,NO,HIGH,Providing motorized boreholes across a specifi...,100
804,ERGP30242146,PROVISION OF ALL IN ONE SOLAR POWERED STREETLI...,215014001,COCOA RESEARCH INSTITUTE- IBADAN,NaN,140000000.0,NO,HIGH,Installing solar streetlights in federal const...,100

In [111]:
print(len(duplicates))

235

In [112]:
merged_mandate_deviation_for_mdas_1_200_df_no_duplicates = merged_mandate_deviation_for_mdas_1_200_df.drop_duplicates(subset=cols)

In [113]:
merged_mandate_deviation_for_mdas_1_200_df_no_duplicates.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
0,ERGP1102191,IT INFRASTRUCTURE AND ASSOCIATED EQUIPMENT\n,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,9.817500e+07,YES,HIGH,IT infrastructure and associated equipment dir...,0
1,ERGP1102209,PURCHASE OF OFFICE FURNITURE AND FITTINGS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.490738e+07,YES,HIGH,Office furniture and fittings are necessary ad...,0
2,ERGP1205869,PURCHASE OF LAP TOP AND DESKTOP COMPUTERS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.107260e+08,YES,HIGH,Purchasing computers for staff official use is...,0
3,ERGP1205905,REMODELING OF SECURITY HOUSE AND BPE MAIN ENTR...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+07,PARTIAL,MEDIUM,While the remodeling of BPE's main entrance do...,50
4,ERGP16234836,"""ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT H...",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+10,NO,HIGH,The budget item refers to acquiring headquarte...,100

In [114]:
df = merged_mandate_deviation_for_mdas_1_200_df_no_duplicates.reset_index(drop=True)

In [116]:
mandate_deviation_output_path_1_200 = "data/outputs/mandate_deviation/llm_alignment_results_1_to_200_combined.csv"
df.to_csv(mandate_deviation_output_path_1_200, index=False)

In [115]:
df.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
0,ERGP1102191,IT INFRASTRUCTURE AND ASSOCIATED EQUIPMENT\n,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,9.817500e+07,YES,HIGH,IT infrastructure and associated equipment dir...,0
1,ERGP1102209,PURCHASE OF OFFICE FURNITURE AND FITTINGS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.490738e+07,YES,HIGH,Office furniture and fittings are necessary ad...,0
2,ERGP1205869,PURCHASE OF LAP TOP AND DESKTOP COMPUTERS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.107260e+08,YES,HIGH,Purchasing computers for staff official use is...,0
3,ERGP1205905,REMODELING OF SECURITY HOUSE AND BPE MAIN ENTR...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+07,PARTIAL,MEDIUM,While the remodeling of BPE's main entrance do...,50
4,ERGP16234836,"""ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT H...",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+10,NO,HIGH,The budget item refers to acquiring headquarte...,100

In [131]:
street_light_list = ['STREET LIGHT', 'streetlight', 'street lights', 'streetlights']
# Filter the DataFrame
street_lights_df = df[df['ergp_line_item'].isin(street_light_list)]

# street_lights_df = df[df['ergp_line_item'].str.lower().isin(street_light_list)]



# List of keywords to check
# keywords = ['test', 'test2']

# Create a regular expression pattern by joining the keywords with '|'
pattern = '|'.join(street_light_list)

# Filter the DataFrame for rows where any keyword occurs in the column
street_lights_df = df[df['ergp_line_item'].str.contains(pattern, case=False, na=False)]

# print(street_lights_df)

              code                                     ergp_line_item  \
40    ERGP10225206  SOLAR STREET LIGHT SYSTEM FOR ACADEMIC AREAS A...
128   ERGP10236498  THREE-IN-ONE SOLAR STREET LIGHT IN OGBARU FEDE...
129   ERGP10236499  PROVISION OF SOLAR STREET LIGHT IN ALIERO/GWAN...
130   ERGP10236500  PROVISION OF SOLAR STREET LIGHT IN GORONYO/GAD...
132   ERGP10236527  PROVISION AND INSTALATION OF STREETLIGHTS IN K...
...            ...                                                ...
7310  ERGP25242158  PROVISION OF ALL IN ONE SOLAR STREET LIGHTS IN...
7312  ERGP25242166  PROVISION OF ALL IN ONE SOLAR STREET LIGHTS IN...
7409  ERGP25226606                 PROVISION OF SOLAR STREET LIGHTS\n
7628  ERGP25240706  SUPPLY AND INSTALLATION OF SOLAR POWERED STREE...
7711  ERGP10224538  REHABILITATION/INSTALLATION OF STREET LIGHTS A...

       mda_code                                             agency  \
40    116008001                    COMMAND AND STAFF COLLEGE, JAJI
128   161022001  BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...
129   161022001  BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...
130   161022001  BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...
132   161022001  BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...
...         ...                                                ...
7310  521027017                    FEDERAL MEDICAL CENTRE, UMUAHIA
7312  521027017                    FEDERAL MEDICAL CENTRE, UMUAHIA
7409  521027024                 FEDERAL MEDICAL CENTRE, NGURU YOBE
7628  521027038                FEDERAL MEDICAL CENTRE, EBUTE METTA
7711  521027058      FEDERAL MEDICAL CENTRE ONITSHA, ANAMBRA STATE

      mother_ministry       amount alignment confidence  \
40                NaN  101563700.0       YES       HIGH
128               NaN   21000000.0        NO       HIGH
129               NaN   14000000.0       YES       HIGH
130               NaN   14000000.0       YES       HIGH
132               NaN   35000000.0        NO       HIGH
...               ...          ...       ...        ...
7310              NaN  105000000.0        NO       HIGH
7312              NaN  105000000.0        NO       HIGH
7409              NaN    7000000.0   PARTIAL     MEDIUM
7628              NaN   21000000.0        NO       HIGH
7711              NaN   10500000.0       YES       HIGH

                                                 reason  \
40    Solar street lighting for academic areas and s...
128   Ogbaru Federal Constituency in Anambra State i...
129   This budget item aligns with BCDA's mandate to...
130   Providing solar street lights in border consti...
132   The budget item targets a federal constituency...
...                                                 ...
7310  Installing solar street lights in various loca...
7312  Installing solar street lights across multiple...
7409  Solar street lights can support the medical ce...
7628  Installing solar street lights in Kwara State ...
7711  Installing street lights at the hospital direc...

      mandate_deviation_score
40                          0
128                       100
129                         0
130                         0
132                       100
...                       ...
7310                      100
7312                      100
7409                       50
7628                      100
7711                        0

[731 rows x 10 columns]

In [132]:
street_lights_df

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
40,ERGP10225206,SOLAR STREET LIGHT SYSTEM FOR ACADEMIC AREAS A...,116008001,"COMMAND AND STAFF COLLEGE, JAJI",NaN,101563700.0,YES,HIGH,Solar street lighting for academic areas and s...,0
128,ERGP10236498,THREE-IN-ONE SOLAR STREET LIGHT IN OGBARU FEDE...,161022001,BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...,NaN,21000000.0,NO,HIGH,Ogbaru Federal Constituency in Anambra State i...,100
129,ERGP10236499,PROVISION OF SOLAR STREET LIGHT IN ALIERO/GWAN...,161022001,BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...,NaN,14000000.0,YES,HIGH,This budget item aligns with BCDA's mandate to...,0
130,ERGP10236500,PROVISION OF SOLAR STREET LIGHT IN GORONYO/GAD...,161022001,BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...,NaN,14000000.0,YES,HIGH,Providing solar street lights in border consti...,0
132,ERGP10236527,PROVISION AND INSTALATION OF STREETLIGHTS IN K...,161022001,BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) H...,NaN,35000000.0,NO,HIGH,The budget item targets a federal constituency...,100
...,...,...,...,...,...,...,...,...,...,...
7310,ERGP25242158,PROVISION OF ALL IN ONE SOLAR STREET LIGHTS IN...,521027017,"FEDERAL MEDICAL CENTRE, UMUAHIA",NaN,105000000.0,NO,HIGH,Installing solar street lights in various loca...,100
7312,ERGP25242166,PROVISION OF ALL IN ONE SOLAR STREET LIGHTS IN...,521027017,"FEDERAL MEDICAL CENTRE, UMUAHIA",NaN,105000000.0,NO,HIGH,Installing solar street lights across multiple...,100
7409,ERGP25226606,PROVISION OF SOLAR STREET LIGHTS\n,521027024,"FEDERAL MEDICAL CENTRE, NGURU YOBE",NaN,7000000.0,PARTIAL,MEDIUM,Solar street lights can support the medical ce...,50
7628,ERGP25240706,SUPPLY AND INSTALLATION OF SOLAR POWERED STREE...,521027038,"FEDERAL MEDICAL CENTRE, EBUTE METTA",NaN,21000000.0,NO,HIGH,Installing solar street lights in Kwara State ...,100
7711,ERGP10224538,REHABILITATION/INSTALLATION OF STREET LIGHTS A...,521027058,"FEDERAL MEDICAL CENTRE ONITSHA, ANAMBRA STATE",NaN,10500000.0,YES,HIGH,Installing street lights at the hospital direc...,0

In [134]:
street_light_total = street_lights_df['amount'].sum()
print(street_light_total/1000000000)

118.242932783

In [128]:
df.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
0,ERGP1102191,IT INFRASTRUCTURE AND ASSOCIATED EQUIPMENT\n,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,9.817500e+07,YES,HIGH,IT infrastructure and associated equipment dir...,0
1,ERGP1102209,PURCHASE OF OFFICE FURNITURE AND FITTINGS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.490738e+07,YES,HIGH,Office furniture and fittings are necessary ad...,0
2,ERGP1205869,PURCHASE OF LAP TOP AND DESKTOP COMPUTERS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.107260e+08,YES,HIGH,Purchasing computers for staff official use is...,0
3,ERGP1205905,REMODELING OF SECURITY HOUSE AND BPE MAIN ENTR...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+07,PARTIAL,MEDIUM,While the remodeling of BPE's main entrance do...,50
4,ERGP16234836,"""ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT H...",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+10,NO,HIGH,The budget item refers to acquiring headquarte...,100

In [137]:
print(len(street_lights_df['mda_code'].unique()))

44

In [ ]:
mdas_1_891_no_duplicates

In [90]:
street_light_list = ['STREET LIGHT', 'streetlight', 'street lights', 'streetlights']
# Filter the DataFrame
# street_lights_df2 = mdas_1_891_no_duplicates[mdas_1_891_no_duplicates['ergp_line_item'].isin(street_light_list)]

# street_lights_df = df[df['ergp_line_item'].str.lower().isin(street_light_list)]



# List of keywords to check
# keywords = ['test', 'test2']

# Create a regular expression pattern by joining the keywords with '|'
pattern = '|'.join(street_light_list)

# Filter the DataFrame for rows where any keyword occurs in the column
street_lights_df2 = mdas_1_891_no_duplicates[mdas_1_891_no_duplicates['ergp_line_item'].str.contains(pattern, case=False, na=False)]

# print(street_lights_df)

In [91]:
street_lights_df2['amount'].sum()/1000000000

278.491847158

In [93]:
print(len(street_lights_df2['mda_code'].unique()))

133

In [105]:

print(len(budget_df['code'].unique()))

27535

## 04 April 2026 - Remaining 7,148 projects

In [5]:
# Mandate data ingestion
input_path_csv = "data/inputs/master_combined_mandate_1_to_891.csv"

mandate_df_1_891 = pd.read_csv(input_path_csv)

In [6]:
print(len(mandate_df_1_891))

876

In [11]:
mandate_df_1_891.head()

,mda_code,mda_name,mandate_description
0,521025001,"41. COMMUNITY HEALTH TUTOR PROGRAMME, UCH",The Community Health Tutor Programme at the Un...
1,517015001,42. COMPUTER PROFESSIONALS (REGISTRATION COUNC...,The Computer Professionals (Registration Counc...
2,119009118,"43. CONSULATE GENERAL OF NIGERIA, FRANKFURT, G...",The Consulate General of the Federal Republic ...
3,234005001,44. COUNCIL FOR THE REGULATION OF ENGINEERING ...,The Council for the Regulation of Engineering ...
4,229006001,45. COUNCIL FOR THE REGULATION OF FREIGHT FORW...,The Council for the Regulation of Freight Forw...

In [18]:
# Mandate data ingestion
budget_input_path_csv = "data/outputs/ergp_budget_2026_proposed_remaining_7148_projects.csv"

budget_df_remaining_7148 = pd.read_csv(budget_input_path_csv)

In [19]:
print(len(budget_df_remaining_7148))

7148

In [20]:
budget_df_remaining_7148.head()

,code,ergp_line_item,status,amount,mda_code,agency,mother_ministry
0,ERGP15172225,COMPUTERISATION OF THE INTERNAL AUDIT DEPARTME...,ONGOING,15559347.0,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN
1,ERGP15172263,ESTABLISHMENT OF CONDUCT OF CORRUPTION INDEX\n,ONGOING,7125580.0,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN
2,ERGP16172270,"CAPACITY BUILDING FOR INFORMATION, ADMIN AND A...",ONGOING,15680000.0,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN
3,ERGP16204356,"DIGITIZATION OF VOTE BOOKS, CASH BOOKS, FIXED ...",ONGOING,13860000.0,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN
4,ERGP16204392,ATTENDANCE OF NATIONAL COUNCIL ON IMATION\n,ONGOING,3871658.0,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN

In [21]:
mda_list = budget_df_remaining_7148['mda_code'].unique().tolist()
print(len(mda_list))

131

In [22]:
filtered_mandate_df = mandate_df_1_891[mandate_df_1_891['mda_code'].isin(mda_list)]

In [25]:
filtered_mandate_df = filtered_mandate_df.reset_index(drop=True)

In [28]:
filtered_mandate_df.tail()

,mda_code,mda_name,mandate_description
114,254001001,176. FEDERAL MINISTRY OF MARINE AND BLUE ECONO...,The Federal Ministry of Marine and Blue Econom...
115,451001001,177. FEDERAL MINISTRY OF NIGER DELTA HQTRS,The Federal Ministry of Niger Delta Affairs wa...
116,155001001,178. FEDERAL MINISTRY OF POLICE AFFAIRS,The Federal Ministry of Police Affairs was est...
117,231001001,179. FEDERAL MINISTRY OF POWER -HQTRS,The Federal Ministry of Power is responsible f...
118,228001001,"180. FEDERAL MINISTRY OF SCIENCE, TECHNOLOGY A...","The Federal Ministry of Science, Technology an..."

In [30]:
print(len(filtered_mandate_df))

119

In [32]:
# =============================================================================
#  USAGE - remaining 7,148 projects
# =============================================================================


# Example usage (replace with your actual data)

# 1. Set your API key
api_key = ANTHROPIC_API_KEY

# 2. Run analysis
result_df = analyze_budget_mandate_alignment_llm(
    budget_df=budget_df_remaining_7148,
    mandate_df=filtered_mandate_df,
    api_key=api_key,
    progress_interval=10
)

Analyzing 7148 budget items with Claude...
Estimated time: 178.7 - 297.8 minutes
============================================================
   Processed 10/7148 (0.1%) | Elapsed: 0.4min | Remaining: 289.4min
   Processed 20/7148 (0.3%) | Elapsed: 0.8min | Remaining: 277.8min
   Processed 30/7148 (0.4%) | Elapsed: 1.2min | Remaining: 286.7min
   Processed 40/7148 (0.6%) | Elapsed: 1.6min | Remaining: 280.9min
   Processed 50/7148 (0.7%) | Elapsed: 2.0min | Remaining: 279.1min
   Processed 60/7148 (0.8%) | Elapsed: 2.3min | Remaining: 274.9min
   Processed 70/7148 (1.0%) | Elapsed: 2.7min | Remaining: 273.9min
   Processed 80/7148 (1.1%) | Elapsed: 3.1min | Remaining: 274.3min
   Processed 90/7148 (1.3%) | Elapsed: 3.5min | Remaining: 274.6min
   Processed 100/7148 (1.4%) | Elapsed: 3.9min | Remaining: 272.7min
   Processed 110/7148 (1.5%) | Elapsed: 4.3min | Remaining: 272.9min
   Processed 120/7148 (1.7%) | Elapsed: 4.7min | Remaining: 272.6min
   Processed 130/7148 (1.8%) | Elapsed: 5.1min | Remaining: 273.1min
   Processed 140/7148 (2.0%) | Elapsed: 5.5min | Remaining: 273.0min
   Processed 150/7148 (2.1%) | Elapsed: 5.8min | Remaining: 271.4min
   Processed 160/7148 (2.2%) | Elapsed: 6.2min | Remaining: 270.0min
   Processed 170/7148 (2.4%) | Elapsed: 6.6min | Remaining: 270.0min
   Processed 180/7148 (2.5%) | Elapsed: 7.0min | Remaining: 271.3min
   Processed 190/7148 (2.7%) | Elapsed: 7.4min | Remaining: 272.2min
   Processed 200/7148 (2.8%) | Elapsed: 7.9min | Remaining: 273.0min
   Processed 210/7148 (2.9%) | Elapsed: 8.3min | Remaining: 272.9min
   Processed 220/7148 (3.1%) | Elapsed: 8.7min | Remaining: 273.4min
   Processed 230/7148 (3.2%) | Elapsed: 9.1min | Remaining: 274.3min
   Processed 240/7148 (3.4%) | Elapsed: 9.5min | Remaining: 273.6min
   Processed 250/7148 (3.5%) | Elapsed: 9.9min | Remaining: 273.4min
   Processed 260/7148 (3.6%) | Elapsed: 10.3min | Remaining: 272.6min
   Processed 270/7148 (3.8%) | Elapsed: 10.7min | Remaining: 271.8min
   Processed 280/7148 (3.9%) | Elapsed: 11.1min | Remaining: 271.7min
   Processed 290/7148 (4.1%) | Elapsed: 11.4min | Remaining: 270.4min
   Processed 300/7148 (4.2%) | Elapsed: 11.8min | Remaining: 270.2min
   Processed 310/7148 (4.3%) | Elapsed: 12.2min | Remaining: 268.9min
   Processed 320/7148 (4.5%) | Elapsed: 12.6min | Remaining: 267.8min
   Processed 330/7148 (4.6%) | Elapsed: 12.9min | Remaining: 267.3min
   Processed 340/7148 (4.8%) | Elapsed: 13.3min | Remaining: 266.8min
   Processed 350/7148 (4.9%) | Elapsed: 13.7min | Remaining: 266.6min
   Processed 360/7148 (5.0%) | Elapsed: 14.1min | Remaining: 265.8min
   Processed 370/7148 (5.2%) | Elapsed: 14.5min | Remaining: 264.7min
   Processed 380/7148 (5.3%) | Elapsed: 14.8min | Remaining: 264.3min
   Processed 390/7148 (5.5%) | Elapsed: 15.3min | Remaining: 264.4min
   Processed 400/7148 (5.6%) | Elapsed: 15.6min | Remaining: 263.7min
   Processed 410/7148 (5.7%) | Elapsed: 16.0min | Remaining: 263.4min
   Processed 420/7148 (5.9%) | Elapsed: 16.4min | Remaining: 263.3min
   Processed 430/7148 (6.0%) | Elapsed: 16.8min | Remaining: 262.7min
   Processed 440/7148 (6.2%) | Elapsed: 17.2min | Remaining: 262.0min
   Processed 450/7148 (6.3%) | Elapsed: 17.5min | Remaining: 261.2min
   Processed 460/7148 (6.4%) | Elapsed: 17.9min | Remaining: 260.4min
   Processed 470/7148 (6.6%) | Elapsed: 18.3min | Remaining: 259.8min
   Processed 480/7148 (6.7%) | Elapsed: 18.7min | Remaining: 259.3min
   Processed 490/7148 (6.9%) | Elapsed: 19.1min | Remaining: 259.0min
   Processed 500/7148 (7.0%) | Elapsed: 19.5min | Remaining: 258.7min
   Processed 510/7148 (7.1%) | Elapsed: 19.9min | Remaining: 258.6min
   Processed 520/7148 (7.3%) | Elapsed: 20.2min | Remaining: 257.8min
   Processed 530/7148 (7.4%) | Elapsed: 20.6min | Remaining: 257.6min
   Processed 540/7148 (7.6%) | Elapsed: 21.1min | Remaining: 257.9min
   Processed 550/7148 (7.7%) | Elapsed: 21.5min | Remaining: 257.6min
   Processed 560/7148 (7.8%) | Elapsed: 21.9min | Remaining: 257.1min
   Processed 570/7148 (8.0%) | Elapsed: 22.3min | Remaining: 256.9min
   Processed 580/7148 (8.1%) | Elapsed: 22.7min | Remaining: 256.7min
   Processed 590/7148 (8.3%) | Elapsed: 23.1min | Remaining: 256.5min
   Processed 600/7148 (8.4%) | Elapsed: 23.5min | Remaining: 256.2min
   Processed 610/7148 (8.5%) | Elapsed: 24.0min | Remaining: 257.2min
   Processed 620/7148 (8.7%) | Elapsed: 24.4min | Remaining: 257.0min
   Processed 630/7148 (8.8%) | Elapsed: 24.8min | Remaining: 256.3min
   Processed 640/7148 (9.0%) | Elapsed: 25.2min | Remaining: 256.3min
   Processed 650/7148 (9.1%) | Elapsed: 25.6min | Remaining: 255.7min
   Processed 660/7148 (9.2%) | Elapsed: 26.0min | Remaining: 255.2min
   Processed 670/7148 (9.4%) | Elapsed: 26.4min | Remaining: 255.0min
   Processed 680/7148 (9.5%) | Elapsed: 26.8min | Remaining: 254.5min
   Processed 690/7148 (9.7%) | Elapsed: 27.1min | Remaining: 253.8min
   Processed 700/7148 (9.8%) | Elapsed: 27.5min | Remaining: 253.7min
   Processed 710/7148 (9.9%) | Elapsed: 27.9min | Remaining: 252.7min
   Processed 720/7148 (10.1%) | Elapsed: 27.9min | Remaining: 248.8min
   Processed 730/7148 (10.2%) | Elapsed: 27.9min | Remaining: 245.3min
   Processed 740/7148 (10.4%) | Elapsed: 28.3min | Remaining: 245.2min
   Processed 750/7148 (10.5%) | Elapsed: 28.7min | Remaining: 244.8min
   Processed 760/7148 (10.6%) | Elapsed: 29.1min | Remaining: 244.8min
   Processed 770/7148 (10.8%) | Elapsed: 29.6min | Remaining: 245.1min
   Processed 780/7148 (10.9%) | Elapsed: 30.0min | Remaining: 244.9min
   Processed 790/7148 (11.1%) | Elapsed: 30.5min | Remaining: 245.3min
   Processed 800/7148 (11.2%) | Elapsed: 31.0min | Remaining: 245.6min
   Processed 810/7148 (11.3%) | Elapsed: 31.4min | Remaining: 245.7min
   Processed 820/7148 (11.5%) | Elapsed: 31.8min | Remaining: 245.5min
   Processed 830/7148 (11.6%) | Elapsed: 32.3min | Remaining: 245.7min
   Processed 840/7148 (11.8%) | Elapsed: 32.7min | Remaining: 245.6min
   Processed 850/7148 (11.9%) | Elapsed: 33.2min | Remaining: 245.6min
   Processed 860/7148 (12.0%) | Elapsed: 33.6min | Remaining: 245.7min
   Processed 870/7148 (12.2%) | Elapsed: 34.0min | Remaining: 245.5min
   Processed 880/7148 (12.3%) | Elapsed: 34.4min | Remaining: 245.3min
   Processed 890/7148 (12.5%) | Elapsed: 34.9min | Remaining: 245.2min
   Processed 900/7148 (12.6%) | Elapsed: 35.3min | Remaining: 244.9min
   Processed 910/7148 (12.7%) | Elapsed: 35.7min | Remaining: 244.5min
   Processed 920/7148 (12.9%) | Elapsed: 36.1min | Remaining: 244.2min
   Processed 930/7148 (13.0%) | Elapsed: 36.6min | Remaining: 244.5min
   Processed 940/7148 (13.2%) | Elapsed: 37.1min | Remaining: 244.8min
   Processed 950/7148 (13.3%) | Elapsed: 37.5min | Remaining: 244.8min
   Processed 960/7148 (13.4%) | Elapsed: 38.0min | Remaining: 244.7min
   Processed 970/7148 (13.6%) | Elapsed: 38.3min | Remaining: 244.1min
   Processed 980/7148 (13.7%) | Elapsed: 38.8min | Remaining: 244.0min
   Processed 990/7148 (13.9%) | Elapsed: 39.2min | Remaining: 243.6min
   Processed 1000/7148 (14.0%) | Elapsed: 39.6min | Remaining: 243.2min
   Processed 1010/7148 (14.1%) | Elapsed: 40.0min | Remaining: 242.8min
   Processed 1020/7148 (14.3%) | Elapsed: 40.3min | Remaining: 242.3min
   Processed 1030/7148 (14.4%) | Elapsed: 40.7min | Remaining: 241.8min
   Processed 1040/7148 (14.5%) | Elapsed: 41.2min | Remaining: 241.7min
   Processed 1050/7148 (14.7%) | Elapsed: 41.6min | Remaining: 241.5min
   Processed 1060/7148 (14.8%) | Elapsed: 42.1min | Remaining: 241.6min
   Processed 1070/7148 (15.0%) | Elapsed: 42.5min | Remaining: 241.7min
   Processed 1080/7148 (15.1%) | Elapsed: 43.0min | Remaining: 241.5min
   Processed 1090/7148 (15.2%) | Elapsed: 43.4min | Remaining: 241.3min
   Processed 1100/7148 (15.4%) | Elapsed: 43.9min | Remaining: 241.2min
   Processed 1110/7148 (15.5%) | Elapsed: 44.3min | Remaining: 240.8min
   Processed 1120/7148 (15.7%) | Elapsed: 44.7min | Remaining: 240.4min
   Processed 1130/7148 (15.8%) | Elapsed: 45.1min | Remaining: 240.4min
   Processed 1140/7148 (15.9%) | Elapsed: 45.6min | Remaining: 240.3min
   Processed 1150/7148 (16.1%) | Elapsed: 46.0min | Remaining: 240.0min
   Processed 1160/7148 (16.2%) | Elapsed: 46.4min | Remaining: 239.7min
   Processed 1170/7148 (16.4%) | Elapsed: 46.9min | Remaining: 239.7min
   Processed 1180/7148 (16.5%) | Elapsed: 47.3min | Remaining: 239.4min
   Processed 1190/7148 (16.6%) | Elapsed: 47.7min | Remaining: 239.0min
   Processed 1200/7148 (16.8%) | Elapsed: 48.1min | Remaining: 238.6min
   Processed 1210/7148 (16.9%) | Elapsed: 48.5min | Remaining: 238.1min
   Processed 1220/7148 (17.1%) | Elapsed: 48.9min | Remaining: 237.8min
   Processed 1230/7148 (17.2%) | Elapsed: 49.4min | Remaining: 237.6min
   Processed 1240/7148 (17.3%) | Elapsed: 49.8min | Remaining: 237.4min
   Processed 1250/7148 (17.5%) | Elapsed: 50.3min | Remaining: 237.3min
   Processed 1260/7148 (17.6%) | Elapsed: 50.7min | Remaining: 236.9min
   Processed 1270/7148 (17.8%) | Elapsed: 51.1min | Remaining: 236.5min
   Processed 1280/7148 (17.9%) | Elapsed: 51.5min | Remaining: 236.2min
   Processed 1290/7148 (18.0%) | Elapsed: 52.0min | Remaining: 236.1min
   Processed 1300/7148 (18.2%) | Elapsed: 52.5min | Remaining: 236.1min
   Processed 1310/7148 (18.3%) | Elapsed: 53.0min | Remaining: 236.0min
   Processed 1320/7148 (18.5%) | Elapsed: 53.4min | Remaining: 235.7min
   Processed 1330/7148 (18.6%) | Elapsed: 53.8min | Remaining: 235.2min
   Processed 1340/7148 (18.7%) | Elapsed: 54.2min | Remaining: 234.9min
   Processed 1350/7148 (18.9%) | Elapsed: 54.6min | Remaining: 234.6min
   Processed 1360/7148 (19.0%) | Elapsed: 55.1min | Remaining: 234.3min
   Processed 1370/7148 (19.2%) | Elapsed: 55.5min | Remaining: 233.9min
   Processed 1380/7148 (19.3%) | Elapsed: 55.9min | Remaining: 233.6min
   Processed 1390/7148 (19.4%) | Elapsed: 56.3min | Remaining: 233.4min
   Processed 1400/7148 (19.6%) | Elapsed: 67.3min | Remaining: 276.2min
   Processed 1410/7148 (19.7%) | Elapsed: 67.8min | Remaining: 275.8min
   Processed 1420/7148 (19.9%) | Elapsed: 68.2min | Remaining: 275.0min
   Processed 1430/7148 (20.0%) | Elapsed: 68.6min | Remaining: 274.2min
   Processed 1440/7148 (20.1%) | Elapsed: 69.0min | Remaining: 273.4min
   Processed 1450/7148 (20.3%) | Elapsed: 69.4min | Remaining: 272.7min
   Processed 1460/7148 (20.4%) | Elapsed: 69.9min | Remaining: 272.2min
   Processed 1470/7148 (20.6%) | Elapsed: 70.3min | Remaining: 271.6min
   Processed 1480/7148 (20.7%) | Elapsed: 70.8min | Remaining: 271.0min
   Processed 1490/7148 (20.8%) | Elapsed: 71.2min | Remaining: 270.4min
   Processed 1500/7148 (21.0%) | Elapsed: 71.7min | Remaining: 270.0min
   Processed 1510/7148 (21.1%) | Elapsed: 72.1min | Remaining: 269.3min
   Processed 1520/7148 (21.3%) | Elapsed: 72.6min | Remaining: 268.7min
   Processed 1530/7148 (21.4%) | Elapsed: 73.0min | Remaining: 268.0min
   Processed 1540/7148 (21.5%) | Elapsed: 73.4min | Remaining: 267.3min
   Processed 1550/7148 (21.7%) | Elapsed: 73.8min | Remaining: 266.4min
   Processed 1560/7148 (21.8%) | Elapsed: 74.2min | Remaining: 265.6min
   Processed 1570/7148 (22.0%) | Elapsed: 74.6min | Remaining: 265.0min
   Processed 1580/7148 (22.1%) | Elapsed: 75.0min | Remaining: 264.4min
   Processed 1590/7148 (22.2%) | Elapsed: 75.4min | Remaining: 263.6min
   Processed 1600/7148 (22.4%) | Elapsed: 75.8min | Remaining: 262.9min
   Processed 1610/7148 (22.5%) | Elapsed: 76.3min | Remaining: 262.3min
   Processed 1620/7148 (22.7%) | Elapsed: 76.7min | Remaining: 261.9min
   Processed 1630/7148 (22.8%) | Elapsed: 77.2min | Remaining: 261.3min
   Processed 1640/7148 (22.9%) | Elapsed: 77.6min | Remaining: 260.6min
   Processed 1650/7148 (23.1%) | Elapsed: 78.0min | Remaining: 259.7min
   Processed 1660/7148 (23.2%) | Elapsed: 78.4min | Remaining: 259.2min
   Processed 1670/7148 (23.4%) | Elapsed: 78.8min | Remaining: 258.6min
   Processed 1680/7148 (23.5%) | Elapsed: 79.3min | Remaining: 258.2min
   Processed 1690/7148 (23.6%) | Elapsed: 79.8min | Remaining: 257.6min
   Processed 1700/7148 (23.8%) | Elapsed: 80.2min | Remaining: 257.1min
   Processed 1710/7148 (23.9%) | Elapsed: 80.7min | Remaining: 256.7min
   Processed 1720/7148 (24.1%) | Elapsed: 81.1min | Remaining: 256.0min
   Processed 1730/7148 (24.2%) | Elapsed: 81.6min | Remaining: 255.6min
   Processed 1740/7148 (24.3%) | Elapsed: 82.1min | Remaining: 255.1min
   Processed 1750/7148 (24.5%) | Elapsed: 82.6min | Remaining: 254.6min
   Processed 1760/7148 (24.6%) | Elapsed: 83.0min | Remaining: 254.2min
   Processed 1770/7148 (24.8%) | Elapsed: 83.5min | Remaining: 253.6min
   Processed 1780/7148 (24.9%) | Elapsed: 84.0min | Remaining: 253.2min
   Processed 1790/7148 (25.0%) | Elapsed: 84.3min | Remaining: 252.5min
   Processed 1800/7148 (25.2%) | Elapsed: 84.8min | Remaining: 252.0min
   Processed 1810/7148 (25.3%) | Elapsed: 85.2min | Remaining: 251.3min
   Processed 1820/7148 (25.5%) | Elapsed: 85.8min | Remaining: 251.2min
   Processed 1830/7148 (25.6%) | Elapsed: 86.3min | Remaining: 250.9min
   Processed 1840/7148 (25.7%) | Elapsed: 86.8min | Remaining: 250.3min
   Processed 1850/7148 (25.9%) | Elapsed: 87.3min | Remaining: 250.0min
   Processed 1860/7148 (26.0%) | Elapsed: 87.7min | Remaining: 249.3min
   Processed 1870/7148 (26.2%) | Elapsed: 88.1min | Remaining: 248.8min
   Processed 1880/7148 (26.3%) | Elapsed: 88.6min | Remaining: 248.3min
   Processed 1890/7148 (26.4%) | Elapsed: 89.1min | Remaining: 247.8min
   Processed 1900/7148 (26.6%) | Elapsed: 89.5min | Remaining: 247.2min
   Processed 1910/7148 (26.7%) | Elapsed: 90.0min | Remaining: 246.7min
   Processed 1920/7148 (26.9%) | Elapsed: 90.3min | Remaining: 245.9min
   Processed 1930/7148 (27.0%) | Elapsed: 90.7min | Remaining: 245.2min
   Processed 1940/7148 (27.1%) | Elapsed: 91.1min | Remaining: 244.6min
   Processed 1950/7148 (27.3%) | Elapsed: 91.5min | Remaining: 243.9min
   Processed 1960/7148 (27.4%) | Elapsed: 91.9min | Remaining: 243.2min
   Processed 1970/7148 (27.6%) | Elapsed: 92.3min | Remaining: 242.6min
   Processed 1980/7148 (27.7%) | Elapsed: 92.7min | Remaining: 241.9min
   Processed 1990/7148 (27.8%) | Elapsed: 93.1min | Remaining: 241.2min
   Processed 2000/7148 (28.0%) | Elapsed: 93.5min | Remaining: 240.5min
   Processed 2010/7148 (28.1%) | Elapsed: 93.9min | Remaining: 239.9min
   Processed 2020/7148 (28.3%) | Elapsed: 94.3min | Remaining: 239.3min
   Processed 2030/7148 (28.4%) | Elapsed: 94.6min | Remaining: 238.6min
   Processed 2040/7148 (28.5%) | Elapsed: 95.1min | Remaining: 238.0min
   Processed 2050/7148 (28.7%) | Elapsed: 95.4min | Remaining: 237.3min
   Processed 2060/7148 (28.8%) | Elapsed: 95.8min | Remaining: 236.7min
   Processed 2070/7148 (29.0%) | Elapsed: 96.2min | Remaining: 236.1min
   Processed 2080/7148 (29.1%) | Elapsed: 96.6min | Remaining: 235.3min
   Processed 2090/7148 (29.2%) | Elapsed: 97.0min | Remaining: 234.7min
   Processed 2100/7148 (29.4%) | Elapsed: 97.4min | Remaining: 234.2min
   Processed 2110/7148 (29.5%) | Elapsed: 97.8min | Remaining: 233.5min
   Processed 2120/7148 (29.7%) | Elapsed: 98.2min | Remaining: 233.0min
   Processed 2130/7148 (29.8%) | Elapsed: 98.6min | Remaining: 232.3min
   Processed 2140/7148 (29.9%) | Elapsed: 99.0min | Remaining: 231.7min
   Processed 2150/7148 (30.1%) | Elapsed: 99.4min | Remaining: 231.0min
   Processed 2160/7148 (30.2%) | Elapsed: 111.9min | Remaining: 258.5min
   Processed 2170/7148 (30.4%) | Elapsed: 112.3min | Remaining: 257.6min
   Processed 2180/7148 (30.5%) | Elapsed: 112.7min | Remaining: 256.7min
   Processed 2190/7148 (30.6%) | Elapsed: 113.0min | Remaining: 255.9min
   Processed 2200/7148 (30.8%) | Elapsed: 113.4min | Remaining: 255.1min
   Processed 2210/7148 (30.9%) | Elapsed: 113.8min | Remaining: 254.3min
   Processed 2220/7148 (31.1%) | Elapsed: 114.2min | Remaining: 253.5min
   Processed 2230/7148 (31.2%) | Elapsed: 114.6min | Remaining: 252.8min
   Processed 2240/7148 (31.3%) | Elapsed: 115.0min | Remaining: 252.0min
   Processed 2250/7148 (31.5%) | Elapsed: 115.4min | Remaining: 251.2min
   Processed 2260/7148 (31.6%) | Elapsed: 115.8min | Remaining: 250.5min
   Processed 2270/7148 (31.8%) | Elapsed: 116.2min | Remaining: 249.7min
   Processed 2280/7148 (31.9%) | Elapsed: 116.6min | Remaining: 249.0min
   Processed 2290/7148 (32.0%) | Elapsed: 117.0min | Remaining: 248.2min
   Processed 2300/7148 (32.2%) | Elapsed: 117.5min | Remaining: 247.6min
   Processed 2310/7148 (32.3%) | Elapsed: 117.9min | Remaining: 246.9min
   Processed 2320/7148 (32.5%) | Elapsed: 118.3min | Remaining: 246.2min
   Processed 2330/7148 (32.6%) | Elapsed: 118.7min | Remaining: 245.4min
   Processed 2340/7148 (32.7%) | Elapsed: 119.0min | Remaining: 244.6min
   Processed 2350/7148 (32.9%) | Elapsed: 119.4min | Remaining: 243.8min
   Processed 2360/7148 (33.0%) | Elapsed: 119.8min | Remaining: 243.0min
   Processed 2370/7148 (33.2%) | Elapsed: 120.2min | Remaining: 242.2min
   Processed 2380/7148 (33.3%) | Elapsed: 120.5min | Remaining: 241.4min
   Processed 2390/7148 (33.4%) | Elapsed: 120.9min | Remaining: 240.8min
   Processed 2400/7148 (33.6%) | Elapsed: 121.3min | Remaining: 240.0min
   Processed 2410/7148 (33.7%) | Elapsed: 121.7min | Remaining: 239.2min
   Processed 2420/7148 (33.9%) | Elapsed: 122.1min | Remaining: 238.5min
   Processed 2430/7148 (34.0%) | Elapsed: 122.5min | Remaining: 237.8min
   Processed 2440/7148 (34.1%) | Elapsed: 122.8min | Remaining: 237.0min
   Processed 2450/7148 (34.3%) | Elapsed: 123.2min | Remaining: 236.3min
   Processed 2460/7148 (34.4%) | Elapsed: 123.6min | Remaining: 235.5min
   Processed 2470/7148 (34.6%) | Elapsed: 124.0min | Remaining: 234.8min
   Processed 2480/7148 (34.7%) | Elapsed: 124.3min | Remaining: 234.0min
   Processed 2490/7148 (34.8%) | Elapsed: 124.7min | Remaining: 233.2min
   Processed 2500/7148 (35.0%) | Elapsed: 125.1min | Remaining: 232.6min
   Processed 2510/7148 (35.1%) | Elapsed: 125.6min | Remaining: 232.1min
   Processed 2520/7148 (35.3%) | Elapsed: 126.0min | Remaining: 231.4min
   Processed 2530/7148 (35.4%) | Elapsed: 126.5min | Remaining: 230.8min
   Processed 2540/7148 (35.5%) | Elapsed: 126.9min | Remaining: 230.2min
   Processed 2550/7148 (35.7%) | Elapsed: 127.3min | Remaining: 229.5min
   Processed 2560/7148 (35.8%) | Elapsed: 127.6min | Remaining: 228.7min
   Processed 2570/7148 (36.0%) | Elapsed: 128.0min | Remaining: 228.0min
   Processed 2580/7148 (36.1%) | Elapsed: 128.4min | Remaining: 227.3min
   Processed 2590/7148 (36.2%) | Elapsed: 128.8min | Remaining: 226.6min
   Processed 2600/7148 (36.4%) | Elapsed: 129.2min | Remaining: 225.9min
   Processed 2610/7148 (36.5%) | Elapsed: 129.5min | Remaining: 225.2min
   Processed 2620/7148 (36.7%) | Elapsed: 129.9min | Remaining: 224.5min
   Processed 2630/7148 (36.8%) | Elapsed: 130.2min | Remaining: 223.7min
   Processed 2640/7148 (36.9%) | Elapsed: 130.6min | Remaining: 223.1min
   Processed 2650/7148 (37.1%) | Elapsed: 131.0min | Remaining: 222.4min
   Processed 2660/7148 (37.2%) | Elapsed: 131.4min | Remaining: 221.7min
   Processed 2670/7148 (37.4%) | Elapsed: 131.7min | Remaining: 221.0min
   Processed 2680/7148 (37.5%) | Elapsed: 132.1min | Remaining: 220.3min
   Processed 2690/7148 (37.6%) | Elapsed: 132.5min | Remaining: 219.6min
   Processed 2700/7148 (37.8%) | Elapsed: 132.9min | Remaining: 218.9min
   Processed 2710/7148 (37.9%) | Elapsed: 133.2min | Remaining: 218.2min
   Processed 2720/7148 (38.1%) | Elapsed: 133.6min | Remaining: 217.5min
   Processed 2730/7148 (38.2%) | Elapsed: 134.0min | Remaining: 216.8min
   Processed 2740/7148 (38.3%) | Elapsed: 134.4min | Remaining: 216.2min
   Processed 2750/7148 (38.5%) | Elapsed: 134.8min | Remaining: 215.6min
   Processed 2760/7148 (38.6%) | Elapsed: 135.2min | Remaining: 214.9min
   Processed 2770/7148 (38.8%) | Elapsed: 135.6min | Remaining: 214.3min

In [33]:
# 3. View results
print_summary_llm(result_df)
print_flagged_items_llm(result_df)

# 4. Export
result_df.to_csv("llm_alignment_results_remaining_7148.csv", index=False)

pass

================================================================================
SUMMARY: LLM-AS-JUDGE ANALYSIS
================================================================================

Total Budget Items: 7148
Total Budget Amount: ₦5,284,169,907,874

Alignment Distribution:
   YES: 4889 items (68.4%) | ₦4,214,756,672,651
   PARTIAL: 1160 items (16.2%) | ₦712,436,930,758
   NO: 995 items (13.9%) | ₦339,152,770,797
   UNKNOWN: 102 items (1.4%) | ₦17,365,733,668
   ERROR: 2 items (0.0%) | ₦457,800,000

🚨 Items flagged as NOT aligned: 995
   Flagged amount: ₦339,152,770,797

====================================================================================================
TOP 20 FLAGGED ITEMS (NOT ALIGNED)
====================================================================================================

🚨 ERGP1247779: CONTINGENCY FUND...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦100,000,000,000
   Confidence: HIGH
   Reason: A contingency fund is a general financial reserve that does not align with the Federal Ministry of Works' specific mandate to construct, rehabilitate and maintain federal roads and bridges infrastructure.

🚨 ERGP12231824: CONTINGENCY FUND
...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦10,514,000,000
   Confidence: HIGH
   Reason: Contingency funds are general emergency reserves that fall outside the Federal Ministry of Works' specific mandate of constructing, rehabilitating and maintaining federal roads and bridges infrastructure.

🚨 ERGP12234327: CONSTRUCTION OF GARBA DAMARGU STADIUM (MULTIPLE LOTS)
...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦9,800,000,000
   Confidence: HIGH
   Reason: Construction of a stadium falls outside the Federal Ministry of Works' core mandate which focuses exclusively on roads, bridges and related transportation infrastructure, not sports facilities.

🚨 ERGP12234326: CONSTRUCTION AND EQUIPPING OF ULTRAMODERN CONFERENCE CENTER ...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦5,600,000,000
   Confidence: HIGH
   Reason: Construction of conference centers is not within the Federal Ministry of Works' mandate, which is exclusively focused on federal roads, bridges and related transportation infrastructure.

🚨 ERGP12231265: REHABILITATION OF OGUNUSI ROAD TO OBA OGUNJI ROAD BY ODO-ERA...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦4,900,000,000
   Confidence: HIGH
   Reason: This appears to be a local/municipal road within Lagos city rather than a federal road, as the Federal Ministry of Works is responsible for federal roads, highways, interstate roads, and roads connecting state capitals, not local urban roads.

🚨 ERGP12234598: CONSTRUCTION OF 20KM INNER TOWNSHIP INTERVENTION ROAD IN COK...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦3,627,470,000
   Confidence: HIGH
   Reason: Inner township intervention roads are typically local/municipal infrastructure under state or local government jurisdiction, not federal roads that fall under the Federal Ministry of Works' mandate for interstate highways, major roads connecting state capitals, and federal road networks.

🚨 ERGP12234324: CONSTRUCTION OF MULTIPLE UNITS OF LOW-COST RESIDENTIAL HOUSE...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Construction of residential houses falls outside the Federal Ministry of Works' mandate which focuses exclusively on roads and bridges infrastructure, with housing functions separated following the October 2024 cabinet reshuffle.

🚨 ERGP12234542: UPGRADE OF EKITI CARGO AIRPORT
...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Airport infrastructure construction and upgrades fall outside the Federal Ministry of Works' mandate which is specifically limited to federal roads, bridges and related road infrastructure, not aviation facilities.

🚨 ERGP30237760: CONSTRUCTION OF LECTURE HALL FOR SELECTED TERTIARY INSTITUTI...
   Agency: FEDERAL COLLEGE OF FISHERIES AND MARINE TECHNOLOGY - LAGOS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The budget item is for construction in Niger Delta states while the Federal College of Fisheries and Marine Technology is specifically located in Lagos and has no mandate to operate in or construct facilities in Niger Delta states.

🚨 ERGP30237767: CONSTRUCTION OF LOW INCOME HOUSING SCHEME IN SELECTED LOCATI...
   Agency: FEDERAL COLLEGE OF FISHERIES AND MARINE TECHNOLOGY - LAGOS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The construction of low income housing schemes is completely outside the mandate of a specialized fisheries and marine technology college whose functions are exclusively focused on education, training, research, and consultancy in fisheries and maritime fields.

🚨 ERGP1246427: CONSTRUCTION AND REHABILITATION OF TOWNSHIP ROAD IN SELECTED...
   Agency: FEDERAL COLLEGE OF AGRICULTURE - ISHIAGU
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The construction and rehabilitation of township roads nationwide falls outside the mandate of an agricultural college focused on training technicians and technologists in agriculture, conducting agricultural research, and providing extension services.

🚨 ERGP12234323: CONSTRUCTION OF MULTIPLE UNITS OF LOW-COST RESIDENTIAL HOUSE...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Construction of residential houses falls outside the Federal Ministry of Works' mandate, which focuses exclusively on roads and bridges infrastructure after housing functions were separated in the October 2024 cabinet reshuffle.

🚨 ERGP1246425: CONSTRUCTION AND REHABILITATION OF RURAL FARM LINK ROAD NATI...
   Agency: FEDERAL COLLEGE OF AGRICULTURE - ISHIAGU
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The construction and rehabilitation of rural farm link roads nationwide is an infrastructure development function that falls outside the college's educational mandate of providing agricultural training, research, and extension services at the diploma level.

🚨 ERGP1246424: CONSTRUCTION OF MODERN MARKETS FOR AGRICULTURAL AND OTHER EC...
   Agency: FEDERAL COLLEGE OF AGRICULTURE - ISHIAGU
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The agency's mandate focuses on agricultural education, training, and research at the diploma level, not on constructing commercial markets for economic activities.

🚨 ERGP30237769: ACQUISITION, FENCING, ROAD CONSTRUCTION, LANDSCAPING & ELECT...
   Agency: FEDERAL COLLEGE OF FISHERIES AND MARINE TECHNOLOGY - LAGOS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: The budget item for low income housing scheme development falls completely outside the agency's mandate which is specifically focused on fisheries and marine technology education, training, and research.

🚨 ERGP27236059: CONSTRUCTION OF ROADS, BUILDINGS AND ELECTRICITY SUPPLY INFR...
   Agency: FEDERAL MINISTRY OF WATER RESOURCES AND SANITATION - HQTRS
   Amount: ₦3,500,000,000
   Confidence: HIGH
   Reason: Construction of roads, buildings and electricity supply infrastructure falls outside the Federal Ministry of Water Resources and Sanitation's mandate, which is specifically focused on water resources development, water supply, sanitation, irrigation, flood control, and dam management rather than general infrastructure development.

🚨 ERGP12234325: CONSTRUCTION AND EQUIPPING OF ULTRAMODERN CONFERENCE CENTER ...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦2,800,000,000
   Confidence: HIGH
   Reason: Construction of conference centers falls outside the Federal Ministry of Works' exclusive mandate which focuses on federal roads, bridges and related transportation infrastructure, not building construction or conference facilities.

🚨 ERGP12231344: REHABILITATION OF EBUTEN - ERO - OUTER MARINA SHORELINE IN L...
   Agency: FEDERAL MINISTRY OF WORKS
   Amount: ₦2,800,000,000
   Confidence: HIGH
   Reason: Shoreline rehabilitation is coastal/marine infrastructure work that falls outside the Federal Ministry of Works' exclusive mandate of constructing, rehabilitating and maintaining federal roads and bridges.

🚨 ERGP25244088: ERGP20241405 - CONSTRUCTION OF GENERAL HOSPITAL IN BENDE FED...
   Agency: FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS
   Amount: ₦2,800,000,000
   Confidence: HIGH
   Reason: Construction of a general hospital is a healthcare infrastructure project that falls under the mandate of health ministries, not the Federal Ministry of Housing and Urban Development which focuses specifically on housing policies, urban development, and physical planning.

🚨 ERGP30237841: CONSTRUCTION AND DEVELOPMENT OF BASIC INFRASTRUCTURES TO ENH...
   Agency: FEDERAL COLLEGE OF FISHERIES AND MARINE TECHNOLOGY - LAGOS
   Amount: ₦2,800,000,000
   Confidence: HIGH
   Reason: The budget item focuses on general rural infrastructure development across the nation, which falls outside the college's specific mandate of providing fisheries and marine technology education, training, and research services.

### Export content

In [34]:
mandate_deviation_to_20_000_projects_path = "data/outputs/mandate_deviation/combined_llm_alignment_results_1_891.csv"
mandate_deviation_to_20_000_projects = pd.read_csv(mandate_deviation_to_20_000_projects_path)

In [35]:
mandate_deviation_to_20_000_projects.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
0,ERGP1102191,IT INFRASTRUCTURE AND ASSOCIATED EQUIPMENT\n,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,9.817500e+07,YES,HIGH,IT infrastructure and associated equipment dir...,0
1,ERGP1102209,PURCHASE OF OFFICE FURNITURE AND FITTINGS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.490738e+07,YES,HIGH,Office furniture and fittings are necessary ad...,0
2,ERGP1205869,PURCHASE OF LAP TOP AND DESKTOP COMPUTERS FOR ...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.107260e+08,YES,HIGH,Purchasing computers for staff official use is...,0
3,ERGP1205905,REMODELING OF SECURITY HOUSE AND BPE MAIN ENTR...,111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+07,PARTIAL,MEDIUM,While the remodeling of BPE's main entrance do...,50
4,ERGP16234836,"""ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT H...",111007001,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+10,NO,HIGH,The budget item refers to acquiring headquarte...,100

In [36]:
llm_alignment_results_remaining_7148_path = "data/outputs/mandate_deviation/llm_alignment_results_remaining_7148.csv"
llm_alignment_results_remaining_7148_projects = pd.read_csv(llm_alignment_results_remaining_7148_path)

In [37]:
llm_alignment_results_remaining_7148_projects.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
0,ERGP15172225,COMPUTERISATION OF THE INTERNAL AUDIT DEPARTME...,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN,15559347.0,PARTIAL,MEDIUM,While computerization of internal audit depart...,50
1,ERGP15172263,ESTABLISHMENT OF CONDUCT OF CORRUPTION INDEX\n,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN,7125580.0,PARTIAL,MEDIUM,While establishing a corruption index is not e...,50
2,ERGP16172270,"CAPACITY BUILDING FOR INFORMATION, ADMIN AND A...",123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN,15680000.0,YES,HIGH,"Capacity building for information, admin and a...",0
3,ERGP16204356,"DIGITIZATION OF VOTE BOOKS, CASH BOOKS, FIXED ...",123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN,13860000.0,NO,HIGH,Digitization of internal financial records and...,100
4,ERGP16204392,ATTENDANCE OF NATIONAL COUNCIL ON IMATION\n,123001001.0,FEDERAL MINISTRY OF INFORMATION AND NATIONAL O...,NaN,3871658.0,YES,HIGH,Attending the National Council on Information ...,0

In [ ]:
# Basic concat
# combined = pd.concat([mandate_deviation_to_20_000_projects, llm_alignment_results_remaining_7148_projects])

# Reset index after stacking
combined_all_budget = pd.concat([mandate_deviation_to_20_000_projects, llm_alignment_results_remaining_7148_projects], ignore_index=True)

In [39]:
combined_all_budget.head()

,code,ergp_line_item,mda_code,agency,mother_ministry,amount,alignment,confidence,reason,mandate_deviation_score
0,ERGP1102191,IT INFRASTRUCTURE AND ASSOCIATED EQUIPMENT\n,111007001.0,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,9.817500e+07,YES,HIGH,IT infrastructure and associated equipment dir...,0
1,ERGP1102209,PURCHASE OF OFFICE FURNITURE AND FITTINGS FOR ...,111007001.0,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.490738e+07,YES,HIGH,Office furniture and fittings are necessary ad...,0
2,ERGP1205869,PURCHASE OF LAP TOP AND DESKTOP COMPUTERS FOR ...,111007001.0,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.107260e+08,YES,HIGH,Purchasing computers for staff official use is...,0
3,ERGP1205905,REMODELING OF SECURITY HOUSE AND BPE MAIN ENTR...,111007001.0,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+07,PARTIAL,MEDIUM,While the remodeling of BPE's main entrance do...,50
4,ERGP16234836,"""ACQUISITION OF BUREAU OF PUBLIC PROCUREMENT H...",111007001.0,BUREAU OF PUBLIC ENTERPRISES (BPE),NaN,1.400000e+10,NO,HIGH,The budget item refers to acquiring headquarte...,100

In [40]:
print(len(combined_all_budget))

27539

In [43]:
llm_alignment_results_combined_all_budget = "data/outputs/mandate_deviation/llm_alignment_results_complete_27_540_projects.csv"
combined_all_budget.to_csv(llm_alignment_results_combined_all_budget, index=False)